final Map autoteileMAP = {
  'Sitz': ['direkt sichtbar','Stoff oder Leder','es gibt oft vier davon','man nimmt darauf Platz'],
  'Dach': ['direkt sichtbar','Metall und Stoff','oben','verhindert das Hineinregnen'],
  'Motor': ['direkt sichtbar','Metall und Kunststoff','vorne','bewegt das Auto'],
  'Rad': ['direkt sichtbar','Stahl oder Aluminium','vorne und hinten je zwei','besteht aus Felge und Reifen'],
  'Achse':['nicht direkt sichtbar','Metall','eine ist vorne und eine hinten','bewegliche Verbindung zwischen Fahrzeug und Rädern'],
  'Batterie': ['nicht direkt sichtbar','Blei','im Motorraum','wenn sie leer ist, braucht man Starthilfe'],
  'Reifen':['direkt sichtbar','Gummi','vorne und hinten je zwei','werden auf die Räder aufgezogen'],
  'Scheinwerfer':['direkt sichtbar','Lampe und Glas','vorne rechts und links','sorgen für Licht auf der Straße'],
  'Lenkrad':['direkt sichtbar','Metall mit Kunststoff oder Leder','vorne links','ringförmiges Objekt zur Drehung der Vorderräder'],
  'Kupplung':['teilweise sichtbar','Metall','verbindet Motor und Getriebe','damit kann man die Gänge schalten'],
  'Zündung':['teilweise sichtbar','Metall','im Motorraum mit Verbindung zum Innenraum','wird mit Autoschlüssel oder Knopf betätigt'],
  'Kofferraum': ['direkt sichtbar','Metall mit Stoff','hinten','zum Transport größerer Gegenstände',],
  'Rückspiegel': ['direkt sichtbar','Glas mit Aluminium oder Silber','vorne oben in der Mitte','zum Beobachten des Verkehrsgeschehens hinter dem Auto'],
  'Handbremse': ['direkt sichtbar','Metall mit Kunststoff oder Leder','rechts vom Fahrer','zur Sicherung des Autos v.a. auf schräger Fläche'],
  'Felge':['direkt sichtbar','Stahl oder Aluminium','vorne und hinten je zwei','äußerer Ring des Rades'],
  'Scheibenwischer': ['direkt sichtbar','Metall mit Gummi','vorne zwei und hinten einer','zum Säubern der Front- oder Heckscheibe bei Regen'],
  'Auspuff': ['direkt sichtbar','Metall','hinten unten','leitet die Abgase nach außen'],
  'Stoßstange': ['direkt sichtbar','Stahl mit Kunststoffhaut','an Front und Heck','minimiert von Unfallschäden'],
  'Klimaanlage': ['nicht direkt sichtbar','Metall','im Motorraum mit Verbindung zum Innenraum','sorgt für angenehme Temperatur und klare Scheiben'],
  'Tachometer': ['direkt sichtbar','Metall','vor dem Fahrer','zeigt die aktuelle Geschwindigkeit an'],
  'Gangschaltung': ['direkt sichtbar','Metall mit Kunststoff oder Leder','rechts vom Fahrer','zur Bedienung des Getriebes mit der Hand'],
  'Bremspedal': ['direkt sichtbar','Metall','im Fußraum des Fahrers','wird beim Starten des Autos getreten'],
  'Handschuhfach': ['direkt sichtbar','Kunststoff','vor dem Beifahrer','zum Transport kleinerer Gegenstände'],
  'Zündkerze': ['nicht direkt sichtbar','Metall und Keramik','im Motorraum','erzeugt einen Funken zum Anlassen des Autos'],
  'Wagenheber': ['nicht direkt sichtbar','Metall','im Kofferraum','wird beim Reifenwechsel zum Hochbewegen des Autos benötigt'],
  'Rückbank': ['direkt sichtbar','Stoff oder Leder','hinter den Vordersitzen','hier sitzen meistens Kinder'],
  'Autotür': ['direkt sichtbar','Metall mit (Kunst-)Stoff oder Leder','vorne und hinten je zwei','muss zum Einsteigen geöffnet werden'],
  'Sicherheitsgurt': ['direkt sichtbar','Nylongewebe mit Metallzunge','vorne und hinten je zwei','Rückhaltesystem zur Sicherheit der Personen im Auto'],
  'Heckscheibe': ['direkt sichtbar','Glas','hinten','ermöglicht die Sicht aus dem Auto nach hinten'],
  'Benzintank': ['nicht direkt sichtbar','Aluminium, Stahl oder Kunststoff','über Hinterachse oder davor unter Rücksitzen','enthält den Kraftstoff'],
  'Schiebedach': ['direkt sichtbar','Glas','oben','Öffnungssystem nach oben'],
  'Kopfstütze': ['direkt sichtbar','Metall mit Stoff oder Leder','eine an jedem Sitz','zum Schutz der Halswirbelsäule bei Unfällen']
};

final Map badezimmerMAP = {
  'Spiegel':['erweiterte Ausstattung','aus Glas','hängt an der Wand','man sieht sich darin'],
  'Kalk': ['erweiterte Ausstattung','eine Ablagerung','entsteht bei hartem Wasser','muss beim Putzen entfernt werden'],
  'Seife': ['erweiterte Ausstattung','eine Lauge','wird mit Wasser benutzt','zum Hände waschen'],
  'Toilette': ['Grundausstattung','aus Porzellan','man setzt sich darauf','wenn man viel getrunken hat'],
  'Handtuch': ['erweiterte Ausstattung','aus Stoff','aus Frottee','zum Abtrocknen'],
  'Badewanne': ['Grundausstattung','aus Porzellan','wird sitzend und liegend benutzt','zum Säubern oder Entspannen'],
  'Waschbecken': ['Grundausstattung','aus Porzellan','hat einen Wasserhahn','zum Reinigen der Hände'],
  'Schminke': ['erweiterte Ausstattung','aus Puder oder Creme','farbliche Hautgestaltung','Puder','Lidschatten','Lippenstift'],
  'Dusche': ['Grundausstattung','oft aus Glas und Porzellan','wird im Stehen benutzt','zum Säubern des Körpers'],
  'Creme': ['erweiterte Ausstattung','eine Art Salbe','wird meist im Gesicht benutzt','bei trockener Haut' ],
  'Föhn': ['erweiterte Ausstattung','funktioniert elektrisch','für die Haare','zum Trocknen'],
  'Zahnbürste': ['erweiterte Ausstattung','meist aus Kunststoff','hat einen kurzen Stiel und Borsten','zum Zähne putzen'],
  'Wasserhahn': ['Grundausstattung','meist aus Metall','zum Hände waschen' ,'zum Auf- und Zudrehen'],
  'Waschlappen': ['erweiterte Ausstattung','aus Frottee','handtellergroßes Textilstück','Körperpflege'],
  'Zahnpasta': ['erweiterte Ausstattung','eine Art Creme','wird mit der Zahnbürste benutzt','zum Zähne reinigen'],
  'Nagellack': ['erweiterte Ausstattung','ein Kosmetikprodukt','farbliche Nagelgestaltung','meist rot oder rosa'],
  'Nagelschere': ['erweiterte Ausstattung','aus Metall','zum Schneiden','für Finger- und Fußnägel'],
  'Shampoo': ['erweiterte Ausstattung','eine Art Creme','für die Haare','zum Waschen'],
  'Duschkabine': ['Grundausstattung','meist aus Glas','grenzt eine Brause von der Umgebung ab','mit Tür zum Öffnen und Schließen'],
  'Fliese': ['Grundausstattung','aus Stein oder Marmor','meist viereckig','Bodenbelag'],
  'Handtuchhalter': ['erweiterte Ausstattung','aus Plastik oder Metall','zum Aufhängen','für Handtücher'],
  'Duschvorhang': ['erweiterte Ausstattung','meist aus Stoff','grenzt eine Brause von der Umgebung ab','zum Hin- und Herschieben'],
  'Zahnseide': ['erweiterte Ausstattung','aus Kunststoff oder textiler Faser','zum Reinigen von Zwischenräumen im Mund','gewachst und ungewachst'],
  'Badezimmerschrank': ['Grundausstattung','meist aus Holz','zur Aufbewahrung','für Badezimmerartikel'],
  'Klobürste': ['erweiterte Ausstattung','meist aus Plastik','hat einen langen Stiel und Borsten','zum Reinigen der Toilette'],
  'Zahnputzbecher': ['erweiterte Ausstattung','meist aus Plastik','zum Mund ausspülen','Zahnbürste steht meist darin'],
  'Duschgel': ['erweiterte Ausstattung','eine Art Creme','für den Körper','zum Waschen'],
  'Badematte': ['erweiterte Ausstattung','meist aus Stoff','meist viereckig','Bodenbelag'],
  'Duschhaube': ['erweiterte Ausstattung','meist aus Plastik','für die Haare','Haare bleiben damit trocken'],
  'Duschkopf': ['Grundausstattung','meist aus Metall','Wasser kommt da raus','zum Abbrausen']
};

final Map bauernhofMAP = {
  'Hund': ['Tier','vier Pfoten','bewacht und hütet','bellt und knurrt'],
  'Milch': ['Nahrungsmittel','Getränk','weiß','von der Kuh'],
  'Pferd': ['Tier','vier Beine und Hufe','wiehert','wird geritten'],
  'Bauer': ['Mensch','füttert Tiere','betreibt Ackerbau','Landwirt'],
  'Eier': ['Nahrungsmittel','von Hühnern','mit Schale','innen weiß und gelb'],
  'Hahn': ['Tier','kräht','bunter Kamm','männliches Huhn'],
  'Wiese': ['Nutzfläche','grün','aus Gras','wird gemäht'],
  'Katze': ['Tier','vier Pfoten','jagt Mäuse','schnurrt und miaut'],
  'Getreide': ['Nahrungsmittel','hat Ähren und Körner','wird auf dem Feld angebaut','Gerste, Weizen, Roggen'],
  'Stall': ['Gebäude','für Tiere','oft in Boxen unterteilt','Schlafplatz'],
  'Käse': ['Nahrungsmittel','meist gelb','aus Milch','Gouda, Appenzeller'],
  'Futter': ['Nahrungsmittel','für Tiere','Getreide und Gemüse','Tiernahrung'],
  'Schwein': ['Tier','meist rosa','Ringelschwanz','grunzt'],
  'Zaun': ['Begrenzung','Trennung von Grundstücken und Feldern','mit Pfosten oder Latten','aus Holz oder Draht'],
  'Kuh': ['Tier','oft schwarz-weiß','hat einen Euter','gibt Milch'],
  'Huhn': ['Tier','häufig braun oder weiß','Schnabel und Federn','legt Eier'],
  'Scheune': ['Gebäude','groß und mit Holzbalken','dient als Lagerraum','für Stroh, Getreide und Fahrzeuge'],
  'Spaten': ['Gartenwerkzeug','zum Graben','drückt man mit dem Fuß in die Erde','große eckige Schaufel'],
  'Teich': ['Gewässer','für Fische und Enten','mit Süßwasser','kleiner als ein See'],
  'Schaf': ['Tier','häufig weiß','dickes Fell','wird zu Wolle verarbeitet'],
  'Kartoffel': ['Nahrungsmittel','Gemüse','außen braun und innen gelb','wird auch Erdapfel genannt'],
  'Ziege': ['Tier','weiß, braun oder schwarz','hat Hörner','aus der Milch wird Käse hergestellt'],
  'Beet': ['kleines Stück Boden','häufig grün und bunt','zieht landwirtschaftliche Geräte','mit Blumen, Kräutern oder Gemüse'],
  'Traktor': ['Fahrzeug','für das Feld geeignet','im Garten oder vor dem Haus','parkt in der Scheune '],
  'Rechen': ['Gartenwerkzeug','für Laub auf der Wiese','häufig Holzstiel mit Metallstäben','zum Kehren'],
  'Hundehütte': ['Gebäude','häufig aus Holz und Metall','Schlafplatz für ein Tier','der Hund lebt darin'],
  'Gummistiefel': ['Kleidungsstück','für die Füße','aus Kunststoff','wird bei Matsch und Regen getragen'],
  'Milchkanne': ['Gefäß','it Henkel','beinhaltet Flüssigkeit','von Kühen oder Ziegen'],
  'Mistgabel': ['Gartenwerkzeug','mit Holzstiel','hat drei Zinken','zum Säubern der Ställe'],
  'Latzhose': ['Kleidungsstück','Arbeitskleidung','hat zwei Träger','spezielle Form einer Hose ']
};

final Map berufeMAP = {
  'Arzt': ['arbeitet viel mit Menschen','erfordert ein Studium','stellt Diagnosen','wird oft bei Schmerzen aufgesucht'],
  'Lehrer': ['arbeitet viel mit Menschen','erfordert ein Studium','korrigiert Arbeiten oder Tests','unterrichtet eine Klasse'],
  'Maler': ['arbeitet viel mit Materialien','erfordert eine Ausbildung','streicht Wände','arbeitet mit Farbe und Pinsel'],
  'Politiker': ['arbeitet viel mit Menschen','ohne Ausbildung möglich','hält Reden','wird gewählt'],
  'Sekretär': ['arbeitet viel mit Materialien','erfordert eine Ausbildung','schreibt Briefe und plant Termine','nimmt stellvertretend Anrufe entgegen'],
  'Schauspieler': ['arbeitet viel mit Menschen','erfordert ein Studium/eine Ausbildung','auf der Bühne oder im Fernsehen','spielt verschiedene Rollen'],
  'Sänger': ['arbeitet viel mit Menschen','erfordert ein Studium/eine Ausbildung','auf der Bühne oder im Radio','benutzt die Stimme zum Arbeiten'],
  'Koch': ['arbeitet viel mit Materialien','erfordert eine Ausbildung','bereitet Gerichte zu','arbeitet in der Küche'],
  'Anwalt': ['arbeitet viel mit Menschen','erfordert ein Studium','berät bei Rechtsfragen','Verteidiger oder Ankläger im Gericht'],
  'Erzieher': ['arbeitet viel mit Menschen','erfordert eine Ausbildung','spielt oder bastelt oft','fördert Kinder'],
  'Gärtner': ['arbeitet viel mit Materialien','erfordert eine Ausbildung','streut Samen in die Erde','kümmert sich um Pflanzen'],
  'Dolmetscher': ['arbeitet viel mit Menschen','erfordert ein Studium','hilft bei der Verständigung zwischen Personen','übersetzt Texte in andere Sprachen'],
  'Polizist': ['arbeitet viel mit Menschen','erfordert eine Ausbildung','ermittelt bei einem Gesetzesbruch','kann Personen verhaften'],
  'Bäcker': ['arbeitet viel mit Materialien','erfordert eine Ausbildung','bereitet Teig für den Ofen vor','stellt Brötchen und Brot her'],
  'Friseur': ['arbeitet viel mit Menschen','erfordert eine Ausbildung','verändert etwas am Aussehen','schneidet Haare'],
  'Therapeut': ['arbeitet viel mit Menschen','erfordert ein Studium/eine Ausbildung','erfragt die Vorgeschichte des Patienten','führt eine Therapie mit Patienten durch'],
  'Fotograf': ['arbeitet viel mit Materialien','erfordert ein Studium/eine Ausbildung','benötigt eine Kamera','macht Bilder von Personen oder Ojekten'],
  'Kassierer': ['arbeitet viel mit Menschen','ohne Ausbildung möglich','nimmt Geld entgegen','tippt Preise in eine Kasse ein'],
  'Uhrmacher': ['arbeitet viel mit Materialien','erfordert eine Ausbildung','stellt Zeitmessgeräte her','repariert Uhren'],
  'Klempner': ['arbeitet viel mit Materialien','erfordert eine Ausbildung','bearbeitet Gegenstände aus Metall','wird bei einem verstopften Abfluss gerufen'],
  'Elektriker': ['arbeitet viel mit Materialien','erfordert eine Ausbildung','misst Spannung und Widerstand','repariert elektrische Anlagen'],
  'Bademeister': ['arbeitet viel mit Menschen','erfordert eine Ausbildung','überwacht den Betrieb eines Schwimmbads','rettet Menschen aus dem Wasser'],
  'Informatiker': ['arbeitet viel mit Materialien','erfordert ein Studium/eine Ausbildung','arbeitet am Computer','programmiert eine Software oder Internetseite'],
  'Masseur': ['arbeitet viel mit Menschen','erfordert eine Ausbildung','führt Bewegungen mit Händen aus','löst Verspannungen am Körper des Klienten'],
  'Dachdecker': ['arbeitet viel mit Materialien','erfordert eine Ausbildung','bringt Dämmstoff an Gebäuden an','deckt Dächer mit Ziegeln'],
  'Konditor': ['arbeitet viel mit Materialien','erfordert eine Ausbildung','backt für spezielle Anlässe','backt Torten'],
  'Tierpfleger': ['arbeitet viel mit Menschen','erfordert eine Ausbildung','füttert und pflegt Lebewesen','kümmert sich um Vier- und Zweibeiner'],
  'Flugbegleiter': ['arbeitet viel mit Menschen','erfordert eine Ausbildung','fliegt in andere Länder','kümmert sich um Passagiere in einem Flugzeug'],
  'Hotelkaufmann': ['arbeitet viel mit Materialien','erfordert eine Ausbildung','gibt Zimmerschlüssel an Gäste aus','arbeitet in der Rezeption in einem Hotel'],
  'Müllmann': ['arbeitet viel mit Materialien','erfordert eine Ausbildung','entsorgt Abfälle','leert Mülltonnen']
};

final Map deutscheStaedteMAP = {
  'Berlin': ['Stadtstaat','Hauptstadt','Reichstagsgebäude','Brandenburger Tor'],
  'München': ['Bayern','Landeshauptstadt','Frauenkirche','Englischer Garten'],
  'Leipzig': ['Sachsen','größte Stadt in Sachsen','Völkerschlachtdenkmal','Nikolaikirche'],
  'Hamburg': ['Stadtstaat','Freie und Hansestadt','Speicherstadt','Reeperbahn'],
  'Essen': ['Nordrhein-Westfalen','Großstadt im Ruhrgebiet','Museum Folkwang','Villa Hügel'],
  'Dresden': ['Sachsen','Landeshauptstadt','Zwinger','Frauenkirche'],
  'Frankfurt am Main': ['Hessen','größte Stadt in Hessen','Römer','Goethe-Haus'],
  'Köln': ['Nordrhein-Westfalen','bevölkerungsreichste Stadt in NRW','Museum Ludwig','Dom'],
  'Stuttgart': ['Baden-Württemberg','Landeshauptstadt','Schloss Solitude','Wilhelma'],
  'Hannover': ['Niedersachsen','Landeshauptstadt','Herrenhäuser Gärten','Maschsee'],
  'Düsseldorf': ['Nordrhein-Westfalen','Landeshauptstadt','Rheinturm','Königsallee'],
  'Bremen': ['Stadtstaat','Freie Hansestadt','Universum','Roland'],
  'Potsdam': ['Brandenburg','Landeshauptstadt','Holländisches Viertel','Sanssouci'],
  'Weimar': ['Thüringen','in der Mitte von Thüringen','Bauhaus-Museum','Goethe-Schiller-Denkmal'],
  'Münster': ['Nordrhein-Westfalen','in Westfalen','Aasee','St.-Paulus-Dom'],
  'Lübeck': ['Schleswig-Holstein','Hansestadt','Marzipan','Holstentor'],
  'Regensburg': ['Bayern','in der Oberpfalz','Donau-Schifffahrtsmuseum','Steinerne Brücke'],
  'Tübingen': ['Baden-Württemberg','klassische Universitätsstadt','Paul-Horn-Arena','Stiftskirche'],
  'Aachen': ['Nordrhein-Westfalen','Kurstadt','Karl der Große','Printen'],
  'Mannheim': ['Baden-Württemberg','ehemalige Residenzstadt der Kurpfalz','Wasserturm','Quadratestadt'],
  'Trier': ['Rheinland-Pfalz','älteste Stadt Deutschlands','Karl-Marx-Haus','Porta Nigra'],
  'Dortmund': ['Nordrhein-Westfalen','bevölkerungsreichste Stadt im Ruhrgebiet','das "U"','Borussia'],
  'Koblenz': ['Rheinland-Pfalz','im Norden von Rheinland-Pfalz','Festung Ehrenbreitstein','Deutsches Eck'],
  'Ulm': ['Baden-Württemberg','im Südosten der Schwäbischen Alb','Münster','Spatz'],
  'Chemnitz': ['Sachsen','im Südwesten von Sachsen','Siegertsches Haus','Roter Turm'],
  'Erlangen': ['Bayern','in Mittelfranken','Botanischer Garten','Hugenottenkirche'],
  'Bochum': ['Nordrhein-Westfalen','Zentrum des mittleren Ruhrgebiets','Zeiss Planetarium','Deutsches Bergbau-Museum'],
  'Ludwigshafen': ['Rheinland-Pfalz','größte Stadt der Pfalz','Wilhelm-Hack-Museum','BASF'],
  'Solingen': ['Nordrhein-Westfalen','im Bergischen Land','Schloss Burg','Zwilling-Messer'],
  'Idstein': ['Hessen','Rheingau-Taunus-Kreis','Hexenturm','Sitz der Hochschule Fresenius']
};

final Map fahrzeugeMAP = {
  'Zug': ['fährt auf Schienen','durch Motor betrieben','transportiert viele Personen','fährt in einen Bahnhof ein'],
  'Schiff': ['fährt auf dem Wasser','durch Motor betrieben','transportiert viele Personen oder Fracht','läuft in einen Hafen ein'],
  'Auto': ['fährt auf Rädern','durch Motor betrieben','transportiert mehrere Personen','hat einen Kofferraum'],
  'Panzer': ['fährt auf Ketten','durch Motor betrieben','Militärfahrzeug','hat Tarnfarben'],
  'Straßenbahn': ['fährt auf Schienen','durch Motor betrieben','transportiert viele Personen','fährt innerhalb der Stadt'],
  'Fahrrad': ['fährt auf Rädern','durch Muskelkraft betrieben','transportiert eine Person','hat einen Sattel'],
  'Bus': ['fährt auf Rädern','durch Motor betrieben','transportiert viele Personen','fährt Kinder zur Schule'],
  'Taxi': ['fährt auf Rädern','durch Motor betrieben','transportiert mehrere Personen','ist meist weiß'],
  'Motorrad': ['fährt auf Rädern','durch Motor betrieben','transportiert höchstens zwei Personen','wird mit Helm gefahren'],
  'Lastkraftwagen': ['fährt auf Rädern','durch Motor betrieben','transportiert Fracht','hat Fahrverbot an Sonn- und Feiertagen'],
  'Fähre': ['fährt auf dem Wasser','durch Motor betrieben','transportiert viele Personen und Autos','fährt häufig zwischen Festland und Inseln'],
  'UBahn': ['fährt auf Schienen','durch Motor betrieben','transportiert viele Personen','fährt unterirdisch'],
  'Transporter': ['fährt auf Rädern','durch Motor betrieben','Umzugsfahrzeug','kleiner als ein LKW'],
  'Bagger': ['fährt auf Rädern','durch Motor betrieben','Arbeitsfahrzeug','wird auf Baustellen benutzt'],
  'Limousine': ['fährt auf Rädern','durch Motor betrieben','transportiert mehrere Personen','wird oft von einem Chauffeur gefahren'],
  'Tandem': ['fährt auf Rädern','durch Muskelkraft betrieben','transportiert höchstens zwei Personen','Fahrrad für zwei Personen'],
  'Motorroller': ['fährt auf Rädern','durch Motor betrieben','transportiert höchstens zwei Personen','hat ein Trittbrett statt Fußrasten'],
  'Gabelstapler': ['fährt auf Rädern','durch Motor betrieben','Arbeitsfahrzeug','transportiert Paletten'],
  'Cabriolet': ['fährt auf Rädern','durch Motor betrieben','transportiert mehrere Personen','kann das Dach öffnen'],
  'Hundeschlitten': ['fährt auf Kufen','durch Muskelkraft betrieben','transportiert höchstens Personen oder Fracht','wird von Tieren über den Schnee gezogen'],
  'Dreirad': ['fährt auf Rädern','durch Muskelkraft betrieben','transportiert eine Person','Tretfahrzeug für kleine Kinder'],
  'Dampfwalze': ['fährt auf Rollen','durch Motor betrieben','Arbeitsfahrzeug','wird zum Verdichten der Straßendecke genutzt'],
  'Mofa': ['fährt auf Rädern','durch Motor betrieben','transportiert höchstens zwei Personen','motorisiertes Fahrrad'],
  'Polizeiauto': ['fährt auf Rädern','durch Motor betrieben','Arbeitsfahrzeug','fährt oft mit Blaulicht'],
  'Feuerwehrauto': ['fährt auf Rädern','durch Motor betrieben','Arbeitsfahrzeug','löscht Flammen'],
  'Dampflokomotive': ['fährt auf Schienen','durch Motor betrieben','transportiert viele Personen','wird von Wasserdampf angetrieben'],
  'Bollerwagen': ['fährt auf Rädern','durch Muskelkraft betrieben','transportiert kleine Kinder oder Gegenstände','muss gezogen werden'],
  'Einrad': ['fährt auf Rädern','durch Muskelkraft betrieben','transportiert eine Person','hat einen Sattel und nur einen Reifen'],
  'Abschleppwagen': ['fährt auf Rädern','durch Motor betrieben','Arbeitsfahrzeug','transportiert andere Fahrzeuge'],
  'Seifenkiste': ['fährt auf Rädern','durch Hangabtriebskraft bewegt','transportiert höchstens zwei Personen','ist oft selbstgebaut']
};

final Map gartenMAP = {
  'Bank': ['Gegenstand','aus Holz oder Stein','zum Sitzen','für mehrere Personen'],
  'Mauer': ['Gegenstand','aus Stein','grenzt einen Bereich ein','besteht aus vielen Steinen'],
  'Baum': ['Pflanzenwelt','grün und braun','Spendet Schatten','hat Stamm und Äste'],
  'Gemüse': ['Pflanze','verschiedene Farben','wächst im speziellen Beet','zum Essen'],
  'Blume': ['Pflanze','verschiedene Farben','wächst auf der Wiese','hat Blüten'],
  'Zaun': ['Gegenstand','aus Holz oder Metall','grenzt einen Bereich ein','hat Latten und Pfosten'],
  'Blumentopf': ['Gegenstand','aus Ton oder Kunststoff','innen hohl und meist rund','steht meist auf der Fensterbank'] ,
  'Schuppen': ['Gegenstand','aus Holz','groß und eckig','zum Geräte lagern'],
  'Laub': ['Pflanze','gelb, rot oder braun','viele einzelne Teile','besteht aus vielen Blättern'],
  'Rasen': ['Pflanze','grün','mit Gras bewachsene Fläche','wird gemäht'],
  'Unkraut': ['Pflanze','verschiedene Farben','wuchert schnell','wird aus Beet entfernt'],
  'Kräuter': ['Pflanze','grün','zum Essen','zum Würzen'],
  'Spaten': ['Gegenstand','aus Holz und Metall','für die Gartenarbeit','zum Graben'],
  'Schere': ['Gegenstand','aus Metall und Kunststoff','für die Gartenarbeit','zum Pflanzen schneiden'],
  'Handschuh': ['Gegenstand','aus Stoff, Gummi oder Latex','bedeckt ein Körperteil','zum Schutz bei der Gartenarbeit'],
  'Liegestuhl': ['Gegenstand','aus Holz oder Kunststoff','zum Ausruhen in der Waagerechten','zum Zusammenklappen'],
  'Sonnenschirm': ['Gegenstand','aus Stoff und Metall','groß und mit einer Stange und Stoff','spendet Schatten'],
  'Grill': ['Gegenstand','aus Metall','zum Erhitzen','zum Essen zubereiten'],
  'Gießkanne': ['Gegenstand','aus Kunststoff oder Metall','mit siebartigem Aufsatz','zum Pflanzen bewässern'],
  'Hängematte': ['Gegenstand','aus Stoff','zum Liegen','zum Schaukeln'],
  'Sandkasten': ['Gegenstand','aus Holz','großer und meist eckig','Kinder bauen darin Burgen'],
  'Harke': ['Gegenstand','aus Metall und Holz','für die Gartenarbeit','zum Lockern der Erde'],
  'Rechen': ['Gegenstand','aus Metall und Holz','für die Gartenarbeit','zum Laub zusammen kehren'],
  'Regentonne': ['Gegenstand','aus Kunststoff','groß, rund und innen hohl','zum Wasser sammeln'],
  'Rasenmäher': ['Gegenstand','aus Kunststoff und Metall','großer und verursacht Lärm','zum Gras kürzen'],
  'Vogelhaus': ['Gegenstand','aus Holz','besitzt ein Dach','Futterstelle für fliegende Tiere'],
  'Rutsche': ['Gegenstand','aus Kunststoff oder Metall','groß mit schiefer Ebene','Kinder gleiten beim Spielen herunter'],
  'Wasserschlauch': ['Gegenstand','aus Kunststoff oder Gummi','langer und innen hohl','Wasser wird darin transportiert'],
  'Setzling': ['Pflanze','grün','klein','junger Pflanzenableger'],
  'Blumenerde': ['Pflanze','dunkelbraun','feinkörniges Gemisch','für Zierpflanzen geeigneter Nährboden']
};

final Map gemueseMAP = {
  'Salat': ['wächst auf dem Feld','meist grün','wird geputzt und dann zubereitet','wird oft mit Dressing zubereitet'],
  'Mais': ['wächst auf dem Feld','gelb','wird geschält und gekocht','die Körner wachsen an Kolben'],
  'Zwiebel': ['wächst in der Erde','weiß oder rot','wird geschält und geschnitten','beim Schneiden brennen die Augen'],
  'Linse': ['wächst am Strauch','rot, gelb oder braun','wird eingeweicht und dann gekocht','Hülsenfrucht, die oft als Eintopf serviert wird'],
  'Kartoffel': ['wächst in der Erde','braun und gelb','wird geschält und gekocht','daraus werden Pommes Frites gemacht'],
  'Paprika': ['wächst am Strauch','rot, grün oder gelb','wird gewaschen und die Kerne entfernt','Schote mit Kammern und Samen'],
  'Pilz': ['wächst meist im Wald','oft weiß oder braun','wird geputzt und dann zubereitet','kann auch giftig sein'],
  'Blumenkohl': ['wächst auf dem Feld','weiß','wird geputzt und die Röschen abgetrennt','eine Form von Kohl'],
  'Spinat': ['wächst auf dem Feld','grün','wird gewaschen und gekocht','wird oft mit Kartoffel und Ei serviert'],
  'Spargel': ['wächst in der Erde','weiß oder grün','wird geschält und gekocht','wird oft mit Sauce Hollandaise serviert'],
  'Knoblauch': ['wächst in der Erde','weiß','wird geschält und geschnitten oder gepresst','langanhaltender und starker Geruch'],
  'Gurke': ['wächst am Strauch','grün','wird oft geschält und geschnitten','kann man sauer einlegen'],
  'Sellerie': ['wächst in der Erde','weiß oder beige','wird geschält und gekocht','gehört zum Suppengrün'],
  'Tomate': ['wächst am Strauch','rot','wird gewaschen und geschnitten','viele machen daraus Soße zu Nudeln'],
  'Bohne': ['wächst am Strauch','meist grün','wird gewaschen und gekocht','das Innere ist von einer Hülse umgeben'],
  'Rhabarber': ['wächst am Boden','meist rot','wird geschält und zubereitet','wird oft zu Kompott verarbeitet'],
  'Rosenkohl': ['wächst auf dem Feld','grün und rund','vor dem Kochen werden die äußeren Blätter entfernt','wird meist als Beilage serviert'],
  'Weißkohl': ['wächst auf dem Feld','weiß oder hellgrün','wird geschnitten und gekocht','eine Form von Kohl'],
  'Ingwer': ['wächst in der Erde','braun und gelb','wird geschnitten und gekocht','wird oft als Gewürz verwendet'],
  'Rotkohl': ['wächst auf dem Feld','rot','wird geschnitten und gekocht','wird im Winter oft als Beilage serviert'],
  'Grünkohl': ['wächst auf dem Feld','grün','wird geschnitten und gekocht','eine Form von Kohl'],
  'Artischocke': ['wächst auf dem Feld','grün','wird gewaschen und der holzige Stiel entfernt','sieht aus wie eine Blume'],
  'Lauch': ['wächst auf dem Feld','grün und weiß','wird geputzt und geschnitten','gibt es als Stange zu kaufene'],
  'Wirsing': ['wächst auf dem Feld','grün','wird gewaschen und die Blätter abgetrennt','wird im Winter oft als Beilage serviert'],
  'Karotte': ['wächst auf dem Feld','orange','wird oft geschält und geschnitten','wird roh oder gekocht gegessen'],
  'Brokkoli': ['wächst auf dem Feld','grün','wird geputzt und die Röschen abgetrennt','eine Form von Kohl'],
  'Aubergine': ['wächst am Strauch','violett','wird geputzt und gekocht','wird auch Eierfrucht genannt'],
  'Peperoni': ['wächst am Strauch','rot oder grün','wird gewaschen und die Kerne entfernt','meist sehr scharf'],
  'Süßkartoffel': ['wächst in der Erde','rot oder orange','wird geschält und gekocht','eine Form der Knollenpflanze'],
  'Zucchini': ['wächst auf dem Feld','grün','wird gewaschen und geschnitten','sieht einer Gurke ähnlich']
};

final Map getraenkeMAP = {
  'Wasser': ['ohne Alkohol','durchsichtig und klar','mit oder ohne Kohlensäure','man kann sich auch damit waschen'],
  'Kaffee': ['ohne Alkohol','braun','enthält oft Koffein','wird oft mit Milch getrunken'],
  'Milch': ['ohne Alkohol','weiß','wird oft mit Kaffee getrunken','daraus wird Käse oder Joghurt gemacht'],
  'Bier': ['meist mit Alkohol','häufig gelb oder braun','enhält Hopfen, Malz, Hefe und Wasser','bekannte Sorten sind Pils und Export'],
  'Tee': ['ohne Alkohol','häufig grün oder braun','mit Früchten oder Kräutern','in Beuteln oder lose verpackt'],
  'Sekt': ['mit Alkohol','weiß, rot oder rosé','wird zum Anstoßen verwendet','trocken oder halbtrocken'],
  'Rotwein': ['mit Alkohol','rot','wird oft in Glasflaschen mit Korken abgefüllt','wird aus Trauben hergestellt'],
  'Rum': ['mit Alkohol','braun','hochprozentig','reift oft in einem Holzfass'],
  'Kakao': ['ohne Alkohol','braun oder weiß','wird mit Milch zubereitet','schmeckt nach Schokolade'],
  'Champagner': ['mit Alkohol','häufig hellgelb','wird oft zum Anstoßen verwendet','ein teures Getränk'],
  'Weißwein': ['mit Alkohol','häufig hellgelb','wird oft in Glasflaschen mit Korken abgefüllt','wird aus Trauben hergestellt'],
  'Likör': ['mit Alkohol','unterschiedliche Farben','hochprozentig','enthält viel Zucker und ist eher dickflüssig'],
  'Limonade': ['ohne Alkohol','unterschiedliche Farben','Erfrischungsgetränk mit Kohlensäure','süß und oft mit Zitronengeschmack'],
  'Nektar': ['ohne Alkohol','unterschiedliche Farben','dickflüssig','wird aus Fruchtmark und Wasser hergestellt'],
  'Cola': ['ohne Alkohol','dunkelbraun','enhält oft Koffein','enthält viel Zucker'],
  'Orangensaft': ['ohne Alkohol','orange','wird durch Pressen einer Frucht gewonnen','schmeckt süß und wird gerne zum Frühstück getrunken'],
  'Apfelsaft': ['ohne Alkohol','häufig hellgelb','wird durch Pressen einer Frucht gewonnen','schmeckt süß und wird gerne von Kindern getrunken'],
  'Glühwein': ['mit Alkohol','häufig rot','wird heiß serviert','wird auf dem Weihnachtsmarkt getrunken'],
  'Apfelwein': ['mit Alkohol','häufig hellgelb','wird aus einer Frucht gewonnen','wird meistens mit Wasser gespritzt'],
  'Tomatensaft': ['ohne Alkohol','rot','wird aus einem Gemüse hergestellt','wird gerne im Flugzeug getrunken'],
  'Radler': ['mit Alkohol','hellgelb','wird gerne im Sommer getrunken','besteht aus Bier und Limonade'],
  'Fanta': ['ohne Alkohol','gelb','wird künstlich hergestellt','süßes Getränk der Coca-Cola-Company'],
  'Kirschsaft': ['ohne Alkohol','dunkelrot','wird häufig aus sauren Früchten gewonnen','wird mit Wasser verdünnt und gesüßt'],
  'Whiskey': ['mit Alkohol','häufig golden','wird durch Destillation von Getreide gewonnen','wird oft aus einem Glas mit dickem Glasboden getrunken'],
  'Ananassaft': ['ohne Alkohol','hellgelb','wird aus einer Frucht gemacht','schmeckt süß und wird oft in Cocktails verwendet'],
  'Karottensaft': ['ohne Alkohol','orange','wird aus einem Gemüse hergestellt','eher dickflüssig, mit viel Vitamin A'],
  'Eistee': ['ohne Alkohol','häufig dunkelbraun','wird heiß hergestellt und schnell abgehült','meist Schwarztee mit Zitronensaft'],
  'Bowle': ['mit Alkohol','unterschiedliche Farben','wird mit Sekt gemacht','wird meist mit Fruchtstücken serviert'],
  'Hefeweizen': ['mit Alkohol','gelb','wird aus einem Getreide hergestellt','wird aus einem speziellen hohen Glas getrunken'],
  'Cappuccino': ['ohne Alkohol','braun und weiß','enthält Koffein','Espresso mit heißer Milch und Milchschaum']
};


final Map hauptstaedteMAP = {
  'Berlin': ['Mitteleuropa','Deutschland','Reichstagsgebäude','Brandenburger Tor'],
  'Paris': ['Westeuropa','Frankreich','Louvre','Eiffelturm'],
  'Wien': ['Mitteleuropa','Österreich','Stephansdom','Schloss Schönbrunn'],
  'London': ['Nordwesteuropa','Großbritannien','Tower Bridge','Big Ben'],
  'Rom': ['Südeuropa','Italien','Spanische Treppe','Colosseum'],
  'Moskau': ['Osteuropa','Russland','Roter Platz','Kreml'],
  'Prag': ['Osteuropa','Tschechien','Veitsdom','Karlsrbrücke'],
  'Washington': ['Nordamerika','USA','Capitol','Weißes Haus'],
  'Athen': ['Südeuropa','Griechenland','Pathenon','Akropolis '],
  'Brüssel': ['Westeuropa','Belgien','Atomium ','Manneken Pis'],
  'Madrid': ['Südwesteuropa','Spanien','Plaza Major','Museo del Prado'],
  'Budapest': ['Osteuropa','Ungarn','Burgpalast','Kettenbrücke'],
  'Peking': ['Ostasien','China','Himmelstempel','Verbotene Stadt'],
  'Stockholm': ['Nordeuropa','Schweden','Vasa-Museum','Gamla stan'],
  'Kopenhagen': ['Nordeuropa','Dänemark','Kleine Meerjungfrau','Schloss Amalienborg'],
  'Helsinki': ['Nordeuropa','Finnland','Dom','Senatsplatz'],
  'Tokio': ['Ostasien','Japan','Senso-ji-Tempel','Meiji-Schrein'],
  'Lissabon': ['dwesteuropa','Portugal','Torre de Belém','Castelo de São Jorge'],
  'Ankara': ['Vorderasien','Türkei','Kocatepe-Moschee','Anıtkabir'],
  'Oslo': ['Nordeuropa','Norwegen','Festung Akershus','Fjord'],
  'Kiew': ['Osteuropa','Ukraine','Sophienkathedrale','Höhlenkloster'],
  'Teheran': ['Naher Osten','Iran','Golestanpalast','Freiheitsturm'],
  'Bagdad': ['Naher Osten','Irak','al-Schahid-Monument','Al-Jawadain Schrein'],
  'Dublin': ['Westeuropa','Irland','Trinity College','Temple Bar'],
  'Hanoi': ['Südostasien','Vietnam','Hanoi Hilton','Ho Chi Minh-Mausoleum'],
  'Havanna': ['Große Antillen','Kuba','Uferpromenade Malécon','Altstadt La Habana Viejo'],
  'Bangkok': ['Südostasien','Thailand','Großer Palast','Wat Arun'],
  'Ottawa': ['Nordamerika','Kanada','Rideau Canal','Parlamentshügel'],
  'Nairobi': ['Ostafrika','Kenia','Karen Blixen Museum','Nationalpark'],
  'NeuDelhi': ['Südasien','Indien','Qutb Minar','Rotes Fort']
};

final Map hausbauMAP = {
  'Farbe': ['Material','dickflüssige Masse','in Eimern zu kaufen','damit werden Wände gestrichen'],
  'Holz': ['Material','meist braun','daraus bestehen Dachbalken','Ausgangsmaterial sind Bäume'],
  'Ingenieur': ['Beruf','erfordert ein Studium','setzt Bauplanung um','Experte für Technik'],
  'Hammer': ['Werkzeug','aus Holz und Stahl','besteht aus Kopf und Stiel','zum Einschlagen von Nägeln'],
  'Architekt': ['Beruf','erfordert ein Studium','erstellt den Entwurf von Bauwerken','entwirft Baupläne'],
  'Rohr': ['Material','aus Stahl oder Kunststoff','runder Hohlkörper','Transportmittel für Flüssigkeiten und Gase'],
  'Lastkraftwagen': ['Fahrzeug','hat Fahrerkabine und Ladefläche','kann bis zu 40 Tonnen tragen','Transportmittel für Güter'],
  'Maurer': ['Beruf','erfordert eine Ausbildung','Hauptbauhandwerker des Rohbaus','erstellt Fundament, Wände und Decken'],
  'Helm': ['Schutzausrüstung','aus Kunststoff','häufig in Signalfarben','wird auf dem Kopf getragen'],
  'Beton': ['Material','erst flüssig und später fest','besteht aus Zement, Sand, Kies und Wasser','Baustoff für Fundament, Wände und Decken'],
  'Gerüst': ['Arbeitshilfe','aus Stahlstreben','wird an der Baustelle aufgebaut','für Arbeiten in der Höhe'],
  'Besen': ['Arbeitsgerät','aus Holz und Borsten','besteht meist aus Stiel und Reisig','zum Zusammenkehren von Schmutz'],
  'Schutt': ['Material','aus Steinen','fällt beim Abriss von Häusern an','Gesteinsbruchstücke'],
  'Tapete': ['Material','aus Papier oder Kunststoff','in Rollen zu kaufen','wird an Wänden angebracht'],
  'Zement': ['Material','aus Kalkstein, Ton und Mergel','in Säcken zu kaufen','wesentlicher Bestandteil von Beton'],
  'Kran': ['Fahrzeug','zum Verladen von Lasten','Turm mit Drehwerk','Hebehilfe für sehr schwere Güter'],
  'Bagger': ['Fahrzeug','hat einen Greifarm mit großer Schaufel','löst und bewegt Boden und Felsen','Fahrzug zum Aushuben der Baugrube'],
  'Polier': ['Beruf','erfordert eine Ausbildung','Bindeglied zwischen Bauarbeitern und Bauleitung','Leiter einer Baustelle oder eines Baustellenabschnittes'],
  'Rohbau': ['Gebäudezustand','erster Bauabschnitt','wird mit dem Richtfest gefeiert','Bauwerk mit Dachkonstruktion ohne Fenster und Türen'],
  'Dachdecker': ['Beruf','erfordert eine Ausbildung','arbeitet häufig in der Höhe','führt Dach- und Abdichtungsarbeiten aus'],
  'Schubkarre': ['Hilfsmittel','hat Wanne und Rad','zum Transport von Baumaterialien','wird von einem Arbeiter geschoben'],
  'Installateur': ['Beruf','erfordert eine Ausbildung','kümmert sich un technische Anlagen','zuständig für Sanitäts-, Heizungs- und Klimatechnik'],
  'Schutzbrille': ['Schutzausrüstung','aus weichem oder hartem Kunststoff','Schutz vor Staub und Splittern','schützt die Augen'],
  'Wasserwaage': ['Messgerät','aus Holz, Aluminium oder Kunststoff','längliche Form','Prüfgerät zur Ausrichtung mittels Flüssigkeit'],
  'Bohrmaschine': ['Werkzeug','elektrisch betrieben','wechselbare Aufsätze','wird verwendet, um Löcher zu erstellen'],
  'Bauzeichnung': ['Hilfsmittel','grafische Darstellung','zeigt räumliche Ausmaße','enthält wichtige Informationen für die Bauausführung'],
  'Stichsäge': ['Werkzeug','aus Holz und Metall','handgeführt oder elektronisch','zum Schneiden von Ausschnitten oder Erweitern von Öffnungen'],
  'Gerüstbauer': ['Beruf','erfordert eine Ausbildung','arbeitet häufig in der Höhe','errichtet Flächen für die Arbeit an der Außenwand'],
  'Gehörschutz': ['Schutzausrüstung','aus Kunststoff','gibt es als Kapseln oder Stöpsel','schützt vor lauten Geräuschen'],
  'Abdeckfolie': ['Material','aus Kunststoff','wird großflächig ausgelegt','schützt vor Verschmutzung']
};

final Map hobbysMAP = {
  'Musik': ['drinnen und draußen','Intrumente und Gesang','kann man hören und selber machen','HipHop, Schlager, Klassik'],
  'Theater': ['häufig drinnen','Kunst und Kultur','in Sälen oder Hallen','Faust, Macbeth, Ein Sommernachtstraum'],
  'Garten': ['draußen','im Grünen','Unkraut jäten','hinterm Haus'],
  'Schreiben': ['eher drinnen','im Deutschunterricht','Wörter und Sätze','Gedichte, Artikel, Bücher'],
  'Reisen': ['draußen','Urlaub und Ferien','per Flugzeug, Auto, Zug','Spanien, Amerika, Neuseeland'],
  'Museum': ['häufig drinnen','Kunst und Kultur','Gemälde und Skulpturen','Städel, Louvre, MoMa'],
  'Tanz': ['häufig drinnen','körperliche Aktivität','mit Musik verbunden','Salsa, Zumba, Walzer '],
  'Sport': ['drinnen und draußen','körperliche Aktivität','mit Geräten oder ohne','Joggen, Fußball, Aerobic'],
  'Gesang': ['drinnen','stimmliche Aktivität','mit Instrumenten oder ohne','im Chor oder alleine'],
  'Fernsehen': ['drinnen','im Wohnzimmer','Zeichentrick, Action oder Drama','ARD, ZDF und RTL'],
  'Computer': ['drinnen','im Büro','Internet und Textverarbeitung','E-Mail, Word, Excel'],
  'Lesen': ['drinnen und draußen','Bildung','Bücher und Zeitung','Die Säulen der Erde, Der Spiegel'],
  'Kino': ['drinnen','im Saal','große Leinwand','Titanic, Harry Potter, Der Herr der Ringe'],
  'Spielen': ['drinnen und draußen','gesellige Aktivität','mit Karten oder Figuren','UNO, Skat, Schach'],
  'Schwimmen': ['drinnen und draußen','körperliche Aktivität','mit Badeanzug oder Badehose','in Freibad oder Meer'],
  'Einkaufen': ['drinnen','Selbstversorgung','Obst, Gemüse, Kleidung','bei REWE, Edeka, Kaufhof'],
  'Nähen': ['drinnen','Handarbeit','mit Nadel und Faden','Tischdecken, Kleider, Anzüge'],
  'Wintersport': ['häufig draußen','körperliche Aktivität','im Winter','Ski, Snowboard, Schlitten'],
  'Disco': ['drinnen','Nachtleben','Bewegung zu lauter Musik','im Club'],
  'Basteln': ['drinnen','Handarbeit','mit Schere, Papier und Kleber','Geburtstagskarten, Weihnachtsschmuck'],
  'Kreuzworträtsel': ['drinnen und draußen','Denksport','mit Stift auf Papier','Wörter raten in Zeitungen'],
  'Häkeln': ['drinnen','Handarbeit','Maschen aus Wolle','Mützen, Topflappen und Schal'],
  'Camping': ['draußen','Urlaub und Ferien','Übernachtungsmöglichkeit','Wohnwagen, Zelt, Wohnmobil'],
  'Jodeln': ['drinnen und draußen','stimmliche Aktivität','ohne Instrumente','Singen mit Silben und ohne Text'],
  'Töpfern': ['drinnen','Handarbeit','Keramikherstellung','Vasen, Schalen, Krüge'],
  'Kampfsport': ['eher drinnen','körperliche Aktivität','Zweikampf','Judo, Karate und Boxen'],
  'Fitness': ['drinnen und draußen','Ausdauer und Kraft','Sportstudio','Laufband, Crosstrainer und Joggen'],
  'Modelleisenbahn': ['drinnen','Modellbau','Gleise, Landschaft und Züge','Märklin, Buco'],
  'Aerobic': ['eher drinnen','körperliche Aktivität','mit Musik, Fitnesstraining in der Gruppe','klassische Gymnasik mit Tanz'],
  'Heimwerken': ['eher drinnen','Haus und Garten','mit Maschinen und Werkzeug','Gartenhütte, Hausbau']
};

final Map kleidungMAP = {
  'Hut': ['wird von Männern und Frauen getragen','wird auf dem Kopf getragen','hat eine umlaufende Krempe','wird häufig auf Pferderennen getragen'],
  'Rock': ['wird meist von Frauen getragen','wird am Unterkörper getragen','umschließt beide Beine gleichzeitig','wird in Schottland auch von Männern getragen'],
  'Kleid': ['wird meist von Frauen getragen','wird am ganzen Körper getragen','ist einteilig und lang','wird im Sommer und zu Festen getragen'],
  'Tuch': ['wird meist von Frauen getragen','wird um den Hals getragen','ist häufig aus leichtem Stoff','wird wie ein Schal getragen'],
  'Hemd': ['wird meist von Männern getragen','wird am Oberkörper getragen','hat kurze oder lange Ärmel','wird häufig unter einem Anzug getragen'],
  'Anzug': ['wird meist von Männern getragen','wird am ganzen Körper getragen','besteht aus Ober- und Unterteil','wird häufig über einem Hemd getragen'],
  'Mütze': ['wird von Männern und Frauen getragen','wird auf dem Kopf getragen','ist häufig aus Wolle','wird meist im Winter getragen'],
  'Stiefel': ['wird von Männern und Frauen getragen','wird an den Füßen getragen','hat einen hohen Schaft','wird im Winter oder zum Reiten getragen'],
  'Hose': ['wird von Männern und Frauen getragen','wird am Unterkörper getragen','hat zwei Beine','hat Knopf, Reißverschluss und Taschen'],
  'Jacke': ['wird von Männern und Frauen getragen','wird am Oberkörper getragen','hat zwei lange Ärmel','hält den Oberkörper warm'],
  'Gürtel': ['wird von Männern und Frauen getragen','wird in der Körpermitte getragen','ist meist aus Leder','hat eine Schnalle und hält die Hose fest'],
  'Schuh': ['wird von Männern und Frauen getragen','wird an den Füßen getragen','man benötigt zwei davon','hat Schnürsenkel'],
  'Bluse': ['wird meist von Frauen getragen','wird am Oberkörper getragen','ist häufig aus Seide oder Baumwolle','ist hemdartig mit Kragen und Knöpfen'],
  'Weste': ['wird von Männern und Frauen getragen','wird am Oberkörper getragen','hat keine Ärmel','ist wie eine Jacke ohne Ärmel'],
  'Handschuhe': ['wird von Männern und Frauen getragen','wird am Oberkörper getragen','ist meist aus Leder oder Wolle','wird an den Händen getragen'],
  'Unterhemd': ['wird von Männern und Frauen getragen','wird am Oberkörper getragen','hat keine Ärmel','gehört zur Unterwäsche'],
  'Dirndl': ['wird meist von Frauen getragen','wird am ganzen Körper getragen','ist ein spezielles Kleid','ist eine Tracht aus Bayern'],
  'BH': ['wird meist von Frauen getragen','wird am Oberkörper getragen','hat zwei Körbchen','stützt und formt die Brust'],
  'Gummistiefel': ['wird von Männern und Frauen getragen','wird an den Füßen getragen','ist aus Kunststoff','wird bei Regen getragen'],
  'Anorak': ['wird von Männern und Frauen getragen','wird am Oberkörper getragen','hat zwei lange Ärmel und ist wetterfest','ist eine Jacke mit Kapuze'],
  'Blazer': ['wird von Männern und Frauen getragen','wird am Oberkörper getragen','hat zwei lange Ärmel und einen Kragen','wird häufig über einer Bluse getragen'],
  'Strumpfhose': ['wird meist von Frauen getragen','wird am Unterkörper getragen','ist eng anliegend und unten geschlossen','ist eine Verbindung aus Unterhose und Strümpfen'],
  'Hausschuh': ['wird von Männern und Frauen getragen','wird an den Füßen getragen','ist bequem und hat meist keinen Absatz','wird meist im Haus getragen'],
  'Latzhose': ['wird von Männern und Frauen getragen','wird am ganzen Körper getragen','ist meist eine Arbeitskleidung','wird am Oberkörper mit Hosenträgern gehalten'],
  'Poncho': ['wird von Männern und Frauen getragen','wird am Oberkörper getragen','ist ein rechteckig und hat ein Loch in der Mitte','ist ein Umhang der Indios'],
  'Korsage': ['wird meist von Frauen getragen','wird am Oberkörper getragen','ist eng anliegend','wird geschnürt und macht schlank'],
  'Turnschuh': ['wird von Männern und Frauen getragen','wird an den Füßen getragen','ist bequem und wird geschnürt','wird beim Sport oder in der Freizeit getragen'],
  'Leggings': ['wird meist von Frauen getragen','wird am Unterkörper getragen','ist eng anliegend und unten offen','ist eine Hose'],
  'Jogginghose': ['wird von Männern und Frauen getragen','wird am Unterkörper getragen','ist bequem und am Bund elastisch','wird beim Laufen oder in der Freizeit getragen'],
  'Pullunder': ['wird von Männern und Frauen getragen','wird am Oberkörper getragen','hat keine Ärmel','ist ein ärmelloser Pullover']
};

final Map koerperteileMAP = {
  'Hand': ['von außen sichtbar','gehört zum Arm','es gibt zwei davon','hat fünf Finger'],
  'Auge': ['von außen sichtbar','ein Sinnesorgan','es gibt zwei davon','man kann damit sehen'],
  'Kopf': ['von außen sichtbar','sitzt auf dem Hals','ist "rund"','Haare wachsen darauf'],
  'Herz': ['von außen nicht sichtbar','sitzt im Oberkörper','es schlägt','Zeichen der Liebe'],
  'Mund': ['von außen sichtbar','sitzt im Gesicht','ein Teil davon sind die Lippen','bewegt sich beim Essen oder Sprechen'],
  'Arm': ['von außen sichtbar','obere Extremität','es gibt zwei davon','am einen Ende sitzt die Hand'],
  'Rücken': ['von außen sichtbar','gegenüber vom Bauch','Wirbelsäule und Rippen','Bandscheibenvorfall und Hexenschuss'],
  'Brust': ['von außen sichtbar','über dem Bauch','es gibt zwei davon','Frauen brauchen sie zum Stillen von Babys'],
  'Haut': ['von außen sichtbar','das größte Sinnesorgan','bedeckt unseren ganzen Körper','wird durch Sonnenbaden dunkler'],
  'Fuß': ['von außen sichtbar','man läuft damit','es gibt zwei davon','hat fünf Zehen'],
  'Finger': ['von außen sichtbar','man greift damit','es gibt an jeder Hand fünf','man trägt Ringe daran'],
  'Nase': ['von außen sichtbar','ist im Gesicht','hat zwei Flügel','man atmet und riecht damit'],
  'Stirn': ['von außen sichtbar','ist im Gesicht','unter dem Haaransatz','man kann sie "runzeln"'],
  'Hals': ['von außen sichtbar','verbindet Rumpf und Kopf','ermöglicht die Bewegung des Kopfes','darin sind Kehlkopf, Luft- und Speiseröhre'],
  'Ohr': ['von außen nicht sichtbar','sitzen rechts und links am Kopf','es gibt zwei davon','man kann damit hören'],
  'Ellenbogen': ['von außen sichtbar','gehört zum Arm','Verbindung zwischen Ober- und Unterarm','man kann sich darauf abstützen'],
  'Wirbelsäule': ['von außen nicht sichtbar','gehört zum Rücken','besteht aus knöchernen Elementen','Bandscheiben verbinden die Wirbel miteinander'],
  'Handgelenk': ['von außen sichtbar','gehört zur Hand','Verbindung zwischen Hand und Arm','man trägt Uhren daran'],
  'Wimper': ['von außen sichtbar','sitzen an den Augenlidern','schützen vor Schmutz und Dreck','Frauen schminken sie sich mit Tusche'],
  'Lippe': ['von außen sichtbar','gehört zum Mund','weich, wulstig, beweglich, rötlich','man kann damit küssen'],
  'Gesäß': ['von außen sichtbar','sitzt unter dem Rücken','besteht aus zwei "Backen"','man sitzt darauf'],
  'Knöchel': ['von außen sichtbar','ist ein Knochen','Verbindung zwischen Fuß und Bein','gehört zum Fußgelenk'],
  'Niere': ['von außen nicht sichtbar','ist ein Organ','es gibt zwei davon','sieht aus wie eine Bohne'],
  'Wade': ['von außen sichtbar','gehört zum Unterschenkel','hinterer Teil des Unterschenkels','dort entstehen oft Krämpfe'],
  'Fingernagel': ['von außen sichtbar','gehört zu den Fingern','wächst, kann man feilen und lackieren','schützt die Fingerkuppen'],
  'Schlüsselbein': ['von außen sichtbar','gehört zum Schultergürtel','es gibt zwei davon','ist "S-förmig"'],
  'Lid': ['von außen sichtbar','gehört zum Auge','es gibt zwei davon','man kann damit blinzeln'],
  'Augenbraue': ['von außen sichtbar','sitzten über dem Auge','es gibt zwei davon','behaarter Halbbogen über den Lidern'],
  'Gebiss': ['von außen teilweise sichtbar','ist im Mund','besteht aus Kiefer und Zähnen','man kann damit essen'],
  'Fußnagel': ['von außen sichtbar','ist an der Spitze der Zehen','wächst, kann man feilen und lackieren','es gibt an jedem Fuß fünf']
};

final Map kuecheMAP = {
  'Glas': ['Geschirr','zum Trinken','durchsichtig','für Kaltgetränke'],
  'Messer': ['Besteck','zum Essen','mit scharfer Kante','zum Schneiden'],
  'Teller': ['Geschirr','zum Essen','meist rund','zum Servieren von Essen'],
  'Tasse': ['Geschirr','zum Trinken','meist mit Henkel','zum Trinken von Heißgetränken'],
  'Gabel': ['Besteck','zum Essen','mit Zacken','zum Aufspießen von Nahrung'],
  'Löffel': ['Besteck','zum Essen','mit ovalem Ende','zum Essen von flüssiger Nahrung'],
  'Herd': ['Elektrogerät','zum Kochen','groß und eckig','zum Erhitzen von Töpfen und Pfannen'],
  'Topf': ['Kochgefäß','zum Zubereiten von Essen','meist zylinderförmig','zum Kochen von Speisen'],
  'Schüssel': ['Geschirr','zum Essen','tiefer als ein Teller','meist zum Servieren von Salat'],
  'Pfanne': ['Kochgefäß','zum Zubereiten von Essen','flach mit langem Stiel','zum Braten von Speisen'],
  'Kühlschrank': ['Elektrogerät','zur Aufbewahrung','groß und eckig','zum kalten Frischhalten von Lebensmitteln'],
  'Sieb': ['Kochutensilie','zum Trennen','mit Löchern','zum Abtropfen von Nudeln'],
  'Schwamm': ['Putzutensilie','zum Reinigen','weich und saugfähig','zum Abwischen'],
  'Backofen': ['Elektrogerät','zum Zubereiten von Essen','groß und eckig','zum Erhitzen mit Luft'],
  'Wasserhahn': ['Armatur','zum Reinigen','aus gebogenem Metall','zum Regulieren des Wassers'],
  'Arbeitsplatte': ['Ablage','zur Vorbereitung','große Fläche','zum Abstellen von Küchenutensilien'],
  'Toaster': ['Elektroger','zum Zubereiten von Essen','klein und eckig','zum Rösten von Brot'],
  'Spülmittel': ['Putzutensilie','zum Reinigen','flüssig und farbig','zum Säubern von Geschirr'],
  'Tauchsieder': ['Elektrogerät','zum Erhitzen','mit einer Spirale','zum Erhitzen von Wasser'],
  'Mikrowelle': ['Elektrogerät','zum Zubereiten von Essen','mittelgroß und eckig','zum Aufwärmen von Speisen'],
  'Spülmaschine': ['Elektrogerät','zum Reinigen','mit Griff und Leiste','zum Reinigen von Geschirr'],
  'Flaschenöffner': ['Hilfswerkzeug','zum Entfernen von Verschlüssen','klein und meist oval','zum Entfernen von Kronkorken'],
  'Eieruhr': ['Hilfswerkzeug','zum Kochen oder Backen','zylinderförmig','als Wecker zum Kochen'],
  'Küchenrolle': ['Putzutensilie','zum Reinigen','rechteckig und leicht','zum Aufwischen'],
  'Küchenhandtuch': ['Hilfswerkzeug','zum Reinigen','rechteckig und leicht','zum Abtrocknen'],
  'Gefrierfach': ['Elektrogerät','zur Aufbewahrung','groß und eckig','zum eiskalten Lagern von Lebensmitteln'],
  'Dosenöffner': ['Hilfswerkzeug','zum Entfernen von Verschlüssen','mit scharfem rundem Messer','zum Entfernen von Konservendeckeln'],
  'Schneidebrett': ['Kochutensilie','zur Vorbereitung','aus Holz oder Plastik','zum Zerkleinern von Lebensmitteln'],
  'Messerblock': ['Aufbewahrnungsgerät','zur Aufbewahrung','aus Holz und eckig','zur Aufbewahrung von Messern'],
  'Dunstabzugshaube': ['Elektrogerät','zum Kochen','aus Edelstahl mit Filter','zum Absaugen von Kochdunst']
};

final Map laenderMAP = {
  'Deutschland': ['Mitteleuropa','grenzt an die Frankreich','in der Hauptstadt steht das Brandenburger Tor','Hauptstadt: Berlin'],
  'Frankreich': ['Westeuropa','grenzt an die Schweiz','in der Hauptstadt steht der Eiffelturm','Hauptstadt: Paris'],
  'USA': ['Nordamerika','grenzt an Kanada','hier liegt der Grand Canyon','Hauptstadt: Washington'],
  'England': ['Nordwesteuropa','grenzt an Schottland','durch die Hauptstadt fließt die Themse','Hauptstadt: London'],
  'Italien': ['Südeuropa','grenzt an die Schweiz','das Land sieht aus wie ein Stiefel','Hauptstadt: Rom'],
  'Polen': ['Osteuropa','grenzt an Deutschland','die ehemalige Hauptstadt war Krakau','Hauptstadt: Warschau'],
  'Österreich': ['Mitteleuropa','grenzt an die Schweiz','durch die Hauptstadt fließt die Donau','Hauptstadt: Wien'],
  'China': ['Ostasien','grenzt an Russland','dort steht die längste Mauer der Welt','Hauptstadt: Peking'],
  'Japan': ['Ostasien','östlich von Korea','die Flagge ist weiß mit rotem Punkt','Hauptstadt: Tokio'],
  'Schweiz': ['Mitteleuropa','grenzt an Deutschland','hier steht das Matterhorn','Hauptstadt: Bern'],
  'Schweden': ['Nordeuropa','grenzt an Norwegen','hier entstand IKEA ','Hauptstadt: Stockholm '],
  'Türkei': ['Vorderasien','grenzt an Syrien','hier befindet sich die sehenswerte Stadt Istanbul ','Hauptstadt: Ankara'],
  'Griechenland': ['Südeuropa','grenzt an Bulgarien','hier isst man gerne Gyros und Zaziki','Hauptstadt: Athen'],
  'Dänemark': ['Nordeuropa','grenzt an Deutschland','hat eine parlamentarische Monarchie','Hauptstadt: Kopenhagen'],
  'Niederlande': ['Westeuropa','grenzt an Belgien','ist für seinen Käse bekannt','Hauptstadt: Amsterdam'],
  'Island': ['Nordeuropa','südlich des nördlichen Polarkreises','größte Vulkaninsel der Erde','Hauptstadt: Reykjavík'],
  'Tunesien': ['Nordafrika','grenzt an Algerien','das nördlichste Land Afrikas','Hauptstadt: Tunis'],
  'Malta': ['Südeuropa','liegt im Mittelmeer','kleinster Mitgliedsstaat der EU','Hauptstadt: Valletta'],
  'Peru': ['Südamerika','grenzt an Brasilien','das Land der Lamas','Hauptstadt: Lima'],
  'Bolivien': ['zwischen Zentral-, Nord- und Ostasien','grenzt an Argentinen','grenzt an den Titicaca-See','Hauptstadt: Sucre'],
  'Mongolei': ['Südwestafrika','grenzt an China','bekannt für nomadische Viehwirtschaft','Hauptstadt: Ulaanbaatar'],
  'Namibia': ['Südosteuropa','grenzt an Südafrika','hier liegt der Etosha-Nationalpark','Hauptstadt: Windhoek'],
  'Kroatien': ['Ostafrika','grenzt an Ungarn','wird Land der tausend Inseln genannt','Hauptstadt: Zagreb'],
  'Kenia': ['Südamerika','grenzt an Uganda','hier liegt der Nairobi Nationalpark','Hauptstadt: Nairobi'],
  'Ecuador': ['Südasien','grenzt an Kolombien','hier steht der aktive Vulkan Cotopaxi','Hauptstadt: Quito'],
  'Nepal': ['Südasien','grenzt an China','hier liegt ein großer Teil des Himalaya','Hauptstadt: Kathmandu'],
  'Haiti': ['Karibik','grenzt an die Dominikanische Republik','wurde von Kolumbus entdeckt','Hauptstadt: Port-au-Prince'],
  'Russland': ['Osteuropa und Asien','grenzt an China','das flächengrößte Land der Erde','Hauptstadt: Moskau'],
  'Jamaika': ['Karibik','liegt in der Karibik','hierher kommt der Reggae','Hauptstadt: Kingston'],
  'Tansania': ['Ostafrika','grenzt an Kenia','hier steht der Kilimandscharo','Hauptstadt: Dodoma']
};


final Map moebelMAP = {
  'Tisch': ['hat meist vier Beine','im Esszimmer oder in der Küche','man kann daran sitzen','man stellt darauf etwas ab'],
  'Bett': ['hat meist vier Beine','im Schlafzimmer','man liegt darin','man schläft darin'],
  'Spiegel': ['hängt an der Wand','im Bad oder Flur','silberne Oberfläche','zeigt das eigene Bild'],
  'Stuhl': ['hat meist vier Beine','im Esszimmer oder in der Küche','man sitzt darauf','hat eine gerade Rückenlehne'],
  'Schreibtisch': ['hat meist vier Beine','im Arbeitszimmer','man erledigt darauf Büroarbeiten','meist steht ein Computer darauf'],
  'Sessel': ['hat meist vier Beine','im Wohnzimmer','man sitzt darin','bequemes Sitzmöbelstück'],
  'Lampe': ['steht oder hängt','in allen Zimmern','wird an- oder ausgeschaltet','beleuchtet den Raum'],
  'Schrank': ['steht auf dem Boden','im Wohnzimmer oder Schlafzimmer','man bewahrt etwas darin auf','Regal mit Türen'],
  'Sofa': ['zum Sitzen oder Liegen','im Wohnzimmer','hat mehr als einen Sitzplatz','bequemes Sitzmöbelstück'],
  'Garderobe': ['steht frei oder ist an der Wand befestigt','im Flur oder Eingangsbereich','man hängt Kleidung daran auf','hat Haken und oder eine Stange'],
  'Schemel': ['hat drei oder vier Beine','in allen Zimmern','hat keine Arm- und Rückenlehne','andere Bezeichnung für Hocker'],
  'Regal': ['steht frei oder ist an der Wand befestigt','im Wohnzimmer oder Arbeitszimmer','offenes Möbelstück','meist stehen Bücher darin'],
  'Kommode': ['hat meist vier Beine','in allen Zimmern','dient zur Aufbewahrung von Dingen','hat mehrere Schubladen oder Türen'],
  'Truhe': ['hat meist vier Beine','in allen Zimmern','dient zur Aufbewahrung von Dingen','kastenförmig und hat einen klappbaren Deckel'],
  'Nachttisch': ['hat meist vier Beine','im Schlafzimmer','dient zur Ablage','steht direkt neben dem Bett'],
  'Stehlampe': ['steht frei','im Wohnzimmer','wird an- oder ausgeschaltet','beleuchtet den Raum'],
  'Standuhr': ['steht frei oder hängt an der Wand','im Esszimmer oder Wohnzimmer','läutet zur vollen Stunde','zeigt die Zeit an'],
  'Sitzbank': ['hat meist vier Beine','im Esszimmer oder Wohnzimmer','hat mehr als einen Sitzplatz','für mehrere Personen geeignet'],
  'Barhocker': ['hat meist vier Beine','im Esszimmer oder in der Küche','man sitzt darauf','steht meist an einer Theke'],
  'Servierwagen': ['hat Rollen','im Esszimmer oder in der Küche','man kann Dinge darauf stellen','zum Transportieren von Geschirr und Speisen'],
  'Schirmständer': ['steht auf dem Boden','im Flur oder Eingangsbereich','dient zur Aufbewahrung von Dingen','dient zur Aufbewahrung von Regenschirmen'],
  'Raumteiler': ['steht frei im Raum','in allen Zimmern','ähnelt einer Trennwand','trennt ein Zimmer in zwei Bereiche'],
  'Hollywoodschaukel': ['zum Sitzen oder Liegen','steht draußen','hat mehr als ein Sitzplatz','bewegt sich vor und zurück'],
  'Handtuchhalter': ['steht frei oder ist an der Wand befestigt','im Badezimmer','dient zur Ablage','darauf trocknen Handtücher'],
  'Zeitungsständer': ['steht frei oder ist an der Wand befestigt','im Wohnzimmer','dient zur Ablage','dient zur Ablage von Zeitschriften'],
  'Wickelkommode': ['hat meist vier Beine','im Kinderzimmer','hat oben eine Fläche zum Liegen','Babys werden darauf an- und ausgezogen'],
  'Sideboard': ['hat meist vier Beine','in allen Zimmern','dient zur Aufbewahrung von Dingen','Bezeichnung stammt aus dem Englischen'],
  'Schuhschrank': ['steht oder hängt an der Wand','im Flur oder Eingangsbereich','dient zur Aufbewahrung von Dingen','dient zur Lagerung von Sandalen, Stiefeln, etc.'],
  'Stockbett': ['hat meist vier Beine','im Kinderzimmer oder Schlafzimmer','mehrere Personen liegen darin','zwei Schlafstätten übereinander'],
  'Sitzsack': ['liegt auf dem Boden','im Wohnzimmer oder Kinderzimmer','man sitzt darauf','bequemes Sitzmöbelstück ohne Beine']
};

final Map musikinstrumenteMAP = {
  'Klavier': ['Tasteninstrument','überwiegend aus Holz','hat schwarze und weiße Tasten','eine Art ist der Flügel'],
  'Orgel': ['Tasteninstrument','aus Holz und Metall','hat verschieden große Pfeifen','wird in der Kirche gespielt'],
  'Trommel': ['Schlaginstrument','überwiegend aus Holz','hat eine Membran','wird mit Schlägeln oder Händen gespielt'],
  'Becken': ['Schlaginstrument','aus Metall','tellerförmige Scheiben','werden gegeneinander geschlagen'],
  'Geige': ['Streichinstrument','aus Holz','wird mit dem Bogen gestrichen','heißt auch Violine'],
  'Bass': ['Zupf- und Streichinstrument','aus Holz','wird gezupft oder gestrichen','spielt tiefe Frequenzen'],
  'Trompete': ['Blasinstrument','aus Metall','ist goldgelb und zylinderförmig','stark vertreten im Jazz'],
  'Schlagzeug': ['Schlaginstrument','aus Holz und Metall','kann sehr laut sein','Kombination mehrerer Schlaginstrumente'],
  'Gitarre': ['Zupfinstrument','aus Holz','kann mit Plektrum gespielt werden','gern am Lagerfeuer gespielt'],
  'Harfe': ['Zupfinstrument','überwiegend aus Holz','größtes und schwerstes Orchesterinstrument','Logo der irischen Biermarke Guinness'],
  'Mundharmonika': ['Blasinstrument','aus Metall','klein und kastenförmig','berühmt ist "Der Junge mit der…"'],
  'Pauke': ['Schlaginstrument','überwiegend aus Holz','wird häufig paarweise verwendet','sprichwörtlich fällt man mit ... und Trompeten durch'],
  'Posaune': ['Blasinstrument','aus Metall','Trompeteninstrument','hat u-förmigen Außenzug'],
  'Klarinette': ['Blasinstrument','überwiegend aus Holz','meist schwarz','Tonlöcher mit silbernen Kappen verschlossen'],
  'Cello': ['Streichinstrument','aus Holz','wird mit Bogen gestrichen','wird zwischen den Knien gehalten'],
  'Saxophon': ['Blasinstrument','aus Metall','Rohr weitet sich zum Ende','stark vertreten im Jazz'],
  'Akkordeon': ['Handzuginstrument','überwiegend aus Holz','hat links eine Tastatur','wird auch "Quetschkomode" genannt'],
  'Tuba': ['Blasinstrument','aus Metall','tiefstes Blechblasinstrument','nach oben gerichteter Schalltrichter'],
  'Triangel': ['Schlaginstrument','aus Stahl','wird mit Stahlstab geschlagen','gleichseitiges Dreieck'],
  'Bratsche': ['Streichinstrument','aus Holz','wird mit Bogen gestrichen','etwas größer als die Geige'],
  'Dudelsack': ['Blasinstrument','überwiegend aus Holz','hat einen Beutel aus Leder oder Kunststoff','wird meist in Schottland gespielt'],
  'Xylophon': ['Schlaginstrument','aus Holz','aneinander gereihte Klangstäbe','wird oft im Kindergarten gespielt'],
  'Waldhorn': ['Blasinstrument','aus Metall','hat kreisförmig gewundenes Rohr','wird zur Jagd geblasen'],
  'Blockflöte': ['Blasinstrument','aus Holz','schmal, lang, mit Löchern','spielen viele Grundschüler'],
  'Tamburin': ['Schlaginstrument','aus Holz und Metall','Rahmentrommel mit Schellen','wird in einer Hand gehalten, mit der anderen geschlagen'],
  'Drehleier': ['Streichinstrument','überwiegend aus Holz','Seiten von innerem Rad gestrichen','Spieler dreht an Kurbel'],
  'Querflöte': ['Blasinstrument','aus Metall','schmal, lang, mit Klappen','wird seitlich gehalten'],
  'Balalaika': ['Zupfinstrument','aus Holz','hat dreieckigen Resonanzkörper','oft in russischer Volksmusik verwendet'],
  'Ukulele': ['Zupfinstrument','aus Holz','exotischer Klang','sehr kleine Gitarre mit 4 Saiten'],
  'Kontrabass': ['Streichinstrument','aus Holz','wird mit Bogen gestrichen','wird im Lied von den drei Chinesen gespielt']
};

final Map obstMAP = {
  'Apfel': ['wächst an einem Baum','grün, rot oder gelb','Kernobst','Braeburn oder Boskoop'],
  'Zitrone': ['wächst an einem Baum','gelb','Zitrusfrucht','wird oft ausgepresst und schmeckt sauer'],
  'Orange': ['wächst an einem Baum','orange','Zitrusfrucht','wird ausgepresst und hat viel Vitamin C'],
  'Birne': ['wächst an einem Baum','gelb oder grün','Kernobst','Abate Fetel oder Williams Christ'],
  'Ananas': ['wächst auf dem Feld','außen braun und innen gelb','exotische Frucht','dicke Schale mit besonderer Struktur'],
  'Traube': ['wächst an einer Rebe','grün oder rot','Fruchtstand mit Beeren','aus den Beeren wird Wein gemacht'],
  'Banane': ['wächst an einer Staude','gelb','exotische Frucht','längliche, gebogene Form'],
  'Kirsche': ['wächst an einem Baum','rot','Steinobst','in Mon Chéri enthalten'],
  'Pfirsich': ['wächst an einem Baum','orange','Steinobst','frisch oder gezuckert aus der Dose'],
  'Melone': ['wächst auf dem Feld','oft außen grün und innen rot','exotische Frucht','wird mit Parmaschinken als Vorspeise gereicht'],
  'Feige': ['wächst an einem Baum','außen lila und innen rötlich','exotische Frucht','wird oft zu Käse gegessen'],
  'Mandarine': ['wächst an einem Baum','orange','Zitrusfrucht','gibt es häufig in der Weihnachtszeit'],
  'Erdbeere': ['wächst auf dem Feld','rot','Beerenobst','wird oft zu Marmelade gemacht'],
  'Quitte': ['wächst an einem Baum','gelb','Kernobst','sieht aus wie eine Mischung aus Apfel und Birne'],
  'Aprikose': ['wächst an einem Baum','gelb oder orange','Steinobst','wird auch Marille genannt'],
  'Grapefruit': ['wächst an einem Baum','außen orange und innen rosa','Zitrusfrucht','hat einen bitteren Geschmack'],
  'Kiwi': ['wächst an einer Rebe','außen braun und innen grün','exotische Frucht','hat eine stachelig-haarige Schale'],
  'Granatapfel': ['wächst an einem Baum','rot','exotische Frucht','enthält viele rubinrote Samen'],
  'Heidelbeere': ['wächst an einem Strauch','blau','Beerenobst','färbt Mund und Zähne blau'],
  'Stachelbeere': ['wächst an einem Strauch','grün oder rot','Beerenobst','der Strauch hat stachelige Äste'],
  'Johannisbeere': ['wächst an einem Strauch','schwarz oder rot','Beerenobst','kleine säuerlich schmeckende kugelförmige Früchte'],
  'Zwetschge': ['wächst an einem Baum','lila','Steinobst','wird auch Pflaume genannt'],
  'Mango': ['wächst an einem Baum','innen gelb','exotische Frucht','hat oft faseriges Fruchtfleisch'],
  'Physalis': ['wächst an einem Strauch','orange mit hellbrauner Hülle','heißt auch Blasenkirsche','wird zum Verzieren von Kuchen oder Cocktails benutzt'],
  'Preiselbeere': ['wächst an einem Strauch','rot','Beerenobst','wird oft zu Wildgerichten gegessen'],
  'Mirabelle': ['wächst an einem Baum','gelb','Steinobst','wird oft zu Likör und Marmelade verarbeitet'],
  'Papaya': ['wächst an einem Baum','außen grün und innen orange','exotische Frucht','schmeckt sehr süß'],
  'Litschi': ['wächst an einem Baum','außen rosa-braun und innen weiß','Kernobst','wird oft in thailändischen Gerichten verwendet'],
  'Kokusnuss': ['wächst an einem Baum','außen braun und innen weiß','Steinobst','die darin enthaltene Milch kann man trinken'],
  'Maracuja': ['wächst an einem Baum','außen lila und innen orange','exotische Frucht','wird auch Passionsfrucht genannt']
};


final Map pflanzenMAP = {
  'Buche': ['Nutzpflanze','sommergrün','Baum','hat dreikantige Früchte und fein gezähnte Blätter'],
  'Rose': ['Zierpflanze','sommergrün','krautige Pflanze','meist rot und symbolisiert die Liebe'],
  'Klee': ['Nutzpflanze','sommergrün','krautige Pflanze','vierblättriges Exemplar symbolisiert Glück'],
  'Kiefer': ['Nutzpflanze','immergrün','Baum','hat Nadeln und duftet aromatisch'],
  'Petersilie': ['Zierpflanze','immergrün','Baum','bildet kräftige und stark verzweigte Wurzeln'],
  'Linde': ['Nutzpflanze','sommergrün','Baum','hat Blätter und duftet süßlich'],
  'Eiche': ['Nutzpflanze','sommergrün','Baum','hat Blätter und trägt eine Nussfrucht'],
  'Veilchen': ['Zierpflanze','sommergrün','krautige Pflanze','blüht meist violett und wird als Duft in Parfüm verwendet'],
  'Palme': ['Nutzpflanze','immergrün','Baum','wächst in südlichen Ländern und trägt zum Teil Kokusnüsse'],
  'Lorbeer': ['Nutzpflanze','immergrün','Baum','aromatische Blätter werden als Gewürz verwendet'],
  'Flieder': ['meZierpflanze','sommergrün','Baum','hat lilafarbene und stark duftende Blüten'],
  'Birke': ['meZierpflanze','sommergrün','Baum','hat Blätter und meist eine weiße Rinde'],
  'Efeu': ['meZierpflanze','immergrün','krautige Pflanze','giftige Kletterpflanze'],
  'Hanf': ['meZierpflanze','sommergrün','krautige Pflanze','liefert Fasern für Seile und ein Rauschmittel'],
  'Tanne': ['Nutzpflanze','sommergrün','Baum','wird meist als Weihnachtsbaum genutzt'],
  'Eberesche': ['Nutzpflanze','sommergrün','hat gefiederte Blätter','wird auch als Vogelbeere bezeichnet'],
  'Hortensie': ['Zierpflanze','sommergrün','hat große Blüten','Blüten haben farbige oder weiße Kelchblättern'],
  'Zypresse': ['Zierpflanze','immergrün','hat Nadeln','prägt die Kulturlandschaft in der Toskana'],
  'Koriander': ['Nutzpflanze','sommergrün','hat Blätter und kugelförmige Samen','wird als Gewürz oder Heilmittel verwendet'],
  'Hyazinthe': ['Zierpflanze','sommergrün','hat eine Blütentraube aus vielen Einzelblüten','duftet süß'],
  'Geranie': ['Zierpflanze','sommergrün','wächst aufrecht oder hängend','wird meist als Balkonpflanze genutzt'],
  'Schlehe': ['Nutzpflanze','sommergrün','hat bitter schmeckende Früchte','hat weiße Blüten'],
  'Mammutbaum': ['Nutzpflanze','immergrün','hat Nadeln','wird sehr alt und gehört zu den größten Bäumen der Erde'],
  'Oregano': ['Nutzpflanze','sommergrün','hat gegenständig angeordnete Blätter','wird in der mediterranen Küche als Gewürz benutzt'],
  'Ringelblume': ['Nutzpflanze','immergrün','blüht gelb oder orange','wird auch Löwenzahn genannt'],
  'Vergissmeinnicht': ['Zierpflanze','sommergrün','hat blaue bis violettfarbene Blüten','gilt als Symbol der Erinnerung'],
  'Löwenmäulchen': ['Zierpflanze','sommergrün','blüht meist gelb, rot oder violett','Blüten sind weit aufgesperrt'],
  'Brennnessel': ['Nutzpflanze','sommergrün','hat mit Haaren besetzte Blätter und Stängel','Berührung ist schmerzhaft'],
  'Bärlauch': ['Nutzpflanze','sommergrün','ist ein Wildgemüse','riecht nach Knoblauch']
};


final Map restaurantMAP = {
  'Geld': ['Finanzen','aus Papier oder Metall','im Portemonnaie','wird zum Bezahlen genutzt'],
  'Musik': ['Inventar','verschiedene Stilrichtungen','läuft im Hintergrund','manchmal live zu hören'],
  'Tisch': ['Inventar','meist aus Holz','eckig oder rund','daran wird gesessen'],
  'Preis': ['Finanzen','hoch oder niedrig','angemessen oder nicht','Kosten'],
  'Glas': ['Inventar','Geschirr','ist durchsichtig','man trinkt daraus'],
  'Rechnung': ['Finanzen','aus Papier','kommt zuletzt ','Kosten für alles zusammen'],
  'Küche': ['Inventar','spezieller Raum','mit Gegenständen aus Edelstahl','hier wird gekocht'],
  'Gast': ['Person','nötig für Erfolg','isst und trinkt im Restaurant','wird bedient'],
  'Tafel': ['Inventar','aus Holz mit Kunststoffschicht','meist sehr groß','festlich eingedeckter Tisch'],
  'Messer': ['Inventar','Besteck','ist scharf','wird zum Schneiden genutzt'],
  'Teller': ['Inventar','aus Porzellan','meist rund','man isst davon'],
  'Kellner': ['Personal','meist gibt es mehrere davon','schwarz/weiß gekleidet','bedient Gäste'],
  'Wirt': ['Personal','oft Eigentümer','meistens anwesend','steht hinter der Theke'],
  'Speisen': ['Nahrung','kalt oder warm','stehen in der Karte','Getränke und ...'],
  'Koch': ['Personal','weiße Kleidung','arbeitet in der Küche','bereitet das Essen zu'],
  'Trinkgeld': ['Finanzen',	'aus Papier oder Metall', 'wenn man zufrieden war', 'erhält der Kellner'],
  'Besteck': ['Inventar',	'aus Silber oder Edelstahl',	'liegt neben dem Teller',	'wird zum Essen benötigt'],
  'Menü': ['Inventar',	'hat mehrere Gänge',	'ist meist günstiger',	'mittags besondere Angebote'],
  'Speisekarte': ['Inventar',	'klein oder umfangreich',	'wird gelesen',	'enthält Speisen und Getränke'],
  'Tresen': ['Inventar',	'man steht daran',	'trennt Personal und Kundschaft',	'auch Schanktisch genannt'],
  'Vorspeise': ['Gang',	'kleine Portion',	'oft Suppe oder Salat',	'erster Gang'],
  'Tischdecke': ['Dekoration',	'aus Stoff oder Papier',	'rund oder eckig',	'schützt den Tisch'],
  'Dessert': ['Gang',	'meist süß',	'manchmal Käseteller',	'letzter Gang'],
  'Aperitif': ['Getränk',	'kalt', 	'oft Prosecco', 	'bei Ankunft im Restaurant'],
  'Hauptgang': ['Gang',	'meist deftig',	'oft Fleisch oder Fisch',	'größter Gang'],
  'Weinkarte': ['Inventar',	'wird gelesen',	'enthält spezielle Getränke',	'Getränke sind rot, weiß oder rosé'],
  'Zapfhahn': ['Inventar',	'befindet sich an der Theke',	'meist an Fass angeschlossen',	'Armatur einer Bierleitung'],
  'Tageskarte': ['Inventar',	'wird gelesen',	'enthält saisonale Gerichte',	'jeden Tag neu'],
  'Reservierung': ['Termin',	'wird im Voraus getätigt',	'per E-Mail oder Telefon',	'Tisch wird damit freigehalten'],
  'Digestif': ['Getränk',	'kalt',	'oft Magenbitter', 'hilfreich nach dem Essen']
};

final Map sportartenMAP = {
  'Fußball': ['meist draußen','in der Gruppe','mit zwei Mannschaften','11 Spieler in einer Mannschaft'],
  'Tanzen': ['meist drinnen','alleine oder in der Gruppe','Bewegung zu Musik','rhytmische Bewegungen'],
  'Schwimmen': ['drinnen oder draußen','meist alleine','Wassersportart','in Freibad oder Meer'],
  'Gymnastik': ['meist drinnen','meist alleine','Bewegung zu Musik','die Kunst der Leibesübungen'],
  'Reiten': ['meist draußen','meist alleine','man benötigt einen Sattel','auf einem Pferd'],
  'Turnen': ['meist drinnen','meist alleine','auf dem Boden oder auf Geräten','Rad schlagen oder Handstand gehören dazu'],
  'Tennis': ['meist draußen','zu zweit oder viert','mit einem Schläger','mit einem kleinen gelben Ball'],
  'Boxen': ['meist drinnen','zu zweit','Kampfsportart','in einem Ring'],
  'Rudern': ['meist draußen','alleine oder in der Gruppe','Wassersportart','in einem Boot'],
  'Leichtathletik': ['meist draußen','meist alleine','mehrere Disziplinen','Hürdenlauf oder Kugelstoßen'],
  'Klettern': ['drinnen oder draußen','alleine oder in der Gruppe','mit Seilen gesichert','an einer Wand oder einem Berg'],
  'Fechten': ['meist drinnen','zu zweit','Kampfsportart','mit einem Degen'],
  'Yoga': ['meist drinnen','meist alleine','mit meditativen und körperlichen Übungen','häufig zur Entspannung'],
  'Tauchen': ['meist draußen','meist alleine','meist im Urlaub','unter Wasser'],
  'Tischtennis': ['meist drinnen','zu zweit','mit einem Schläger','mit einem kleinen Ball auf einer Platte'],
  'Basketball': ['meist in einer Halle',	'in der Gruppe',	'mit zwei Mannschaften',	'Ball wird in Korb geworfen'],
  'Eiskunstlauf': ['meist drinnen',	'alleine oder zu zweit',	'Bewegung zu Musik',	'auf dem Eis'],
  'Marathonlauf': ['meist draußen',	'meist alleine',	'Laufsportart',	'sehr lange Strecke'],
  'Baseball': ['meist draußen',	'in der Gruppe',	'Schlagballspiel',	'Ball wird geschlagen und gefangen'],
  'Volleyball': ['meist in einer Halle',	'in der Gruppe',	'mit zwei Mannschaften',	'Ball wird über ein Netz'],
  'Badminton': ['meist in einer Halle',	'zu zweit',	'mit einem Schläger',	'mit einem Federball'],
  'Joggen': ['meist draußen',	'meist alleine',	'Laufsportart',	'längere Strecke'],
  'Judo': ['meist in einer Halle',	'zu zweit',	'Kampfsportart',	'mit weißem Stoffanzug und Gürtel'],
  'Karate': ['meist in einer Halle',	'zu zweit',	'Kampfsportart',	'mit Schlägen, Tritten und Stößen'],
  'Walken': ['meist draußen',	'meist alleine',	'Laufsportart',	'mit zwei Stöcken'],
  'Squash': ['meist in einer Halle',	'alleine oder zu zweit',	'mit einem Schläger',	'mit einem kleinen Ball gegen in die Wand'],
  'Biathlon': ['meist draußen',	'meist alleine',	'Wintersportart',	'beinhaltet Langlauf und Schießen'],
  'Skisprung': ['meist draußen',	'meist alleine',	'Wintersportart',	'von einer Schanze'],
  'Aerobic': ['meist drinnen',	'in der Gruppe',	'Bewegung zu Musik',	'rhytmische Bewegungen'],
  'Snowboard': ['meist draußen',	'meist alleine',	'Wintersportart',	'mit beiden Füßen auf einem Brett']
};


final Map strassenverkehrMAP = {
  'Polizei': ['bewegt sich fort','sorgt für Sicherheit','darf im Notfall über Rot fahren','fährt mit Blaulicht'],
  'Auto': ['bewegt sich fort','Verkehrsteilnehmer','privates Verkehrsmittel','hat ein Gas- und ein Bremspedal'],
  'Kurve': ['hat einen festen Platz','Teil des Straßenverlaufs','erlaubt keinen geraden Straßenverlauf','man muss nach rechts oder links lenken'],
  'Straßenbahn': ['bewegt sich fort','nimmt am Verkehr teil','öffentliches Verkehrsmittel','fährt auf Schienen'],
  'Fahrrad': ['bewegt sich fort','Verkehrsteilnehmer','privates Verkehrsmittel','hat Pedale und zwei Räder'],
  'Baustelle': ['hat einen festen Platz','verändert den Straßenverlauf','erfordert langsames Fahren','Straße wird repariert'],
  'Feuerwehr': ['bewegt sich fort','sorgt für Sicherheit','darf im Notfall über Rot fahren','wird bei einem Brand gerufen'],
  'Kreuzung': ['hat einen festen Platz','Teil einer Straße','bietet vier verschiedene Richtungen','Schnittpunkt von zwei Straßen'],
  'Autobahn': ['hat einen festen Platz','Art einer Straße','mehrspurig','ermöglicht sehr schnelles Fahren'],
  'Bus': ['bewegt sich fort','Verkehrsteilnehmer','öffentliches Verkehrsmittel','kann mehr als zehn Personen befördern'],
  'Taxi': ['bewegt sich fort','Verkehrsteilnehmer','öffentliches Verkehrsmittel','kann von Personen gebucht werden'],
  'Fahrbahn': ['hat einen festen Platz','Teil einer Straße','Teil der Straße auf dem Autos fahren','wird durch weiße Streifen begrenzt'],
  'Fußgänger': ['bewegt sich fort','Verkehrsteilnehmer','langsamster Teilnehmer des Straßenverkehrs','nutzt meistens den Bürgersteig'],
  'Motorrad': ['bewegt sich fort','Verkehrsteilnehmer','privates Verkehrsmittel','besitzt zwei Räder und einen Motor'],
  'Asphalt': ['hat einen festen Platz','Teil der Straße','wird beim Straßenbau verwendet','wird mit einer Dampfwalze geglättet'],
  'Tankstelle': ['hat einen festen Platz',	'Teil einer Straße',	'am Straßenrand zu finden',	'wird aufgesucht wenn das Benzin leer ist'],
  'Ampel': ['hat einen festen Platz',	'sorgt für Sicherheit',	'muss vom Autofahrer beachtet werden',	'leuchtet rot', 'gelb oder grün'],
  'Krankenwagen': ['bewegt sich fort',	'Verkehrsteilnehmer',	'darf im Notfall über Rot fahren',	'wird bei Unfall mit Verletzten gerufen'],
  'Stau': ['hat einen festen Platz',	'verändert den Verkehrsfluss',	'erfordert langsames Fahren',	'passiert häufig bei stockendem Straßenverkehr'],
  'Bushaltestelle': ['hat einen festen Platz',	'Teil einer Straße',	'Anlaufstelle für ein öffentliches Verkehrsmittel',	'wird von Bussen genutzt'],
  'Fußgängerzone': ['hat einen festen Platz',	'Verkehrsfläche',	'darf mit dem Auto nicht befahren werden',	'wird ausschließlich von Menschen genutzt'],
  'Gehweg': ['hat einen festen Platz',	'Verkehrsfläche',	'darf mit dem Auto nicht befahren werden',	'anderes Wort für Bürgersteig'],
  'Bordstein': ['hat einen festen Platz',	'Teil einer Verkehrsfläche',	'Teil des Gehwegs',	'Rand des Gehwegs'],
  'Zebrastreifen': ['hat einen festen Platz',	'sorgt für Sicherheit',	'muss vom Autofahrer beachtet werden',	'zeigt einen Straßenübergang an'],
  'Kreisverkehr': ['hat einen festen Platz',	'Teil des Straßenverlaufs',	'bietet einen runden Straßenverlauf',	'ersetzt eine Kreuzung'],
  'Radweg': ['hat einen festen Platz',	'Verkehrsfläche',	'muss vom Autofahrer beachtet werden',	'ausschließllich für Farhrräder'],
  'Verkehrsschild': ['hat einen festen Platz',	'sorgt für Sicherheit',	'muss vom Autofahrer beachtet werden',	'zeigt z.B. die erlaubte Geschwindigkeit an'],
  'Leitplanke': ['hat einen festen Platz',	'sorgt für Sicherheit',	'Schutz aus Stahl',	'hindert ein Fahrzeug daran, von der Straße abzukommen'],
  'Blitzer': ['hat einen festen Platz',	'sorgt für Sicherheit',	'überwacht die Einhaltung der Geschwindigkeit',	'anderes Wort für Radarfalle'],
  'Mittelstreifen': ['hat einen festen Platz',	'Teil einer Straße',	'trennt Fahrbahnen',	'meist begrünte Trennung des Verkehrsstroms']
};

final Map supermarktMAP = {
  'Wein': ['Nahrungsmittel','Getränkeabteilung','meist rot oder weiß','Alkohol aus Trauben'],
  'Kaffee': ['Nahrungsmittel','Abteilung für Heißgetränke','dunkelbraun','aus gerösteten und gemahlenen Bohnen'],
  'Milch': ['Nahrungsmittel','Kühltruhe','weiß','von Kühen'],
  'Bier': ['Nahrungsmittel','Getränkeabteilung','meist goldgelb','aus Hopfen, Wasser, Malz und Hefe'],
  'Zeitschrift': ['kein Nahrungsmittel','nah an der Kasse','aus Papier','berichtet über Aktuelles'],
  'Tee': ['Nahrungsmittel','Abteilung für Heißgetränke','schwarz, grün oder rot','meist aus getrockneten Blättern'],
  'Ei': ['Nahrungsmittel','nah an der Gemüseabteilung','oval','von Hühnern'],
  'Eis': ['Nahrungsmittel','Tiefkühltruhe','kalt','italienische Spezialität'],
  'Blume': ['kein Nahrungsmittel','oft am Eingang','bunt und duftend','wächst auf der Wiese'],
  'Käse': ['Nahrungsmittel','an der Theke','gelb','aus Milch'],
  'Reis': ['Nahrungsmittel','Teigwarenabteilung','weiß','aus China'],
  'Schokolade': ['Nahrungsmittel','Süßwarenabteilung','braun oder weiß','aus Kakao'],
  'Salat': ['Nahrungsmittel','Gemüseabteilung','grün','wächst auf der Erde'],
  'Saft': ['Nahrungsmittel','Getränkeabteilung','meist orange, gelb oder rot','aus Früchten'],
  'Apfel': ['Nahrungsmittel','Obstabteilung','grün oder rot','wächst am Baum'],
  'Nudeln': ['Nahrungsmittel', 	'bei Grundnahrungsmitteln',	'gelb',	'aus Getreide'],
  'Kaugummi': ['Nahrungsmittel', 	'oft an der Kasse',	'meist weiß',	'wird lange gekaut'],
  'Leberwurst': ['Nahrungsmittel', 	'Fleischtheke',	'rosa oder braun',	'kalbsfleischhaltiger Brotaufstrich'],
  'Eierlikör': ['Nahrungsmittel', 	'Getränkeabteilung',	'gelb und dickflüssig',	'aus Alkohol, Zucker und Eiern'],
  'Heidelbeeren': ['Nahrungsmittel', 	'Obstabteilung',	'dunkelblau',	'wachsen an Sträuchern'],
  'Pizza': ['Nahrungsmittel', 	'Tiefkühltruhe',	'rund und flach',	'italienische Teigwarenspezialität'],
  'Apfelwein': ['Nahrungsmittel', 	'Getränkeabteilung',	'gelb',	'Alkohol aus Äpfeln'],
  'Mettwurst': ['Nahrungsmittel', 	'Fleischtheke',	'rotbraun',	'aus rohem Schweine- und Rindfleisch'],
  'Klopapier': ['kein Nahrungsmittel', 	'Haushaltswarenabteilung',	'meist weiß',	'aus bis zu fünf Papierlagen'],
  'Spülmittel': ['kein Nahrungsmittel', 	'Haushaltswarenabteilung',	'gelb, grün, blau oder weiß',	'aus Zitronensäure und Alkohol zum Abwaschen'],
  'Shampoo': ['kein Nahrungsmittel', 	'Kosmetikabteilung',	'meist weiß und duftend',	'aus flüssiger Masse für die Haare'],
  'Eiskaffee': ['Nahrungsmittel', 	'Getränkeabteilung',	'meist braun',	'Kaltgetränk, zuvor aus Bohnen aufgebrüht'],
  'Geschenkpapier': ['kein Nahrungsmittel', 	'Schreibwarenabteilung',	'aus Papier',	'zum Einpacken von Überraschungen'],
  'Rasierer': ['kein Nahrungsmittel', 	'Kosmetikabteilung',	'bunt und länglich',	'aus Klingen und Stiel'],
  'Eistee': ['Nahrungsmittel', 	'Getränkeabteilung',	'meist braun',	'Kaltgetränk, zuvor aus Blättern aufgegossen']
};


final Map tiereMAP = {
  'Hund': ['Säugetier','Haustier','hat Haare','bellt'],
  'Pferd': ['Säugetier','Nutztier','hat Fell','man kann darauf reiten'],
  'Vogel': ['kein Säugetier','Haus- oder Wildtier','hat Federn','kann fliegen'],
  'Fisch': ['kein Säugetier','Wildtier','hat Schuppen','schwimmt und hat Kiemen'],
  'Wolf': ['Säugetier','Wildtier','hat Fell','lebt im Rudel'],
  'Katze': ['Säugetier','Haustier','hat Fell','schnurrt'],
  'Fuchs': ['Säugetier','Wildtier','hat Fell','hat einen buschigen roten Schwanz'],
  'Schwein': ['Säugetier','Nutztier','hat Borsten','grunzt'],
  'Esel': ['Säugetier','Nutztier','hat Fell','ähnelt dem Pferd'],
  'Kuh': ['Säugetier','Nutztier','hat Fell','gibt Milch'],
  'Tiger': ['Säugetier','Wildtier','hat Fell','hat schwarze Streifen'],
  'Maus': ['Säugetier','Haus- oder Wildtier','hat Fell','kleines Nagetier'],
  'Bär': ['Säugetier','Wildtier','hat Fell','ist groß und meist braun'],
  'Löwe': ['Säugetier','Wildtier','hat Fell','hat eine Mähne'],
  'Huhn': ['kein Säugetier','Nutztier','hat Federn','legt Eier'],
  'Schildkröte': ['kein Säugetier',	'Wildtier',	'hat einen Panzer',	'wird sehr alt'],
  'Krokodil': ['kein Säugetier',	'Wildtier',	'hat einen Panzer',	'hat scharfe Zähne'],
  'Meerschweinchen': ['Säugetier',	'Haustier',	'hat Fell',	'tagaktives Nagetier'],
  'Leopard': ['Säugetier',	'Wildtier',	'hat Fell',	'ist sehr schnell'],
  'Jaguar': ['Säugetier',	'Wildtier',	'hat Fell',	'ist auch Symbol einer Automarke'],
  'Wiesel': ['Säugetier',	'Wildtier',	'hat Fell',	'ist flink'],
  'Luchs': ['Säugetier',	'Wildtier',	'hat Fell',	'gehört zur Familie der Wildkatzen'],
  'Hamster': ['Säugetier',	'Haustier',	'hat Fell',	'rennt nachts im Rad'],
  'Lama': ['Säugetier',	'Nutztier',	'hat Fell',	'spuckt'],
  'Otter': ['Säugetier',	'Wildtier',	'hat Fell',	'isst gerne Fisch'],
  'Elch': ['Säugetier',	'Wildtier',	'hat Fell',	'hat ein Geweih und röhrt'],
  'Robbe': ['Säugetier',	'Wildtier',	'hat Fell',	'Kinder werden Heuler genannt'],
  'Pinguin': ['kein Säugetier',	'Wildtier',	'hat Federn',	'ist schwarz und weiß'],
  'Alpaka': ['Säugetier',	'Nutztier',	'hat Fell',	'gehört zur Familie der Kamele'],
  'Delfin': ['Säugetier',	'Wildtier',	'hat eine glatte Haut',	'ist stromlinienförmig und sehr intelligent']
};

final Map werkzeugeMAP = {
  'Leiter': ['groß','aus Holz oder Metall','hat Sprossen','benötigt man um hinaufzuklettern'],
  'Hammer': ['mittelgroß','aus Holz und Metall','hat einen Stiel und einen schweren Kopf','benötigt man um Nägel in die Wand zu schlagen'],
  'Haken': ['klein','aus Holz, Metall oder Kunststoff','hat eine gebogene oder abgeknickte Form','benötigt man um etwas daran aufzuhängen'],
  'Nagel': ['klein','aus Metall','hat eine Spitze','benötigt man um Bilder aufzuhängen'],
  'Pinsel': ['mittelgroß','aus Holz und Kunstfasern','hat einen Holzgriff mit Borsten','benötigt man um etwas anzustreichen'],
  'Seil': ['lang','aus Natur- oder Kunstfaser','hat eine geflochtene Struktur','benötigt man um etwas festzubinden'],
  'Bit': ['klein','aus Metall','hat verschiedene Formen, Schlitz, Vierkant, etc.','benötigt man für einen Akkuschrauber'],
  'Besen': ['groß','aus Holz und Kunstfasern','hat einen Stiel und Borsten','benötigt man um Dreck zu beseitigen'],
  'Schere': ['mittelgroß','aus Metall und Plastik','hat Griffe für Daumen, Zeige- und Mittelfinger','benötigt man um Dinge zu zertrennen'],
  'Zange': ['mittelgroß','aus Metall und Plastik','hat Griff, Gelenk und Kopf','benötigt man um Nägel zu entfernen'],
  'Schraube': ['klein','aus Metall','hat ein Gewinde','benötigt man um Möbelteile miteinander zu verbinden'],
  'Meißel': ['mittelgroß','aus Metall','hat eine Schneide','benötigt man um etwas zu trennen oder zu bearbeiten'],
  'Pinzette': ['klein','aus Metall','hat einen Griff für Daumen und Zeigefinger','benötigt man um einen Splitter zu entfernen'],
  'Feile': ['mittelgroß','aus Metall und Plastik','hat eine gerade Form','benötigt man um etwas zu glätten'],
  'Schraubenschlüssel': ['mittelgroß','aus Metall','hat zwei nutzbare Enden','benötigt man um Muttern anzuziehen oder zu lösen'],
  'Zollstock': ['lang',	'aus Holz, Kuststoff oder Metall',	'hat miteinander verbundene gerade Holzteile',	'benötigt man um etwas zu messen'],
  'Kreissäge': ['groß',	'aus Metall',	'hat eine gezackte, runde Schneideplatte',	'benötigt man um Holz und Metall zu zerkleinern'],
  'Dübel': ['klein',	'aus Plastik oder Holz',	'hat eine spitz zulaufende Form',	'benötigt man als Halterung für Schrauben'],
  'Wasserwaage': ['lang',	'aus Holz, Kunststoff und Metall',	'hat eine längliche, rechteckige Form',	'benötigt man um etwas gerade anzubringen'],
  'Bohrmaschine': ['mittelgroß',	'aus Metall und Kunststoff',	'hat ein Gewinde für Aufsätze',	'benötigt man um tiefe Löcher in einer Wand herzustellen'],
  'Lötkolben': ['mittelgroß',	'aus Metall und Kunststoff',	'hat eine stiftartige Form',	'benötigt man um Metalle aufzuschmelzen'],
  'Kabeltrommel': ['mittelgroß',	'aus Kunststoff und Metall',	'hat eine runde Form',	'benötigt man um eine Kunststoffschnur aufzurollen'],
  'Drahtbürste': ['mittelgroß',	'aus Holz und Metall',	'hat einen Holzgriff mit Borsten',	'benötigt man zum Reinigen von Flaschen'],
  'Winkelmesser': ['mittelgroß',	'aus Metall oder Plastik',	'hat eine Maßstabangabe',	'benötigt man für das Ausmessen von Ecken'],
  'Verlängerungskabel': ['lang',	'aus Kunststoff und Metall',	'hat einen Stecker und eine Kupplung',	'benötigt man um Strom zu verlegen'],
  'Motorsäge': ['groß',	'aus Metall',	'hat eine lange und gezackte Spitze',	'benötigt man um Holz zu schneiden'],
  'Handbohrer': ['mittelgroß',	'aus Metall',	'hat einen Seitengriff',	'benötigt man um ohne Strom Löcher herzustellen'],
  'Schweißgerät': ['groß',	'aus Metall und Kunststoff',	'hat einen viereckigen Kasten',	'benötigt man um Dinge mittels Wärme zu verbinden'],
  'Schleifpapier': ['mittelgroß',	'aus Papier und Kunststoff',	'hat eine Körnung',	'benötigt man um eine raue Fläche zu glätten'],
  'Lüsterklemme': ['klein',	'aus Kunststoff und Metall',	'hat Klemmschrauben',	'benötigt man um eine Lampe am Strom anzuschließen']
};

