final Map nfallMAP = {
  'Scheibenwischer': ['direkt sichtbar','Metall mit Gummi','vorne zwei und hinten einer','zum Säubern der Front- oder Heckscheibe bei Regen'],
  'Auspuff': ['direkt sichtbar','Metall','hinten unten','leitet die Abgase nach außen'],
  'Stoßstange': ['direkt sichtbar','Stahl mit Kunststoffhaut','an Front und Heck','minimiert von Unfallschäden'],
  'Klimaanlage': ['nicht direkt sichtbar','Metall','im Motorraum mit Verbindung zum Innenraum','sorgt für angenehme Temperatur und klare Scheiben'],
  'Tachometer': ['direkt sichtbar','Metall','vor dem Fahrer','zeigt die aktuelle Geschwindigkeit an'],
  'Gangschaltung': ['direkt sichtbar','Metall mit Kunststoff oder Leder','rechts vom Fahrer','zur Bedienung des Getriebes mit der Hand'],
  'Bremspedal': ['direkt sichtbar','Metall','im Fußraum des Fahrers','wird beim Starten des Autos getreten'],
  'Handschuhfach': ['direkt sichtbar','Kunststoff','vor dem Beifahrer','zum Transport kleinerer Gegenstände'],
  'Zündkerze': ['nicht direkt sichtbar','Metall und Keramik','im Motorraum','erzeugt einen Funken zum Anlassen des Autos'],
  'Wagenheber': ['nicht direkt sichtbar','Metall','im Kofferraum','wird beim Reifenwechsel zum Hochbewegen des Autos benötigt'],
  'Rückbank': ['direkt sichtbar','Stoff oder Leder','hinter den Vordersitzen','hier sitzen meistens Kinder'],
  'Autotür': ['direkt sichtbar','Metall mit (Kunst-)Stoff oder Leder','vorne und hinten je zwei','muss zum Einsteigen geöffnet werden'],
  'Sicherheitsgurt': ['direkt sichtbar','Nylongewebe mit Metallzunge','vorne und hinten je zwei','Rückhaltesystem zur Sicherheit der Personen im Auto'],
  'Heckscheibe': ['direkt sichtbar','Glas','hinten','ermöglicht die Sicht aus dem Auto nach hinten'],
  'Benzintank': ['nicht direkt sichtbar','Aluminium, Stahl oder Kunststoff','über Hinterachse oder davor unter Rücksitzen','enthält den Kraftstoff'],
  'Schiebedach': ['direkt sichtbar','Glas','oben','Öffnungssystem nach oben'],
  'Kopfstütze': ['direkt sichtbar','Metall mit Stoff oder Leder','eine an jedem Sitz','zum Schutz der Halswirbelsäule bei Unfällen'],

  'Nagellack': ['erweiterte Ausstattung','ein Kosmetikprodukt','farbliche Nagelgestaltung','meist rot oder rosa'],
  'Nagelschere': ['erweiterte Ausstattung','aus Metall','zum Schneiden','für Finger- und Fußnägel'],
  'Shampoo': ['erweiterte Ausstattung','eine Art Creme','für die Haare','zum Waschen'],
  'Duschkabine': ['Grundausstattung','meist aus Glas','grenzt eine Brause von der Umgebung ab','mit Tür zum Öffnen und Schließen'],
  'Fliese': ['Grundausstattung','aus Stein oder Marmor','meist viereckig','Bodenbelag'],
  'Handtuchhalter': ['erweiterte Ausstattung','aus Plastik oder Metall','zum Aufhängen','für Handtücher'],
  'Duschvorhang': ['erweiterte Ausstattung','meist aus Stoff','grenzt eine Brause von der Umgebung ab','zum Hin- und Herschieben'],
  'Zahnseide': ['erweiterte Ausstattung','aus Kunststoff oder textiler Faser','zum Reinigen von Zwischenräumen im Mund','gewachst und ungewachst'],
  'Badezimmerschrank': ['Grundausstattung','meist aus Holz','zur Aufbewahrung','für Badezimmerartikel'],
  'Klobürste': ['erweiterte Ausstattung','meist aus Plastik','hat einen langen Stiel und Borsten','zum Reinigen der Toilette'],
  'Zahnputzbecher': ['erweiterte Ausstattung','meist aus Plastik','zum Mund ausspülen','Zahnbürste steht meist darin'],
  'Duschgel': ['erweiterte Ausstattung','eine Art Creme','für den Körper','zum Waschen'],
  'Badematte': ['erweiterte Ausstattung','meist aus Stoff','meist viereckig','Bodenbelag'],
  'Duschhaube': ['erweiterte Ausstattung','meist aus Plastik','für die Haare','Haare bleiben damit trocken'],
  'Duschkopf': ['Grundausstattung','meist aus Metall','Wasser kommt da raus','zum Abbrausen'],

  'Huhn': ['Tier','häufig braun oder weiß','Schnabel und Federn','legt Eier'],
  'Scheune': ['Gebäude','groß und mit Holzbalken','dient als Lagerraum','für Stroh, Getreide und Fahrzeuge'],
  'Spaten': ['Gartenwerkzeug','zum Graben','drückt man mit dem Fuß in die Erde','große eckige Schaufel'],
  'Teich': ['Gewässer','für Fische und Enten','mit Süßwasser','kleiner als ein See'],
  'Schaf': ['Tier','häufig weiß','dickes Fell','wird zu Wolle verarbeitet'],
  'Kartoffel': ['Nahrungsmittel','Gemüse','außen braun und innen gelb','wird auch Erdapfel genannt'],
  'Ziege': ['Tier','weiß, braun oder schwarz','hat Hörner','aus der Milch wird Käse hergestellt'],
  'Beet': ['kleines Stück Boden','häufig grün und bunt','zieht landwirtschaftliche Geräte','mit Blumen, Kräutern oder Gemüse'],
  'Traktor': ['Fahrzeug','für das Feld geeignet','im Garten oder vor dem Haus','parkt in der Scheune '],
  'Rechen': ['Gartenwerkzeug','für Laub auf der Wiese','häufig Holzstiel mit Metallstäben','zum Kehren'],
  'Hundehütte': ['Gebäude','häufig aus Holz und Metall','Schlafplatz für ein Tier','der Hund lebt darin'],
  'Gummistiefel': ['Kleidungsstück','für die Füße','aus Kunststoff','wird bei Matsch und Regen getragen'],
  'Milchkanne': ['Gefäß','it Henkel','beinhaltet Flüssigkeit','von Kühen oder Ziegen'],
  'Mistgabel': ['Gartenwerkzeug','mit Holzstiel','hat drei Zinken','zum Säubern der Ställe'],
  'Latzhose': ['Kleidungsstück','Arbeitskleidung','hat zwei Träger','spezielle Form einer Hose '],

  'Therapeut': ['arbeitet viel mit Menschen','erfordert ein Studium/eine Ausbildung','erfragt die Vorgeschichte des Patienten','führt eine Therapie mit Patienten durch'],
  'Fotograf': ['arbeitet viel mit Materialien','erfordert ein Studium/eine Ausbildung','benötigt eine Kamera','macht Bilder von Personen oder Ojekten'],
  'Kassierer': ['arbeitet viel mit Menschen','ohne Ausbildung möglich','nimmt Geld entgegen','tippt Preise in eine Kasse ein'],
  'Uhrmacher': ['arbeitet viel mit Materialien','erfordert eine Ausbildung','stellt Zeitmessgeräte her','repariert Uhren'],
  'Klempner': ['arbeitet viel mit Materialien','erfordert eine Ausbildung','bearbeitet Gegenstände aus Metall','wird bei einem verstopften Abfluss gerufen'],
  'Elektriker': ['arbeitet viel mit Materialien','erfordert eine Ausbildung','misst Spannung und Widerstand','repariert elektrische Anlagen'],
  'Bademeister': ['arbeitet viel mit Menschen','erfordert eine Ausbildung','überwacht den Betrieb eines Schwimmbads','rettet Menschen aus dem Wasser'],
  'Informatiker': ['arbeitet viel mit Materialien','erfordert ein Studium/eine Ausbildung','arbeitet am Computer','programmiert eine Software oder Internetseite'],
  'Masseur': ['arbeitet viel mit Menschen','erfordert eine Ausbildung','führt Bewegungen mit Händen aus','löst Verspannungen am Körper des Klienten'],
  'Dachdecker': ['arbeitet viel mit Materialien','erfordert eine Ausbildung','bringt Dämmstoff an Gebäuden an','deckt Dächer mit Ziegeln'],
  'Konditor': ['arbeitet viel mit Materialien','erfordert eine Ausbildung','backt für spezielle Anlässe','backt Torten'],
  'Tierpfleger': ['arbeitet viel mit Menschen','erfordert eine Ausbildung','füttert und pflegt Lebewesen','kümmert sich um Vier- und Zweibeiner'],
  'Flugbegleiter': ['arbeitet viel mit Menschen','erfordert eine Ausbildung','fliegt in andere Länder','kümmert sich um Passagiere in einem Flugzeug'],
  'Hotelkaufmann': ['arbeitet viel mit Materialien','erfordert eine Ausbildung','gibt Zimmerschlüssel an Gäste aus','arbeitet in der Rezeption in einem Hotel'],
  'Müllmann': ['arbeitet viel mit Materialien','erfordert eine Ausbildung','entsorgt Abfälle','leert Mülltonnen'],

  'Lübeck': ['Schleswig-Holstein','Hansestadt','Marzipan','Holstentor'],
  'Regensburg': ['Bayern','in der Oberpfalz','Donau-Schifffahrtsmuseum','Steinerne Brücke'],
  'Tübingen': ['Baden-Württemberg','klassische Universitätsstadt','Paul-Horn-Arena','Stiftskirche'],
  'Aachen': ['Nordrhein-Westfalen','Kurstadt','Karl der Große','Printen'],
  'Mannheim': ['Baden-Württemberg','ehemalige Residenzstadt der Kurpfalz','Wasserturm','Quadratestadt'],
  'Trier': ['Rheinland-Pfalz','älteste Stadt Deutschlands','Karl-Marx-Haus','Porta Nigra'],
  'Dortmund': ['Nordrhein-Westfalen','bevölkerungsreichste Stadt im Ruhrgebiet','das "U"','Borussia'],
  'Koblenz': ['Rheinland-Pfalz','im Norden von Rheinland-Pfalz','Festung Ehrenbreitstein','Deutsches Eck'],
  'Ulm': ['Baden-Württemberg','im Südosten der Schwäbischen Alb','Münster','Spatz'],
  'Chemnitz': ['Sachsen','im Südwesten von Sachsen','Siegertsches Haus','Roter Turm'],
  'Erlangen': ['Bayern','in Mittelfranken','Botanischer Garten','Hugenottenkirche'],
  'Bochum': ['Nordrhein-Westfalen','Zentrum des mittleren Ruhrgebiets','Zeiss Planetarium','Deutsches Bergbau-Museum'],
  'Ludwigshafen': ['Rheinland-Pfalz','größte Stadt der Pfalz','Wilhelm-Hack-Museum','BASF'],
  'Solingen': ['Nordrhein-Westfalen','im Bergischen Land','Schloss Burg','Zwilling-Messer'],
  'Idstein': ['Hessen','Rheingau-Taunus-Kreis','Hexenturm','Sitz der Hochschule Fresenius'],

  'Tandem': ['fährt auf Rädern','durch Muskelkraft betrieben','transportiert höchstens zwei Personen','Fahrrad für zwei Personen'],
  'Motorroller': ['fährt auf Rädern','durch Motor betrieben','transportiert höchstens zwei Personen','hat ein Trittbrett statt Fußrasten'],
  'Gabelstapler': ['fährt auf Rädern','durch Motor betrieben','Arbeitsfahrzeug','transportiert Paletten'],
  'Cabriolet': ['fährt auf Rädern','durch Motor betrieben','transportiert mehrere Personen','kann das Dach öffnen'],
  'Hundeschlitten': ['fährt auf Kufen','durch Muskelkraft betrieben','transportiert höchstens Personen oder Fracht','wird von Tieren über den Schnee gezogen'],
  'Dreirad': ['fährt auf Rädern','durch Muskelkraft betrieben','transportiert eine Person','Tretfahrzeug für kleine Kinder'],
  'Dampfwalze': ['fährt auf Rollen','durch Motor betrieben','Arbeitsfahrzeug','wird zum Verdichten der Straßendecke genutzt'],
  'Mofa': ['fährt auf Rädern','durch Motor betrieben','transportiert höchstens zwei Personen','motorisiertes Fahrrad'],
  'Polizeiauto': ['fährt auf Rädern','durch Motor betrieben','Arbeitsfahrzeug','fährt oft mit Blaulicht'],
  'Feuerwehrauto': ['fährt auf Rädern','durch Motor betrieben','Arbeitsfahrzeug','löscht Flammen'],
  'Dampflokomotive': ['fährt auf Schienen','durch Motor betrieben','transportiert viele Personen','wird von Wasserdampf angetrieben'],
  'Bollerwagen': ['fährt auf Rädern','durch Muskelkraft betrieben','transportiert kleine Kinder oder Gegenstände','muss gezogen werden'],
  'Einrad': ['fährt auf Rädern','durch Muskelkraft betrieben','transportiert eine Person','hat einen Sattel und nur einen Reifen'],
  'Abschleppwagen': ['fährt auf Rädern','durch Motor betrieben','Arbeitsfahrzeug','transportiert andere Fahrzeuge'],
  'Seifenkiste': ['fährt auf Rädern','durch Hangabtriebskraft bewegt','transportiert höchstens zwei Personen','ist oft selbstgebaut'],

  'Liegestuhl': ['Gegenstand','aus Holz oder Kunststoff','zum Ausruhen in der Waagerechten','zum Zusammenklappen'],
  'Sonnenschirm': ['Gegenstand','aus Stoff und Metall','groß und mit einer Stange und Stoff','spendet Schatten'],
  'Grill': ['Gegenstand','aus Metall','zum Erhitzen','zum Essen zubereiten'],
  'Gießkanne': ['Gegenstand','aus Kunststoff oder Metall','mit siebartigem Aufsatz','zum Pflanzen bewässern'],
  'Hängematte': ['Gegenstand','aus Stoff','zum Liegen','zum Schaukeln'],
  'Sandkasten': ['Gegenstand','aus Holz','großer und meist eckig','Kinder bauen darin Burgen'],
  'Harke': ['Gegenstand','aus Metall und Holz','für die Gartenarbeit','zum Lockern der Erde'],
  'Rechen': ['Gegenstand','aus Metall und Holz','für die Gartenarbeit','zum Laub zusammen kehren'],
  'Regentonne': ['Gegenstand','aus Kunststoff','groß, rund und innen hohl','zum Wasser sammeln'],
  'Rasenmäher': ['Gegenstand','aus Kunststoff und Metall','großer und verursacht Lärm','zum Gras kürzen'],
  'Vogelhaus': ['Gegenstand','aus Holz','besitzt ein Dach','Futterstelle für fliegende Tiere'],
  'Rutsche': ['Gegenstand','aus Kunststoff oder Metall','groß mit schiefer Ebene','Kinder gleiten beim Spielen herunter'],
  'Wasserschlauch': ['Gegenstand','aus Kunststoff oder Gummi','langer und innen hohl','Wasser wird darin transportiert'],
  'Setzling': ['Pflanze','grün','klein','junger Pflanzenableger'],
  'Blumenerde': ['Pflanze','dunkelbraun','feinkörniges Gemisch','für Zierpflanzen geeigneter Nährboden'],

  'Rhabarber': ['wächst am Boden','meist rot','wird geschält und zubereitet','wird oft zu Kompott verarbeitet'],
  'Rosenkohl': ['wächst auf dem Feld','grün und rund','vor dem Kochen werden die äußeren Blätter entfernt','wird meist als Beilage serviert'],
  'Weißkohl': ['wächst auf dem Feld','weiß oder hellgrün','wird geschnitten und gekocht','eine Form von Kohl'],
  'Ingwer': ['wächst in der Erde','braun und gelb','wird geschnitten und gekocht','wird oft als Gewürz verwendet'],
  'Rotkohl': ['wächst auf dem Feld','rot','wird geschnitten und gekocht','wird im Winter oft als Beilage serviert'],
  'Grünkohl': ['wächst auf dem Feld','grün','wird geschnitten und gekocht','eine Form von Kohl'],
  'Artischocke': ['wächst auf dem Feld','grün','wird gewaschen und der holzige Stiel entfernt','sieht aus wie eine Blume'],
  'Lauch': ['wächst auf dem Feld','grün und weiß','wird geputzt und geschnitten','gibt es als Stange zu kaufene'],
  'Wirsing': ['wächst auf dem Feld','grün','wird gewaschen und die Blätter abgetrennt','wird im Winter oft als Beilage serviert'],
  'Karotte': ['wächst auf dem Feld','orange','wird oft geschält und geschnitten','wird roh oder gekocht gegessen'],
  'Brokkoli': ['wächst auf dem Feld','grün','wird geputzt und die Röschen abgetrennt','eine Form von Kohl'],
  'Aubergine': ['wächst am Strauch','violett','wird geputzt und gekocht','wird auch Eierfrucht genannt'],
  'Peperoni': ['wächst am Strauch','rot oder grün','wird gewaschen und die Kerne entfernt','meist sehr scharf'],
  'Süßkartoffel': ['wächst in der Erde','rot oder orange','wird geschält und gekocht','eine Form der Knollenpflanze'],
  'Zucchini': ['wächst auf dem Feld','grün','wird gewaschen und geschnitten','sieht einer Gurke ähnlich'],

  'Orangensaft': ['ohne Alkohol','orange','wird durch Pressen einer Frucht gewonnen','schmeckt süß und wird gerne zum Frühstück getrunken'],
  'Apfelsaft': ['ohne Alkohol','häufig hellgelb','wird durch Pressen einer Frucht gewonnen','schmeckt süß und wird gerne von Kindern getrunken'],
  'Glühwein': ['mit Alkohol','häufig rot','wird heiß serviert','wird auf dem Weihnachtsmarkt getrunken'],
  'Apfelwein': ['mit Alkohol','häufig hellgelb','wird aus einer Frucht gewonnen','wird meistens mit Wasser gespritzt'],
  'Tomatensaft': ['ohne Alkohol','rot','wird aus einem Gemüse hergestellt','wird gerne im Flugzeug getrunken'],
  'Radler': ['mit Alkohol','hellgelb','wird gerne im Sommer getrunken','besteht aus Bier und Limonade'],
  'Fanta': ['ohne Alkohol','gelb','wird künstlich hergestellt','süßes Getränk der Coca-Cola-Company'],
  'Kirschsaft': ['ohne Alkohol','dunkelrot','wird häufig aus sauren Früchten gewonnen','wird mit Wasser verdünnt und gesüßt'],
  'Whiskey': ['mit Alkohol','häufig golden','wird durch Destillation von Getreide gewonnen','wird oft aus einem Glas mit dickem Glasboden getrunken'],
  'Ananassaft': ['ohne Alkohol','hellgelb','wird aus einer Frucht gemacht','schmeckt süß und wird oft in Cocktails verwendet'],
  'Karottensaft': ['ohne Alkohol','orange','wird aus einem Gemüse hergestellt','eher dickflüssig, mit viel Vitamin A'],
  'Eistee': ['ohne Alkohol','häufig dunkelbraun','wird heiß hergestellt und schnell abgehült','meist Schwarztee mit Zitronensaft'],
  'Bowle': ['mit Alkohol','unterschiedliche Farben','wird mit Sekt gemacht','wird meist mit Fruchtstücken serviert'],
  'Hefeweizen': ['mit Alkohol','gelb','wird aus einem Getreide hergestellt','wird aus einem speziellen hohen Glas getrunken'],
  'Cappuccino': ['ohne Alkohol','braun und weiß','enthält Koffein','Espresso mit heißer Milch und Milchschaum'],

  'Helsinki': ['Nordeuropa','Finnland','Dom','Senatsplatz'],
  'Tokio': ['Ostasien','Japan','Senso-ji-Tempel','Meiji-Schrein'],
  'Lissabon': ['dwesteuropa','Portugal','Torre de Belém','Castelo de São Jorge'],
  'Ankara': ['Vorderasien','Türkei','Kocatepe-Moschee','Anıtkabir'],
  'Oslo': ['Nordeuropa','Norwegen','Festung Akershus','Fjord'],
  'Kiew': ['Osteuropa','Ukraine','Sophienkathedrale','Höhlenkloster'],
  'Teheran': ['Naher Osten','Iran','Golestanpalast','Freiheitsturm'],
  'Bagdad': ['Naher Osten','Irak','al-Schahid-Monument','Al-Jawadain Schrein'],
  'Dublin': ['Westeuropa','Irland','Trinity College','Temple Bar'],
  'Hanoi': ['Südostasien','Vietnam','Hanoi Hilton','Ho Chi Minh-Mausoleum'],
  'Havanna': ['Große Antillen','Kuba','Uferpromenade Malécon','Altstadt La Habana Viejo'],
  'Bangkok': ['Südostasien','Thailand','Großer Palast','Wat Arun'],
  'Ottawa': ['Nordamerika','Kanada','Rideau Canal','Parlamentshügel'],
  'Nairobi': ['Ostafrika','Kenia','Karen Blixen Museum','Nationalpark'],
  'NeuDelhi': ['Südasien','Indien','Qutb Minar','Rotes Fort'],

  'Kran': ['Fahrzeug','zum Verladen von Lasten','Turm mit Drehwerk','Hebehilfe für sehr schwere Güter'],
  'Bagger': ['Fahrzeug','hat einen Greifarm mit großer Schaufel','löst und bewegt Boden und Felsen','Fahrzug zum Aushuben der Baugrube'],
  'Polier': ['Beruf','erfordert eine Ausbildung','Bindeglied zwischen Bauarbeitern und Bauleitung','Leiter einer Baustelle oder eines Baustellenabschnittes'],
  'Rohbau': ['Gebäudezustand','erster Bauabschnitt','wird mit dem Richtfest gefeiert','Bauwerk mit Dachkonstruktion ohne Fenster und Türen'],
  'Dachdecker': ['Beruf','erfordert eine Ausbildung','arbeitet häufig in der Höhe','führt Dach- und Abdichtungsarbeiten aus'],
  'Schubkarre': ['Hilfsmittel','hat Wanne und Rad','zum Transport von Baumaterialien','wird von einem Arbeiter geschoben'],
  'Installateur': ['Beruf','erfordert eine Ausbildung','kümmert sich un technische Anlagen','zuständig für Sanitäts-, Heizungs- und Klimatechnik'],
  'Schutzbrille': ['Schutzausrüstung','aus weichem oder hartem Kunststoff','Schutz vor Staub und Splittern','schützt die Augen'],
  'Wasserwaage': ['Messgerät','aus Holz, Aluminium oder Kunststoff','längliche Form','Prüfgerät zur Ausrichtung mittels Flüssigkeit'],
  'Bohrmaschine': ['Werkzeug','elektrisch betrieben','wechselbare Aufsätze','wird verwendet, um Löcher zu erstellen'],
  'Bauzeichnung': ['Hilfsmittel','grafische Darstellung','zeigt räumliche Ausmaße','enthält wichtige Informationen für die Bauausführung'],
  'Stichsäge': ['Werkzeug','aus Holz und Metall','handgeführt oder elektronisch','zum Schneiden von Ausschnitten oder Erweitern von Öffnungen'],
  'Gerüstbauer': ['Beruf','erfordert eine Ausbildung','arbeitet häufig in der Höhe','errichtet Flächen für die Arbeit an der Außenwand'],
  'Gehörschutz': ['Schutzausrüstung','aus Kunststoff','gibt es als Kapseln oder Stöpsel','schützt vor lauten Geräuschen'],
  'Abdeckfolie': ['Material','aus Kunststoff','wird großflächig ausgelegt','schützt vor Verschmutzung'],

  'Einkaufen': ['drinnen','Selbstversorgung','Obst, Gemüse, Kleidung','bei REWE, Edeka, Kaufhof'],
  'Nähen': ['drinnen','Handarbeit','mit Nadel und Faden','Tischdecken, Kleider, Anzüge'],
  'Wintersport': ['häufig draußen','körperliche Aktivität','im Winter','Ski, Snowboard, Schlitten'],
  'Disco': ['drinnen','Nachtleben','Bewegung zu lauter Musik','im Club'],
  'Basteln': ['drinnen','Handarbeit','mit Schere, Papier und Kleber','Geburtstagskarten, Weihnachtsschmuck'],
  'Kreuzworträtsel': ['drinnen und draußen','Denksport','mit Stift auf Papier','Wörter raten in Zeitungen'],
  'Häkeln': ['drinnen','Handarbeit','Maschen aus Wolle','Mützen, Topflappen und Schal'],
  'Camping': ['draußen','Urlaub und Ferien','Übernachtungsmöglichkeit','Wohnwagen, Zelt, Wohnmobil'],
  'Jodeln': ['drinnen und draußen','stimmliche Aktivität','ohne Instrumente','Singen mit Silben und ohne Text'],
  'Töpfern': ['drinnen','Handarbeit','Keramikherstellung','Vasen, Schalen, Krüge'],
  'Kampfsport': ['eher drinnen','körperliche Aktivität','Zweikampf','Judo, Karate und Boxen'],
  'Fitness': ['drinnen und draußen','Ausdauer und Kraft','Sportstudio','Laufband, Crosstrainer und Joggen'],
  'Modelleisenbahn': ['drinnen','Modellbau','Gleise, Landschaft und Züge','Märklin, Buco'],
  'Aerobic': ['eher drinnen','körperliche Aktivität','mit Musik, Fitnesstraining in der Gruppe','klassische Gymnasik mit Tanz'],
  'Heimwerken': ['eher drinnen','Haus und Garten','mit Maschinen und Werkzeug','Gartenhütte, Hausbau'],

  'Unterhemd': ['wird von Männern und Frauen getragen','wird am Oberkörper getragen','hat keine Ärmel','gehört zur Unterwäsche'],
  'Dirndl': ['wird meist von Frauen getragen','wird am ganzen Körper getragen','ist ein spezielles Kleid','ist eine Tracht aus Bayern'],
  'BH': ['wird meist von Frauen getragen','wird am Oberkörper getragen','hat zwei Körbchen','stützt und formt die Brust'],
  'Gummistiefel': ['wird von Männern und Frauen getragen','wird an den Füßen getragen','ist aus Kunststoff','wird bei Regen getragen'],
  'Anorak': ['wird von Männern und Frauen getragen','wird am Oberkörper getragen','hat zwei lange Ärmel und ist wetterfest','ist eine Jacke mit Kapuze'],
  'Blazer': ['wird von Männern und Frauen getragen','wird am Oberkörper getragen','hat zwei lange Ärmel und einen Kragen','wird häufig über einer Bluse getragen'],
  'Strumpfhose': ['wird meist von Frauen getragen','wird am Unterkörper getragen','ist eng anliegend und unten geschlossen','ist eine Verbindung aus Unterhose und Strümpfen'],
  'Hausschuh': ['wird von Männern und Frauen getragen','wird an den Füßen getragen','ist bequem und hat meist keinen Absatz','wird meist im Haus getragen'],
  'Latzhose': ['wird von Männern und Frauen getragen','wird am ganzen Körper getragen','ist meist eine Arbeitskleidung','wird am Oberkörper mit Hosenträgern gehalten'],
  'Poncho': ['wird von Männern und Frauen getragen','wird am Oberkörper getragen','ist ein rechteckig und hat ein Loch in der Mitte','ist ein Umhang der Indios'],
  'Korsage': ['wird meist von Frauen getragen','wird am Oberkörper getragen','ist eng anliegend','wird geschnürt und macht schlank'],
  'Turnschuh': ['wird von Männern und Frauen getragen','wird an den Füßen getragen','ist bequem und wird geschnürt','wird beim Sport oder in der Freizeit getragen'],
  'Leggings': ['wird meist von Frauen getragen','wird am Unterkörper getragen','ist eng anliegend und unten offen','ist eine Hose'],
  'Jogginghose': ['wird von Männern und Frauen getragen','wird am Unterkörper getragen','ist bequem und am Bund elastisch','wird beim Laufen oder in der Freizeit getragen'],
  'Pullunder': ['wird von Männern und Frauen getragen','wird am Oberkörper getragen','hat keine Ärmel','ist ein ärmelloser Pullover'],

  'Ellenbogen': ['von außen sichtbar','gehört zum Arm','Verbindung zwischen Ober- und Unterarm','man kann sich darauf abstützen'],
  'Wirbelsäule': ['von außen nicht sichtbar','gehört zum Rücken','besteht aus knöchernen Elementen','Bandscheiben verbinden die Wirbel miteinander'],
  'Handgelenk': ['von außen sichtbar','gehört zur Hand','Verbindung zwischen Hand und Arm','man trägt Uhren daran'],
  'Wimper': ['von außen sichtbar','sitzen an den Augenlidern','schützen vor Schmutz und Dreck','Frauen schminken sie sich mit Tusche'],
  'Lippe': ['von außen sichtbar','gehört zum Mund','weich, wulstig, beweglich, rötlich','man kann damit küssen'],
  'Gesäß': ['von außen sichtbar','sitzt unter dem Rücken','besteht aus zwei "Backen"','man sitzt darauf'],
  'Knöchel': ['von außen sichtbar','ist ein Knochen','Verbindung zwischen Fuß und Bein','gehört zum Fußgelenk'],
  'Niere': ['von außen nicht sichtbar','ist ein Organ','es gibt zwei davon','sieht aus wie eine Bohne'],
  'Wade': ['von außen sichtbar','gehört zum Unterschenkel','hinterer Teil des Unterschenkels','dort entstehen oft Krämpfe'],
  'Fingernagel': ['von außen sichtbar','gehört zu den Fingern','wächst, kann man feilen und lackieren','schützt die Fingerkuppen'],
  'Schlüsselbein': ['von außen sichtbar','gehört zum Schultergürtel','es gibt zwei davon','ist "S-förmig"'],
  'Lid': ['von außen sichtbar','gehört zum Auge','es gibt zwei davon','man kann damit blinzeln'],
  'Augenbraue': ['von außen sichtbar','sitzten über dem Auge','es gibt zwei davon','behaarter Halbbogen über den Lidern'],
  'Gebiss': ['von außen teilweise sichtbar','ist im Mund','besteht aus Kiefer und Zähnen','man kann damit essen'],
  'Fußnagel': ['von außen sichtbar','ist an der Spitze der Zehen','wächst, kann man feilen und lackieren','es gibt an jedem Fuß fünf'],

  'Arbeitsplatte': ['Ablage','zur Vorbereitung','große Fläche','zum Abstellen von Küchenutensilien'],
  'Toaster': ['Elektroger','zum Zubereiten von Essen','klein und eckig','zum Rösten von Brot'],
  'Spülmittel': ['Putzutensilie','zum Reinigen','flüssig und farbig','zum Säubern von Geschirr'],
  'Tauchsieder': ['Elektrogerät','zum Erhitzen','mit einer Spirale','zum Erhitzen von Wasser'],
  'Mikrowelle': ['Elektrogerät','zum Zubereiten von Essen','mittelgroß und eckig','zum Aufwärmen von Speisen'],
  'Spülmaschine': ['Elektrogerät','zum Reinigen','mit Griff und Leiste','zum Reinigen von Geschirr'],
  'Flaschenöffner': ['Hilfswerkzeug','zum Entfernen von Verschlüssen','klein und meist oval','zum Entfernen von Kronkorken'],
  'Eieruhr': ['Hilfswerkzeug','zum Kochen oder Backen','zylinderförmig','als Wecker zum Kochen'],
  'Küchenrolle': ['Putzutensilie','zum Reinigen','rechteckig und leicht','zum Aufwischen'],
  'Küchenhandtuch': ['Hilfswerkzeug','zum Reinigen','rechteckig und leicht','zum Abtrocknen'],
  'Gefrierfach': ['Elektrogerät','zur Aufbewahrung','groß und eckig','zum eiskalten Lagern von Lebensmitteln'],
  'Dosenöffner': ['Hilfswerkzeug','zum Entfernen von Verschlüssen','mit scharfem rundem Messer','zum Entfernen von Konservendeckeln'],
  'Schneidebrett': ['Kochutensilie','zur Vorbereitung','aus Holz oder Plastik','zum Zerkleinern von Lebensmitteln'],
  'Messerblock': ['Aufbewahrnungsgerät','zur Aufbewahrung','aus Holz und eckig','zur Aufbewahrung von Messern'],
  'Dunstabzugshaube': ['Elektrogerät','zum Kochen','aus Edelstahl mit Filter','zum Absaugen von Kochdunst'],

  'Island': ['Nordeuropa','südlich des nördlichen Polarkreises','',''],
  'Tunesien': ['Nordafrika','grenzt an Algerien','',''],
  'Malta': ['Südeuropa','liegt im Mittelmeer','',''],
  'Peru': ['Südamerika','grenzt an Brasilien','',''],
  'Bolivien': ['zwischen Zentral-, Nord- und Ostasien','grenzt an Argentinen','',''],
  'Mongolei': ['Südwestafrika','grenzt an China','',''],
  'Namibia': ['Südosteuropa','grenzt an Südafrika','',''],
  'Kroatien': ['Ostafrika','grenzt an Ungarn','',''],
  'Kenia': ['Südamerika','grenzt an Uganda','',''],
  'Ecuador': ['Südasien','grenzt an Kolombien','',''],
  'Nepal': ['Südasien','grenzt an China','',''],
  'Haiti': ['Karibik','grenzt an die Dominikanische Republik','',''],
  'Russland': ['Osteuropa und Asien','grenzt an China','',''],
  'Jamaika': ['Karibik','liegt in der Karibik','',''],
  'Tansania': ['Ostafrika','grenzt an Kenia','',''],

  'Stehlampe': ['steht frei','im Wohnzimmer','wird an- oder ausgeschaltet','beleuchtet den Raum'],
  'Standuhr': ['steht frei oder hängt an der Wand','im Esszimmer oder Wohnzimmer','läutet zur vollen Stunde','zeigt die Zeit an'],
  'Sitzbank': ['hat meist vier Beine','im Esszimmer oder Wohnzimmer','hat mehr als einen Sitzplatz','für mehrere Personen geeignet'],
  'Barhocker': ['hat meist vier Beine','im Esszimmer oder in der Küche','man sitzt darauf','steht meist an einer Theke'],
  'Servierwagen': ['hat Rollen','im Esszimmer oder in der Küche','man kann Dinge darauf stellen','zum Transportieren von Geschirr und Speisen'],
  'Schirmständer': ['steht auf dem Boden','im Flur oder Eingangsbereich','dient zur Aufbewahrung von Dingen','dient zur Aufbewahrung von Regenschirmen'],
  'Raumteiler': ['steht frei im Raum','in allen Zimmern','ähnelt einer Trennwand','trennt ein Zimmer in zwei Bereiche'],
  'Hollywoodschaukel': ['zum Sitzen oder Liegen','steht draußen','hat mehr als ein Sitzplatz','bewegt sich vor und zurück'],
  'Handtuchhalter': ['steht frei oder ist an der Wand befestigt','im Badezimmer','dient zur Ablage','darauf trocknen Handtücher'],
  'Zeitungsständer': ['steht frei oder ist an der Wand befestigt','im Wohnzimmer','dient zur Ablage','dient zur Ablage von Zeitschriften'],
  'Wickelkommode': ['hat meist vier Beine','im Kinderzimmer','hat oben eine Fläche zum Liegen','Babys werden darauf an- und ausgezogen'],
  'Sideboard': ['hat meist vier Beine','in allen Zimmern','dient zur Aufbewahrung von Dingen','Bezeichnung stammt aus dem Englischen'],
  'Schuhschrank': ['steht oder hängt an der Wand','im Flur oder Eingangsbereich','dient zur Aufbewahrung von Dingen','dient zur Lagerung von Sandalen, Stiefeln, etc.'],
  'Stockbett': ['hat meist vier Beine','im Kinderzimmer oder Schlafzimmer','mehrere Personen liegen darin','zwei Schlafstätten übereinander'],
  'Sitzsack': ['liegt auf dem Boden','im Wohnzimmer oder Kinderzimmer','man sitzt darauf','bequemes Sitzmöbelstück ohne Beine'],

  'Saxophon': ['Blasinstrument','aus Metall','Rohr weitet sich zum Ende','stark vertreten im Jazz'],
  'Akkordeon': ['Handzuginstrument','überwiegend aus Holz','hat links eine Tastatur','wird auch "Quetschkomode" genannt'],
  'Tuba': ['Blasinstrument','aus Metall','tiefstes Blechblasinstrument','nach oben gerichteter Schalltrichter'],
  'Triangel': ['Schlaginstrument','aus Stahl','wird mit Stahlstab geschlagen','gleichseitiges Dreieck'],
  'Bratsche': ['Streichinstrument','aus Holz','wird mit Bogen gestrichen','etwas größer als die Geige'],
  'Dudelsack': ['Blasinstrument','überwiegend aus Holz','hat einen Beutel aus Leder oder Kunststoff','wird meist in Schottland gespielt'],
  'Xylophon': ['Schlaginstrument','aus Holz','aneinander gereihte Klangstäbe','wird oft im Kindergarten gespielt'],
  'Waldhorn': ['Blasinstrument','aus Metall','hat kreisförmig gewundenes Rohr','wird zur Jagd geblasen'],
  'Blockflöte': ['Blasinstrument','aus Holz','schmal, lang, mit Löchern','spielen viele Grundschüler'],
  'Tamburin': ['Schlaginstrument','aus Holz und Metall','Rahmentrommel mit Schellen','wird in einer Hand gehalten, mit der anderen geschlagen'],
  'Drehleier': ['Streichinstrument','überwiegend aus Holz','Seiten von innerem Rad gestrichen','Spieler dreht an Kurbel'],
  'Querflöte': ['Blasinstrument','aus Metall','schmal, lang, mit Klappen','wird seitlich gehalten'],
  'Balalaika': ['Zupfinstrument','aus Holz','hat dreieckigen Resonanzkörper','oft in russischer Volksmusik verwendet'],
  'Ukulele': ['Zupfinstrument','aus Holz','exotischer Klang','sehr kleine Gitarre mit 4 Saiten'],
  'Kontrabass': ['Streichinstrument','aus Holz','wird mit Bogen gestrichen','wird im Lied von den drei Chinesen gespielt'],

  'Grapefruit': ['wächst an einem Baum','außen orange und innen rosa','Zitrusfrucht','hat einen bitteren Geschmack'],
  'Kiwi': ['wächst an einer Rebe','außen braun und innen grün','exotische Frucht','hat eine stachelig-haarige Schale'],
  'Granatapfel': ['wächst an einem Baum','rot','exotische Frucht','enthält viele rubinrote Samen'],
  'Heidelbeere': ['wächst an einem Strauch','blau','Beerenobst','färbt Mund und Zähne blau'],
  'Stachelbeere': ['wächst an einem Strauch','grün oder rot','Beerenobst','der Strauch hat stachelige Äste'],
  'Johannisbeere': ['wächst an einem Strauch','schwarz oder rot','Beerenobst','kleine säuerlich schmeckende kugelförmige Früchte'],
  'Zwetschge': ['wächst an einem Baum','lila','Steinobst','wird auch Pflaume genannt'],
  'Mango': ['wächst an einem Baum','innen gelb','exotische Frucht','hat oft faseriges Fruchtfleisch'],
  'Physalis': ['wächst an einem Strauch','orange mit hellbrauner Hülle','heißt auch Blasenkirsche','wird zum Verzieren von Kuchen oder Cocktails benutzt'],
  'Preiselbeere': ['wächst an einem Strauch','rot','Beerenobst','wird oft zu Wildgerichten gegessen'],
  'Mirabelle': ['wächst an einem Baum','gelb','Steinobst','wird oft zu Likör und Marmelade verarbeitet'],
  'Papaya': ['wächst an einem Baum','außen grün und innen orange','exotische Frucht','schmeckt sehr süß'],
  'Litschi': ['wächst an einem Baum','außen rosa-braun und innen weiß','Kernobst','wird oft in thailändischen Gerichten verwendet'],
  'Kokusnuss': ['wächst an einem Baum','außen braun und innen weiß','Steinobst','die darin enthaltene Milch kann man trinken'],
  'Maracuja': ['wächst an einem Baum','außen lila und innen orange','exotische Frucht','wird auch Passionsfrucht genannt'],

  'Eberesche': ['Nutzpflanze','sommergrün','hat gefiederte Blätter','wird auch als Vogelbeere bezeichnet'],
  'Hortensie': ['Zierpflanze','sommergrün','hat große Blüten','Blüten haben farbige oder weiße Kelchblättern'],
  'Zypresse': ['Zierpflanze','immergrün','hat Nadeln','prägt die Kulturlandschaft in der Toskana'],
  'Koriander': ['Nutzpflanze','sommergrün','hat Blätter und kugelförmige Samen','wird als Gewürz oder Heilmittel verwendet'],
  'Hyazinthe': ['Zierpflanze','sommergrün','hat eine Blütentraube aus vielen Einzelblüten','duftet süß'],
  'Geranie': ['Zierpflanze','sommergrün','wächst aufrecht oder hängend','wird meist als Balkonpflanze genutzt'],
  'Schlehe': ['Nutzpflanze','sommergrün','hat bitter schmeckende Früchte','hat weiße Blüten'],
  'Mammutbaum': ['Nutzpflanze','immergrün','hat Nadeln','wird sehr alt und gehört zu den größten Bäumen der Erde'],
  'Oregano': ['Nutzpflanze','sommergrün','hat gegenständig angeordnete Blätter','wird in der mediterranen Küche als Gewürz benutzt'],
  'Ringelblume': ['Nutzpflanze','immergrün','blüht gelb oder orange','wird auch Löwenzahn genannt'],
  'Vergissmeinnicht': ['Zierpflanze','sommergrün','hat blaue bis violettfarbene Blüten','gilt als Symbol der Erinnerung'],
  'Löwenmäulchen': ['Zierpflanze','sommergrün','blüht meist gelb, rot oder violett','Blüten sind weit aufgesperrt'],
  'Brennnessel': ['Nutzpflanze','sommergrün','hat mit Haaren besetzte Blätter und Stängel','Berührung ist schmerzhaft'],
  'Bärlauch': ['Nutzpflanze','sommergrün','ist ein Wildgemüse','riecht nach Knoblauch'],

  'Trinkgeld': ['Finanzen',	'aus Papier oder Metall', 'wenn man zufrieden war', 'erhält der Kellner'],
  'Besteck': ['Inventar',	'aus Silber oder Edelstahl',	'liegt neben dem Teller',	'wird zum Essen benötigt'],
  'Menü': ['Inventar',	'hat mehrere Gänge',	'ist meist günstiger',	'mittags besondere Angebote'],
  'Speisekarte': ['Inventar',	'klein oder umfangreich',	'wird gelesen',	'enthält Speisen und Getränke'],
  'Tresen': ['Inventar',	'man steht daran',	'trennt Personal und Kundschaft',	'auch Schanktisch genannt'],
  'Vorspeise': ['Gang',	'kleine Portion',	'oft Suppe oder Salat',	'erster Gang'],
  'Tischdecke': ['Dekoration',	'aus Stoff oder Papier',	'rund oder eckig',	'schützt den Tisch'],
  'Dessert': ['Gang',	'meist süß',	'manchmal Käseteller',	'letzter Gang'],
  'Aperitif': ['Getränk',	'kalt', 	'oft Prosecco', 	'bei Ankunft im Restaurant'],
  'Hauptgang': ['Gang',	'meist deftig',	'oft Fleisch oder Fisch',	'größter Gang'],
  'Weinkarte': ['Inventar',	'wird gelesen',	'enthält spezielle Getränke',	'Getränke sind rot, weiß oder rosé'],
  'Zapfhahn': ['Inventar',	'befindet sich an der Theke',	'meist an Fass angeschlossen',	'Armatur einer Bierleitung'],
  'Tageskarte': ['Inventar',	'wird gelesen',	'enthält saisonale Gerichte',	'jeden Tag neu'],
  'Reservierung': ['Termin',	'wird im Voraus getätigt',	'per E-Mail oder Telefon',	'Tisch wird damit freigehalten'],
  'Digestif': ['Getränk',	'kalt',	'oft Magenbitter', 'hilfreich nach dem Essen'],

  'Basketball': ['meist in einer Halle',	'in der Gruppe',	'mit zwei Mannschaften',	'Ball wird in Korb geworfen'],
  'Eiskunstlauf': ['meist drinnen',	'alleine oder zu zweit',	'Bewegung zu Musik',	'auf dem Eis'],
  'Marathonlauf': ['meist draußen',	'meist alleine',	'Laufsportart',	'sehr lange Strecke'],
  'Baseball': ['meist draußen',	'in der Gruppe',	'Schlagballspiel',	'Ball wird geschlagen und gefangen'],
  'Volleyball': ['meist in einer Halle',	'in der Gruppe',	'mit zwei Mannschaften',	'Ball wird über ein Netz'],
  'Badminton': ['meist in einer Halle',	'zu zweit',	'mit einem Schläger',	'mit einem Federball'],
  'Joggen': ['meist draußen',	'meist alleine',	'Laufsportart',	'längere Strecke'],
  'Judo': ['meist in einer Halle',	'zu zweit',	'Kampfsportart',	'mit weißem Stoffanzug und Gürtel'],
  'Karate': ['meist in einer Halle',	'zu zweit',	'Kampfsportart',	'mit Schlägen, Tritten und Stößen'],
  'Walken': ['meist draußen',	'meist alleine',	'Laufsportart',	'mit zwei Stöcken'],
  'Squash': ['meist in einer Halle',	'alleine oder zu zweit',	'mit einem Schläger',	'mit einem kleinen Ball gegen in die Wand'],
  'Biathlon': ['meist draußen',	'meist alleine',	'Wintersportart',	'beinhaltet Langlauf und Schießen'],
  'Skisprung': ['meist draußen',	'meist alleine',	'Wintersportart',	'von einer Schanze'],
  'Aerobic': ['meist drinnen',	'in der Gruppe',	'Bewegung zu Musik',	'rhytmische Bewegungen'],
  'Snowboard': ['meist draußen',	'meist alleine',	'Wintersportart',	'mit beiden Füßen auf einem Brett'],

  'Tankstelle': ['hat einen festen Platz',	'Teil einer Straße',	'am Straßenrand zu finden',	'wird aufgesucht wenn das Benzin leer ist'],
  'Ampel': ['hat einen festen Platz',	'sorgt für Sicherheit',	'muss vom Autofahrer beachtet werden',	'leuchtet rot', 'gelb oder grün'],
  'Krankenwagen': ['bewegt sich fort',	'Verkehrsteilnehmer',	'darf im Notfall über Rot fahren',	'wird bei Unfall mit Verletzten gerufen'],
  'Stau': ['hat einen festen Platz',	'verändert den Verkehrsfluss',	'erfordert langsames Fahren',	'passiert häufig bei stockendem Straßenverkehr'],
  'Bushaltestelle': ['hat einen festen Platz',	'Teil einer Straße',	'Anlaufstelle für ein öffentliches Verkehrsmittel',	'wird von Bussen genutzt'],
  'Fußgängerzone': ['hat einen festen Platz',	'Verkehrsfläche',	'darf mit dem Auto nicht befahren werden',	'wird ausschließlich von Menschen genutzt'],
  'Gehweg': ['hat einen festen Platz',	'Verkehrsfläche',	'darf mit dem Auto nicht befahren werden',	'anderes Wort für Bürgersteig'],
  'Bordstein': ['hat einen festen Platz',	'Teil einer Verkehrsfläche',	'Teil des Gehwegs',	'Rand des Gehwegs'],
  'Zebrastreifen': ['hat einen festen Platz',	'sorgt für Sicherheit',	'muss vom Autofahrer beachtet werden',	'zeigt einen Straßenübergang an'],
  'Kreisverkehr': ['hat einen festen Platz',	'Teil des Straßenverlaufs',	'bietet einen runden Straßenverlauf',	'ersetzt eine Kreuzung'],
  'Radweg': ['hat einen festen Platz',	'Verkehrsfläche',	'muss vom Autofahrer beachtet werden',	'ausschließllich für Farhrräder'],
  'Verkehrsschild': ['hat einen festen Platz',	'sorgt für Sicherheit',	'muss vom Autofahrer beachtet werden',	'zeigt z.B. die erlaubte Geschwindigkeit an'],
  'Leitplanke': ['hat einen festen Platz',	'sorgt für Sicherheit',	'Schutz aus Stahl',	'hindert ein Fahrzeug daran, von der Straße abzukommen'],
  'Blitzer': ['hat einen festen Platz',	'sorgt für Sicherheit',	'überwacht die Einhaltung der Geschwindigkeit',	'anderes Wort für Radarfalle'],
  'Mittelstreifen': ['hat einen festen Platz',	'Teil einer Straße',	'trennt Fahrbahnen',	'meist begrünte Trennung des Verkehrsstroms'],

  'Nudeln': ['Nahrungsmittel', 	'bei Grundnahrungsmitteln',	'gelb',	'aus Getreide'],
  'Kaugummi': ['Nahrungsmittel', 	'oft an der Kasse',	'meist weiß',	'wird lange gekaut'],
  'Leberwurst': ['Nahrungsmittel', 	'Fleischtheke',	'rosa oder braun',	'kalbsfleischhaltiger Brotaufstrich'],
  'Eierlikör': ['Nahrungsmittel', 	'Getränkeabteilung',	'gelb und dickflüssig',	'aus Alkohol, Zucker und Eiern'],
  'Heidelbeeren': ['Nahrungsmittel', 	'Obstabteilung',	'dunkelblau',	'wachsen an Sträuchern'],
  'Pizza': ['Nahrungsmittel', 	'Tiefkühltruhe',	'rund und flach',	'italienische Teigwarenspezialität'],
  'Apfelwein': ['Nahrungsmittel', 	'Getränkeabteilung',	'gelb',	'Alkohol aus Äpfeln'],
  'Mettwurst': ['Nahrungsmittel', 	'Fleischtheke',	'rotbraun',	'aus rohem Schweine- und Rindfleisch'],
  'Klopapier': ['kein Nahrungsmittel', 	'Haushaltswarenabteilung',	'meist weiß',	'aus bis zu fünf Papierlagen'],
  'Spülmittel': ['kein Nahrungsmittel', 	'Haushaltswarenabteilung',	'gelb, grün, blau oder weiß',	'aus Zitronensäure und Alkohol zum Abwaschen'],
  'Shampoo': ['kein Nahrungsmittel', 	'Kosmetikabteilung',	'meist weiß und duftend',	'aus flüssiger Masse für die Haare'],
  'Eiskaffee': ['Nahrungsmittel', 	'Getränkeabteilung',	'meist braun',	'Kaltgetränk, zuvor aus Bohnen aufgebrüht'],
  'Geschenkpapier': ['kein Nahrungsmittel', 	'Schreibwarenabteilung',	'aus Papier',	'zum Einpacken von Überraschungen'],
  'Rasierer': ['kein Nahrungsmittel', 	'Kosmetikabteilung',	'bunt und länglich',	'aus Klingen und Stiel'],
  'Eistee': ['Nahrungsmittel', 	'Getränkeabteilung',	'meist braun',	'Kaltgetränk, zuvor aus Blättern aufgegossen'],

  'Schildkröte': ['kein Säugetier',	'Wildtier',	'hat einen Panzer',	'wird sehr alt'],
  'Krokodil': ['kein Säugetier',	'Wildtier',	'hat einen Panzer',	'hat scharfe Zähne'],
  'Meerschweinchen': ['Säugetier',	'Haustier',	'hat Fell',	'tagaktives Nagetier'],
  'Leopard': ['Säugetier',	'Wildtier',	'hat Fell',	'ist sehr schnell'],
  'Jaguar': ['Säugetier',	'Wildtier',	'hat Fell',	'ist auch Symbol einer Automarke'],
  'Wiesel': ['Säugetier',	'Wildtier',	'hat Fell',	'ist flink'],
  'Luchs': ['Säugetier',	'Wildtier',	'hat Fell',	'gehört zur Familie der Wildkatzen'],
  'Hamster': ['Säugetier',	'Haustier',	'hat Fell',	'rennt nachts im Rad'],
  'Lama': ['Säugetier',	'Nutztier',	'hat Fell',	'spuckt'],
  'Otter': ['Säugetier',	'Wildtier',	'hat Fell',	'isst gerne Fisch'],
  'Elch': ['Säugetier',	'Wildtier',	'hat Fell',	'hat ein Geweih und röhrt'],
  'Robbe': ['Säugetier',	'Wildtier',	'hat Fell',	'Kinder werden Heuler genannt'],
  'Pinguin': ['kein Säugetier',	'Wildtier',	'hat Federn',	'ist schwarz und weiß'],
  'Alpaka': ['Säugetier',	'Nutztier',	'hat Fell',	'gehört zur Familie der Kamele'],
  'Delfin': ['Säugetier',	'Wildtier',	'hat eine glatte Haut',	'ist stromlinienförmig und sehr intelligent'],

  'Zollstock': ['lang',	'aus Holz, Kuststoff oder Metall',	'hat miteinander verbundene gerade Holzteile',	'benötigt man um etwas zu messen'],
  'Kreissäge': ['groß',	'aus Metall',	'hat eine gezackte, runde Schneideplatte',	'benötigt man um Holz und Metall zu zerkleinern'],
  'Dübel': ['klein',	'aus Plastik oder Holz',	'hat eine spitz zulaufende Form',	'benötigt man als Halterung für Schrauben'],
  'Wasserwaage': ['lang',	'aus Holz, Kunststoff und Metall',	'hat eine längliche, rechteckige Form',	'benötigt man um etwas gerade anzubringen'],
  'Bohrmaschine': ['mittelgroß',	'aus Metall und Kunststoff',	'hat ein Gewinde für Aufsätze',	'benötigt man um tiefe Löcher in einer Wand herzustellen'],
  'Lötkolben': ['mittelgroß',	'aus Metall und Kunststoff',	'hat eine stiftartige Form',	'benötigt man um Metalle aufzuschmelzen'],
  'Kabeltrommel': ['mittelgroß',	'aus Kunststoff und Metall',	'hat eine runde Form',	'benötigt man um eine Kunststoffschnur aufzurollen'],
  'Drahtbürste': ['mittelgroß',	'aus Holz und Metall',	'hat einen Holzgriff mit Borsten',	'benötigt man zum Reinigen von Flaschen'],
  'Winkelmesser': ['mittelgroß',	'aus Metall oder Plastik',	'hat eine Maßstabangabe',	'benötigt man für das Ausmessen von Ecken'],
  'Verlängerungskabel': ['lang',	'aus Kunststoff und Metall',	'hat einen Stecker und eine Kupplung',	'benötigt man um Strom zu verlegen'],
  'Motorsäge': ['groß',	'aus Metall',	'hat eine lange und gezackte Spitze',	'benötigt man um Holz zu schneiden'],
  'Handbohrer': ['mittelgroß',	'aus Metall',	'hat einen Seitengriff',	'benötigt man um ohne Strom Löcher herzustellen'],
  'Schweißgerät': ['groß',	'aus Metall und Kunststoff',	'hat einen viereckigen Kasten',	'benötigt man um Dinge mittels Wärme zu verbinden'],
  'Schleifpapier': ['mittelgroß',	'aus Papier und Kunststoff',	'hat eine Körnung',	'benötigt man um eine raue Fläche zu glätten'],
  'Lüsterklemme': ['klein',	'aus Kunststoff und Metall',	'hat Klemmschrauben',	'benötigt man um eine Lampe am Strom anzuschließen']
};

final Map nfAutoteileMAP = {
  'Scheibenwischer': ['direkt sichtbar','Metall mit Gummi','vorne zwei und hinten einer','zum Säubern der Front- oder Heckscheibe bei Regen'],
  'Auspuff': ['direkt sichtbar','Metall','hinten unten','leitet die Abgase nach außen'],
  'Stoßstange': ['direkt sichtbar','Stahl mit Kunststoffhaut','an Front und Heck','minimiert von Unfallschäden'],
  'Klimaanlage': ['nicht direkt sichtbar','Metall','im Motorraum mit Verbindung zum Innenraum','sorgt für angenehme Temperatur und klare Scheiben'],
  'Tachometer': ['direkt sichtbar','Metall','vor dem Fahrer','zeigt die aktuelle Geschwindigkeit an'],
  'Gangschaltung': ['direkt sichtbar','Metall mit Kunststoff oder Leder','rechts vom Fahrer','zur Bedienung des Getriebes mit der Hand'],
  'Bremspedal': ['direkt sichtbar','Metall','im Fußraum des Fahrers','wird beim Starten des Autos getreten'],
  'Handschuhfach': ['direkt sichtbar','Kunststoff','vor dem Beifahrer','zum Transport kleinerer Gegenstände'],
  'Zündkerze': ['nicht direkt sichtbar','Metall und Keramik','im Motorraum','erzeugt einen Funken zum Anlassen des Autos'],
  'Wagenheber': ['nicht direkt sichtbar','Metall','im Kofferraum','wird beim Reifenwechsel zum Hochbewegen des Autos benötigt'],
  'Rückbank': ['direkt sichtbar','Stoff oder Leder','hinter den Vordersitzen','hier sitzen meistens Kinder'],
  'Autotür': ['direkt sichtbar','Metall mit (Kunst-)Stoff oder Leder','vorne und hinten je zwei','muss zum Einsteigen geöffnet werden'],
  'Sicherheitsgurt': ['direkt sichtbar','Nylongewebe mit Metallzunge','vorne und hinten je zwei','Rückhaltesystem zur Sicherheit der Personen im Auto'],
  'Heckscheibe': ['direkt sichtbar','Glas','hinten','ermöglicht die Sicht aus dem Auto nach hinten'],
  'Benzintank': ['nicht direkt sichtbar','Aluminium, Stahl oder Kunststoff','über Hinterachse oder davor unter Rücksitzen','enthält den Kraftstoff'],
  'Schiebedach': ['direkt sichtbar','Glas','oben','Öffnungssystem nach oben'],
  'Kopfstütze': ['direkt sichtbar','Metall mit Stoff oder Leder','eine an jedem Sitz','zum Schutz der Halswirbelsäule bei Unfällen']
};


final Map nfBadezimmerMAP = {
  'Nagellack': ['erweiterte Ausstattung','ein Kosmetikprodukt','farbliche Nagelgestaltung','meist rot oder rosa'],
  'Nagelschere': ['erweiterte Ausstattung','aus Metall','zum Schneiden','für Finger- und Fußnägel'],
  'Shampoo': ['erweiterte Ausstattung','eine Art Creme','für die Haare','zum Waschen'],
  'Duschkabine': ['Grundausstattung','meist aus Glas','grenzt eine Brause von der Umgebung ab','mit Tür zum Öffnen und Schließen'],
  'Fliese': ['Grundausstattung','aus Stein oder Marmor','meist viereckig','Bodenbelag'],
  'Handtuchhalter': ['erweiterte Ausstattung','aus Plastik oder Metall','zum Aufhängen','für Handtücher'],
  'Duschvorhang': ['erweiterte Ausstattung','meist aus Stoff','grenzt eine Brause von der Umgebung ab','zum Hin- und Herschieben'],
  'Zahnseide': ['erweiterte Ausstattung','aus Kunststoff oder textiler Faser','zum Reinigen von Zwischenräumen im Mund','gewachst und ungewachst'],
  'Badezimmerschrank': ['Grundausstattung','meist aus Holz','zur Aufbewahrung','für Badezimmerartikel'],
  'Klobürste': ['erweiterte Ausstattung','meist aus Plastik','hat einen langen Stiel und Borsten','zum Reinigen der Toilette'],
  'Zahnputzbecher': ['erweiterte Ausstattung','meist aus Plastik','zum Mund ausspülen','Zahnbürste steht meist darin'],
  'Duschgel': ['erweiterte Ausstattung','eine Art Creme','für den Körper','zum Waschen'],
  'Badematte': ['erweiterte Ausstattung','meist aus Stoff','meist viereckig','Bodenbelag'],
  'Duschhaube': ['erweiterte Ausstattung','meist aus Plastik','für die Haare','Haare bleiben damit trocken'],
  'Duschkopf': ['Grundausstattung','meist aus Metall','Wasser kommt da raus','zum Abbrausen']
};

final Map nfBauernhofMAP = {
  'Huhn': ['Tier','häufig braun oder weiß','Schnabel und Federn','legt Eier'],
  'Scheune': ['Gebäude','groß und mit Holzbalken','dient als Lagerraum','für Stroh, Getreide und Fahrzeuge'],
  'Spaten': ['Gartenwerkzeug','zum Graben','drückt man mit dem Fuß in die Erde','große eckige Schaufel'],
  'Teich': ['Gewässer','für Fische und Enten','mit Süßwasser','kleiner als ein See'],
  'Schaf': ['Tier','häufig weiß','dickes Fell','wird zu Wolle verarbeitet'],
  'Kartoffel': ['Nahrungsmittel','Gemüse','außen braun und innen gelb','wird auch Erdapfel genannt'],
  'Ziege': ['Tier','weiß, braun oder schwarz','hat Hörner','aus der Milch wird Käse hergestellt'],
  'Beet': ['kleines Stück Boden','häufig grün und bunt','zieht landwirtschaftliche Geräte','mit Blumen, Kräutern oder Gemüse'],
  'Traktor': ['Fahrzeug','für das Feld geeignet','im Garten oder vor dem Haus','parkt in der Scheune '],
  'Rechen': ['Gartenwerkzeug','für Laub auf der Wiese','häufig Holzstiel mit Metallstäben','zum Kehren'],
  'Hundehütte': ['Gebäude','häufig aus Holz und Metall','Schlafplatz für ein Tier','der Hund lebt darin'],
  'Gummistiefel': ['Kleidungsstück','für die Füße','aus Kunststoff','wird bei Matsch und Regen getragen'],
  'Milchkanne': ['Gefäß','it Henkel','beinhaltet Flüssigkeit','von Kühen oder Ziegen'],
  'Mistgabel': ['Gartenwerkzeug','mit Holzstiel','hat drei Zinken','zum Säubern der Ställe'],
  'Latzhose': ['Kleidungsstück','Arbeitskleidung','hat zwei Träger','spezielle Form einer Hose ']
};


final Map nfBerufeMAP = {
  'Therapeut': ['arbeitet viel mit Menschen','erfordert ein Studium/eine Ausbildung','erfragt die Vorgeschichte des Patienten','führt eine Therapie mit Patienten durch'],
  'Fotograf': ['arbeitet viel mit Materialien','erfordert ein Studium/eine Ausbildung','benötigt eine Kamera','macht Bilder von Personen oder Ojekten'],
  'Kassierer': ['arbeitet viel mit Menschen','ohne Ausbildung möglich','nimmt Geld entgegen','tippt Preise in eine Kasse ein'],
  'Uhrmacher': ['arbeitet viel mit Materialien','erfordert eine Ausbildung','stellt Zeitmessgeräte her','repariert Uhren'],
  'Klempner': ['arbeitet viel mit Materialien','erfordert eine Ausbildung','bearbeitet Gegenstände aus Metall','wird bei einem verstopften Abfluss gerufen'],
  'Elektriker': ['arbeitet viel mit Materialien','erfordert eine Ausbildung','misst Spannung und Widerstand','repariert elektrische Anlagen'],
  'Bademeister': ['arbeitet viel mit Menschen','erfordert eine Ausbildung','überwacht den Betrieb eines Schwimmbads','rettet Menschen aus dem Wasser'],
  'Informatiker': ['arbeitet viel mit Materialien','erfordert ein Studium/eine Ausbildung','arbeitet am Computer','programmiert eine Software oder Internetseite'],
  'Masseur': ['arbeitet viel mit Menschen','erfordert eine Ausbildung','führt Bewegungen mit Händen aus','löst Verspannungen am Körper des Klienten'],
  'Dachdecker': ['arbeitet viel mit Materialien','erfordert eine Ausbildung','bringt Dämmstoff an Gebäuden an','deckt Dächer mit Ziegeln'],
  'Konditor': ['arbeitet viel mit Materialien','erfordert eine Ausbildung','backt für spezielle Anlässe','backt Torten'],
  'Tierpfleger': ['arbeitet viel mit Menschen','erfordert eine Ausbildung','füttert und pflegt Lebewesen','kümmert sich um Vier- und Zweibeiner'],
  'Flugbegleiter': ['arbeitet viel mit Menschen','erfordert eine Ausbildung','fliegt in andere Länder','kümmert sich um Passagiere in einem Flugzeug'],
  'Hotelkaufmann': ['arbeitet viel mit Materialien','erfordert eine Ausbildung','gibt Zimmerschlüssel an Gäste aus','arbeitet in der Rezeption in einem Hotel'],
  'Müllmann': ['arbeitet viel mit Materialien','erfordert eine Ausbildung','entsorgt Abfälle','leert Mülltonnen']
};


final Map nfDeutscheStaedteMAP = {
  'Lübeck': ['Schleswig-Holstein','Hansestadt','Marzipan','Holstentor'],
  'Regensburg': ['Bayern','in der Oberpfalz','Donau-Schifffahrtsmuseum','Steinerne Brücke'],
  'Tübingen': ['Baden-Württemberg','klassische Universitätsstadt','Paul-Horn-Arena','Stiftskirche'],
  'Aachen': ['Nordrhein-Westfalen','Kurstadt','Karl der Große','Printen'],
  'Mannheim': ['Baden-Württemberg','ehemalige Residenzstadt der Kurpfalz','Wasserturm','Quadratestadt'],
  'Trier': ['Rheinland-Pfalz','älteste Stadt Deutschlands','Karl-Marx-Haus','Porta Nigra'],
  'Dortmund': ['Nordrhein-Westfalen','bevölkerungsreichste Stadt im Ruhrgebiet','das "U"','Borussia'],
  'Koblenz': ['Rheinland-Pfalz','im Norden von Rheinland-Pfalz','Festung Ehrenbreitstein','Deutsches Eck'],
  'Ulm': ['Baden-Württemberg','im Südosten der Schwäbischen Alb','Münster','Spatz'],
  'Chemnitz': ['Sachsen','im Südwesten von Sachsen','Siegertsches Haus','Roter Turm'],
  'Erlangen': ['Bayern','in Mittelfranken','Botanischer Garten','Hugenottenkirche'],
  'Bochum': ['Nordrhein-Westfalen','Zentrum des mittleren Ruhrgebiets','Zeiss Planetarium','Deutsches Bergbau-Museum'],
  'Ludwigshafen': ['Rheinland-Pfalz','größte Stadt der Pfalz','Wilhelm-Hack-Museum','BASF'],
  'Solingen': ['Nordrhein-Westfalen','im Bergischen Land','Schloss Burg','Zwilling-Messer'],
  'Idstein': ['Hessen','Rheingau-Taunus-Kreis','Hexenturm','Sitz der Hochschule Fresenius']
};


final Map nfFahrzeugeMAP = {
  'Tandem': ['fährt auf Rädern','durch Muskelkraft betrieben','transportiert höchstens zwei Personen','Fahrrad für zwei Personen'],
  'Motorroller': ['fährt auf Rädern','durch Motor betrieben','transportiert höchstens zwei Personen','hat ein Trittbrett statt Fußrasten'],
  'Gabelstapler': ['fährt auf Rädern','durch Motor betrieben','Arbeitsfahrzeug','transportiert Paletten'],
  'Cabriolet': ['fährt auf Rädern','durch Motor betrieben','transportiert mehrere Personen','kann das Dach öffnen'],
  'Hundeschlitten': ['fährt auf Kufen','durch Muskelkraft betrieben','transportiert höchstens Personen oder Fracht','wird von Tieren über den Schnee gezogen'],
  'Dreirad': ['fährt auf Rädern','durch Muskelkraft betrieben','transportiert eine Person','Tretfahrzeug für kleine Kinder'],
  'Dampfwalze': ['fährt auf Rollen','durch Motor betrieben','Arbeitsfahrzeug','wird zum Verdichten der Straßendecke genutzt'],
  'Mofa': ['fährt auf Rädern','durch Motor betrieben','transportiert höchstens zwei Personen','motorisiertes Fahrrad'],
  'Polizeiauto': ['fährt auf Rädern','durch Motor betrieben','Arbeitsfahrzeug','fährt oft mit Blaulicht'],
  'Feuerwehrauto': ['fährt auf Rädern','durch Motor betrieben','Arbeitsfahrzeug','löscht Flammen'],
  'Dampflokomotive': ['fährt auf Schienen','durch Motor betrieben','transportiert viele Personen','wird von Wasserdampf angetrieben'],
  'Bollerwagen': ['fährt auf Rädern','durch Muskelkraft betrieben','transportiert kleine Kinder oder Gegenstände','muss gezogen werden'],
  'Einrad': ['fährt auf Rädern','durch Muskelkraft betrieben','transportiert eine Person','hat einen Sattel und nur einen Reifen'],
  'Abschleppwagen': ['fährt auf Rädern','durch Motor betrieben','Arbeitsfahrzeug','transportiert andere Fahrzeuge'],
  'Seifenkiste': ['fährt auf Rädern','durch Hangabtriebskraft bewegt','transportiert höchstens zwei Personen','ist oft selbstgebaut']
};


final Map nfGartenMAP = {
  'Liegestuhl': ['Gegenstand','aus Holz oder Kunststoff','zum Ausruhen in der Waagerechten','zum Zusammenklappen'],
  'Sonnenschirm': ['Gegenstand','aus Stoff und Metall','groß und mit einer Stange und Stoff','spendet Schatten'],
  'Grill': ['Gegenstand','aus Metall','zum Erhitzen','zum Essen zubereiten'],
  'Gießkanne': ['Gegenstand','aus Kunststoff oder Metall','mit siebartigem Aufsatz','zum Pflanzen bewässern'],
  'Hängematte': ['Gegenstand','aus Stoff','zum Liegen','zum Schaukeln'],
  'Sandkasten': ['Gegenstand','aus Holz','großer und meist eckig','Kinder bauen darin Burgen'],
  'Harke': ['Gegenstand','aus Metall und Holz','für die Gartenarbeit','zum Lockern der Erde'],
  'Rechen': ['Gegenstand','aus Metall und Holz','für die Gartenarbeit','zum Laub zusammen kehren'],
  'Regentonne': ['Gegenstand','aus Kunststoff','groß, rund und innen hohl','zum Wasser sammeln'],
  'Rasenmäher': ['Gegenstand','aus Kunststoff und Metall','großer und verursacht Lärm','zum Gras kürzen'],
  'Vogelhaus': ['Gegenstand','aus Holz','besitzt ein Dach','Futterstelle für fliegende Tiere'],
  'Rutsche': ['Gegenstand','aus Kunststoff oder Metall','groß mit schiefer Ebene','Kinder gleiten beim Spielen herunter'],
  'Wasserschlauch': ['Gegenstand','aus Kunststoff oder Gummi','langer und innen hohl','Wasser wird darin transportiert'],
  'Setzling': ['Pflanze','grün','klein','junger Pflanzenableger'],
  'Blumenerde': ['Pflanze','dunkelbraun','feinkörniges Gemisch','für Zierpflanzen geeigneter Nährboden']
};


final Map nfGemueseMAP = {
  'Rhabarber': ['wächst am Boden','meist rot','wird geschält und zubereitet','wird oft zu Kompott verarbeitet'],
  'Rosenkohl': ['wächst auf dem Feld','grün und rund','vor dem Kochen werden die äußeren Blätter entfernt','wird meist als Beilage serviert'],
  'Weißkohl': ['wächst auf dem Feld','weiß oder hellgrün','wird geschnitten und gekocht','eine Form von Kohl'],
  'Ingwer': ['wächst in der Erde','braun und gelb','wird geschnitten und gekocht','wird oft als Gewürz verwendet'],
  'Rotkohl': ['wächst auf dem Feld','rot','wird geschnitten und gekocht','wird im Winter oft als Beilage serviert'],
  'Grünkohl': ['wächst auf dem Feld','grün','wird geschnitten und gekocht','eine Form von Kohl'],
  'Artischocke': ['wächst auf dem Feld','grün','wird gewaschen und der holzige Stiel entfernt','sieht aus wie eine Blume'],
  'Lauch': ['wächst auf dem Feld','grün und weiß','wird geputzt und geschnitten','gibt es als Stange zu kaufene'],
  'Wirsing': ['wächst auf dem Feld','grün','wird gewaschen und die Blätter abgetrennt','wird im Winter oft als Beilage serviert'],
  'Karotte': ['wächst auf dem Feld','orange','wird oft geschält und geschnitten','wird roh oder gekocht gegessen'],
  'Brokkoli': ['wächst auf dem Feld','grün','wird geputzt und die Röschen abgetrennt','eine Form von Kohl'],
  'Aubergine': ['wächst am Strauch','violett','wird geputzt und gekocht','wird auch Eierfrucht genannt'],
  'Peperoni': ['wächst am Strauch','rot oder grün','wird gewaschen und die Kerne entfernt','meist sehr scharf'],
  'Süßkartoffel': ['wächst in der Erde','rot oder orange','wird geschält und gekocht','eine Form der Knollenpflanze'],
  'Zucchini': ['wächst auf dem Feld','grün','wird gewaschen und geschnitten','sieht einer Gurke ähnlich']
};


final Map nfGetraenkeMAP = {
  'Orangensaft': ['ohne Alkohol','orange','wird durch Pressen einer Frucht gewonnen','schmeckt süß und wird gerne zum Frühstück getrunken'],
  'Apfelsaft': ['ohne Alkohol','häufig hellgelb','wird durch Pressen einer Frucht gewonnen','schmeckt süß und wird gerne von Kindern getrunken'],
  'Glühwein': ['mit Alkohol','häufig rot','wird heiß serviert','wird auf dem Weihnachtsmarkt getrunken'],
  'Apfelwein': ['mit Alkohol','häufig hellgelb','wird aus einer Frucht gewonnen','wird meistens mit Wasser gespritzt'],
  'Tomatensaft': ['ohne Alkohol','rot','wird aus einem Gemüse hergestellt','wird gerne im Flugzeug getrunken'],
  'Radler': ['mit Alkohol','hellgelb','wird gerne im Sommer getrunken','besteht aus Bier und Limonade'],
  'Fanta': ['ohne Alkohol','gelb','wird künstlich hergestellt','süßes Getränk der Coca-Cola-Company'],
  'Kirschsaft': ['ohne Alkohol','dunkelrot','wird häufig aus sauren Früchten gewonnen','wird mit Wasser verdünnt und gesüßt'],
  'Whiskey': ['mit Alkohol','häufig golden','wird durch Destillation von Getreide gewonnen','wird oft aus einem Glas mit dickem Glasboden getrunken'],
  'Ananassaft': ['ohne Alkohol','hellgelb','wird aus einer Frucht gemacht','schmeckt süß und wird oft in Cocktails verwendet'],
  'Karottensaft': ['ohne Alkohol','orange','wird aus einem Gemüse hergestellt','eher dickflüssig, mit viel Vitamin A'],
  'Eistee': ['ohne Alkohol','häufig dunkelbraun','wird heiß hergestellt und schnell abgehült','meist Schwarztee mit Zitronensaft'],
  'Bowle': ['mit Alkohol','unterschiedliche Farben','wird mit Sekt gemacht','wird meist mit Fruchtstücken serviert'],
  'Hefeweizen': ['mit Alkohol','gelb','wird aus einem Getreide hergestellt','wird aus einem speziellen hohen Glas getrunken'],
  'Cappuccino': ['ohne Alkohol','braun und weiß','enthält Koffein','Espresso mit heißer Milch und Milchschaum']
};


final Map nfHauptstaedteMAP = {
  'Helsinki': ['Nordeuropa','Finnland','Dom','Senatsplatz'],
  'Tokio': ['Ostasien','Japan','Senso-ji-Tempel','Meiji-Schrein'],
  'Lissabon': ['dwesteuropa','Portugal','Torre de Belém','Castelo de São Jorge'],
  'Ankara': ['Vorderasien','Türkei','Kocatepe-Moschee','Anıtkabir'],
  'Oslo': ['Nordeuropa','Norwegen','Festung Akershus','Fjord'],
  'Kiew': ['Osteuropa','Ukraine','Sophienkathedrale','Höhlenkloster'],
  'Teheran': ['Naher Osten','Iran','Golestanpalast','Freiheitsturm'],
  'Bagdad': ['Naher Osten','Irak','al-Schahid-Monument','Al-Jawadain Schrein'],
  'Dublin': ['Westeuropa','Irland','Trinity College','Temple Bar'],
  'Hanoi': ['Südostasien','Vietnam','Hanoi Hilton','Ho Chi Minh-Mausoleum'],
  'Havanna': ['Große Antillen','Kuba','Uferpromenade Malécon','Altstadt La Habana Viejo'],
  'Bangkok': ['Südostasien','Thailand','Großer Palast','Wat Arun'],
  'Ottawa': ['Nordamerika','Kanada','Rideau Canal','Parlamentshügel'],
  'Nairobi': ['Ostafrika','Kenia','Karen Blixen Museum','Nationalpark'],
  'NeuDelhi': ['Südasien','Indien','Qutb Minar','Rotes Fort']
};


final Map nfHausbauMAP = {
  'Kran': ['Fahrzeug','zum Verladen von Lasten','Turm mit Drehwerk','Hebehilfe für sehr schwere Güter'],
  'Bagger': ['Fahrzeug','hat einen Greifarm mit großer Schaufel','löst und bewegt Boden und Felsen','Fahrzug zum Aushuben der Baugrube'],
  'Polier': ['Beruf','erfordert eine Ausbildung','Bindeglied zwischen Bauarbeitern und Bauleitung','Leiter einer Baustelle oder eines Baustellenabschnittes'],
  'Rohbau': ['Gebäudezustand','erster Bauabschnitt','wird mit dem Richtfest gefeiert','Bauwerk mit Dachkonstruktion ohne Fenster und Türen'],
  'Dachdecker': ['Beruf','erfordert eine Ausbildung','arbeitet häufig in der Höhe','führt Dach- und Abdichtungsarbeiten aus'],
  'Schubkarre': ['Hilfsmittel','hat Wanne und Rad','zum Transport von Baumaterialien','wird von einem Arbeiter geschoben'],
  'Installateur': ['Beruf','erfordert eine Ausbildung','kümmert sich un technische Anlagen','zuständig für Sanitäts-, Heizungs- und Klimatechnik'],
  'Schutzbrille': ['Schutzausrüstung','aus weichem oder hartem Kunststoff','Schutz vor Staub und Splittern','schützt die Augen'],
  'Wasserwaage': ['Messgerät','aus Holz, Aluminium oder Kunststoff','längliche Form','Prüfgerät zur Ausrichtung mittels Flüssigkeit'],
  'Bohrmaschine': ['Werkzeug','elektrisch betrieben','wechselbare Aufsätze','wird verwendet, um Löcher zu erstellen'],
  'Bauzeichnung': ['Hilfsmittel','grafische Darstellung','zeigt räumliche Ausmaße','enthält wichtige Informationen für die Bauausführung'],
  'Stichsäge': ['Werkzeug','aus Holz und Metall','handgeführt oder elektronisch','zum Schneiden von Ausschnitten oder Erweitern von Öffnungen'],
  'Gerüstbauer': ['Beruf','erfordert eine Ausbildung','arbeitet häufig in der Höhe','errichtet Flächen für die Arbeit an der Außenwand'],
  'Gehörschutz': ['Schutzausrüstung','aus Kunststoff','gibt es als Kapseln oder Stöpsel','schützt vor lauten Geräuschen'],
  'Abdeckfolie': ['Material','aus Kunststoff','wird großflächig ausgelegt','schützt vor Verschmutzung']
};

final Map nfHobbysMAP = {
  'Einkaufen': ['drinnen','Selbstversorgung','Obst, Gemüse, Kleidung','bei REWE, Edeka, Kaufhof'],
  'Nähen': ['drinnen','Handarbeit','mit Nadel und Faden','Tischdecken, Kleider, Anzüge'],
  'Wintersport': ['häufig draußen','körperliche Aktivität','im Winter','Ski, Snowboard, Schlitten'],
  'Disco': ['drinnen','Nachtleben','Bewegung zu lauter Musik','im Club'],
  'Basteln': ['drinnen','Handarbeit','mit Schere, Papier und Kleber','Geburtstagskarten, Weihnachtsschmuck'],
  'Kreuzworträtsel': ['drinnen und draußen','Denksport','mit Stift auf Papier','Wörter raten in Zeitungen'],
  'Häkeln': ['drinnen','Handarbeit','Maschen aus Wolle','Mützen, Topflappen und Schal'],
  'Camping': ['draußen','Urlaub und Ferien','Übernachtungsmöglichkeit','Wohnwagen, Zelt, Wohnmobil'],
  'Jodeln': ['drinnen und draußen','stimmliche Aktivität','ohne Instrumente','Singen mit Silben und ohne Text'],
  'Töpfern': ['drinnen','Handarbeit','Keramikherstellung','Vasen, Schalen, Krüge'],
  'Kampfsport': ['eher drinnen','körperliche Aktivität','Zweikampf','Judo, Karate und Boxen'],
  'Fitness': ['drinnen und draußen','Ausdauer und Kraft','Sportstudio','Laufband, Crosstrainer und Joggen'],
  'Modelleisenbahn': ['drinnen','Modellbau','Gleise, Landschaft und Züge','Märklin, Buco'],
  'Aerobic': ['eher drinnen','körperliche Aktivität','mit Musik, Fitnesstraining in der Gruppe','klassische Gymnasik mit Tanz'],
  'Heimwerken': ['eher drinnen','Haus und Garten','mit Maschinen und Werkzeug','Gartenhütte, Hausbau']
};

final Map nfKleidungMAP = {
  'Unterhemd': ['wird von Männern und Frauen getragen','wird am Oberkörper getragen','hat keine Ärmel','gehört zur Unterwäsche'],
  'Dirndl': ['wird meist von Frauen getragen','wird am ganzen Körper getragen','ist ein spezielles Kleid','ist eine Tracht aus Bayern'],
  'BH': ['wird meist von Frauen getragen','wird am Oberkörper getragen','hat zwei Körbchen','stützt und formt die Brust'],
  'Gummistiefel': ['wird von Männern und Frauen getragen','wird an den Füßen getragen','ist aus Kunststoff','wird bei Regen getragen'],
  'Anorak': ['wird von Männern und Frauen getragen','wird am Oberkörper getragen','hat zwei lange Ärmel und ist wetterfest','ist eine Jacke mit Kapuze'],
  'Blazer': ['wird von Männern und Frauen getragen','wird am Oberkörper getragen','hat zwei lange Ärmel und einen Kragen','wird häufig über einer Bluse getragen'],
  'Strumpfhose': ['wird meist von Frauen getragen','wird am Unterkörper getragen','ist eng anliegend und unten geschlossen','ist eine Verbindung aus Unterhose und Strümpfen'],
  'Hausschuh': ['wird von Männern und Frauen getragen','wird an den Füßen getragen','ist bequem und hat meist keinen Absatz','wird meist im Haus getragen'],
  'Latzhose': ['wird von Männern und Frauen getragen','wird am ganzen Körper getragen','ist meist eine Arbeitskleidung','wird am Oberkörper mit Hosenträgern gehalten'],
  'Poncho': ['wird von Männern und Frauen getragen','wird am Oberkörper getragen','ist ein rechteckig und hat ein Loch in der Mitte','ist ein Umhang der Indios'],
  'Korsage': ['wird meist von Frauen getragen','wird am Oberkörper getragen','ist eng anliegend','wird geschnürt und macht schlank'],
  'Turnschuh': ['wird von Männern und Frauen getragen','wird an den Füßen getragen','ist bequem und wird geschnürt','wird beim Sport oder in der Freizeit getragen'],
  'Leggings': ['wird meist von Frauen getragen','wird am Unterkörper getragen','ist eng anliegend und unten offen','ist eine Hose'],
  'Jogginghose': ['wird von Männern und Frauen getragen','wird am Unterkörper getragen','ist bequem und am Bund elastisch','wird beim Laufen oder in der Freizeit getragen'],
  'Pullunder': ['wird von Männern und Frauen getragen','wird am Oberkörper getragen','hat keine Ärmel','ist ein ärmelloser Pullover']
};


final Map nfKoerperteileMAP = {
  'Ellenbogen': ['von außen sichtbar','gehört zum Arm','Verbindung zwischen Ober- und Unterarm','man kann sich darauf abstützen'],
  'Wirbelsäule': ['von außen nicht sichtbar','gehört zum Rücken','besteht aus knöchernen Elementen','Bandscheiben verbinden die Wirbel miteinander'],
  'Handgelenk': ['von außen sichtbar','gehört zur Hand','Verbindung zwischen Hand und Arm','man trägt Uhren daran'],
  'Wimper': ['von außen sichtbar','sitzen an den Augenlidern','schützen vor Schmutz und Dreck','Frauen schminken sie sich mit Tusche'],
  'Lippe': ['von außen sichtbar','gehört zum Mund','weich, wulstig, beweglich, rötlich','man kann damit küssen'],
  'Gesäß': ['von außen sichtbar','sitzt unter dem Rücken','besteht aus zwei "Backen"','man sitzt darauf'],
  'Knöchel': ['von außen sichtbar','ist ein Knochen','Verbindung zwischen Fuß und Bein','gehört zum Fußgelenk'],
  'Niere': ['von außen nicht sichtbar','ist ein Organ','es gibt zwei davon','sieht aus wie eine Bohne'],
  'Wade': ['von außen sichtbar','gehört zum Unterschenkel','hinterer Teil des Unterschenkels','dort entstehen oft Krämpfe'],
  'Fingernagel': ['von außen sichtbar','gehört zu den Fingern','wächst, kann man feilen und lackieren','schützt die Fingerkuppen'],
  'Schlüsselbein': ['von außen sichtbar','gehört zum Schultergürtel','es gibt zwei davon','ist "S-förmig"'],
  'Lid': ['von außen sichtbar','gehört zum Auge','es gibt zwei davon','man kann damit blinzeln'],
  'Augenbraue': ['von außen sichtbar','sitzten über dem Auge','es gibt zwei davon','behaarter Halbbogen über den Lidern'],
  'Gebiss': ['von außen teilweise sichtbar','ist im Mund','besteht aus Kiefer und Zähnen','man kann damit essen'],
  'Fußnagel': ['von außen sichtbar','ist an der Spitze der Zehen','wächst, kann man feilen und lackieren','es gibt an jedem Fuß fünf']
};


final Map nfKuecheMAP = {
  'Arbeitsplatte': ['Ablage','zur Vorbereitung','große Fläche','zum Abstellen von Küchenutensilien'],
  'Toaster': ['Elektroger','zum Zubereiten von Essen','klein und eckig','zum Rösten von Brot'],
  'Spülmittel': ['Putzutensilie','zum Reinigen','flüssig und farbig','zum Säubern von Geschirr'],
  'Tauchsieder': ['Elektrogerät','zum Erhitzen','mit einer Spirale','zum Erhitzen von Wasser'],
  'Mikrowelle': ['Elektrogerät','zum Zubereiten von Essen','mittelgroß und eckig','zum Aufwärmen von Speisen'],
  'Spülmaschine': ['Elektrogerät','zum Reinigen','mit Griff und Leiste','zum Reinigen von Geschirr'],
  'Flaschenöffner': ['Hilfswerkzeug','zum Entfernen von Verschlüssen','klein und meist oval','zum Entfernen von Kronkorken'],
  'Eieruhr': ['Hilfswerkzeug','zum Kochen oder Backen','zylinderförmig','als Wecker zum Kochen'],
  'Küchenrolle': ['Putzutensilie','zum Reinigen','rechteckig und leicht','zum Aufwischen'],
  'Küchenhandtuch': ['Hilfswerkzeug','zum Reinigen','rechteckig und leicht','zum Abtrocknen'],
  'Gefrierfach': ['Elektrogerät','zur Aufbewahrung','groß und eckig','zum eiskalten Lagern von Lebensmitteln'],
  'Dosenöffner': ['Hilfswerkzeug','zum Entfernen von Verschlüssen','mit scharfem rundem Messer','zum Entfernen von Konservendeckeln'],
  'Schneidebrett': ['Kochutensilie','zur Vorbereitung','aus Holz oder Plastik','zum Zerkleinern von Lebensmitteln'],
  'Messerblock': ['Aufbewahrnungsgerät','zur Aufbewahrung','aus Holz und eckig','zur Aufbewahrung von Messern'],
  'Dunstabzugshaube': ['Elektrogerät','zum Kochen','aus Edelstahl mit Filter','zum Absaugen von Kochdunst']
};

final Map nfLaenderMAP = {
  'Island': ['Nordeuropa','südlich des nördlichen Polarkreises','größte Vulkaninsel der Erde','Hauptstadt: Reykjavík'],
  'Tunesien': ['Nordafrika','grenzt an Algerien','das nördlichste Land Afrikas','Hauptstadt: Tunis'],
  'Malta': ['Südeuropa','liegt im Mittelmeer','kleinster Mitgliedsstaat der EU','Hauptstadt: Valletta'],
  'Peru': ['Südamerika','grenzt an Brasilien','das Land der Lamas','Hauptstadt: Lima'],
  'Bolivien': ['zwischen Zentral-, Nord- und Ostasien','grenzt an Argentinen','grenzt an den Titicaca-See','Hauptstadt: Sucre'],
  'Mongolei': ['Südwestafrika','grenzt an China','bekannt für nomadische Viehwirtschaft','Hauptstadt: Ulaanbaatar'],
  'Namibia': ['Südosteuropa','grenzt an Südafrika','hier liegt der Etosha-Nationalpark','Hauptstadt: Windhoek'],
  'Kroatien': ['Ostafrika','grenzt an Ungarn','wird Land der tausend Inseln genannt','Hauptstadt: Zagreb'],
  'Kenia': ['Südamerika','grenzt an Uganda','hier liegt der Nairobi Nationalpark','Hauptstadt: Nairobi'],
  'Ecuador': ['Südasien','grenzt an Kolombien','hier steht der aktive Vulkan Cotopaxi','Hauptstadt: Quito'],
  'Nepal': ['Südasien','grenzt an China','hier liegt ein großer Teil des Himalaya','Hauptstadt: Kathmandu'],
  'Haiti': ['Karibik','grenzt an die Dominikanische Republik','wurde von Kolumbus entdeckt','Hauptstadt: Port-au-Prince'],
  'Russland': ['Osteuropa und Asien','grenzt an China','das flächengrößte Land der Erde','Hauptstadt: Moskau'],
  'Jamaika': ['Karibik','liegt in der Karibik','hierher kommt der Reggae','Hauptstadt: Kingston'],
  'Tansania': ['Ostafrika','grenzt an Kenia','hier steht der Kilimandscharo','Hauptstadt: Dodoma']
};

final Map nfMoebelMAP = {
  'Stehlampe': ['steht frei','im Wohnzimmer','wird an- oder ausgeschaltet','beleuchtet den Raum'],
  'Standuhr': ['steht frei oder hängt an der Wand','im Esszimmer oder Wohnzimmer','läutet zur vollen Stunde','zeigt die Zeit an'],
  'Sitzbank': ['hat meist vier Beine','im Esszimmer oder Wohnzimmer','hat mehr als einen Sitzplatz','für mehrere Personen geeignet'],
  'Barhocker': ['hat meist vier Beine','im Esszimmer oder in der Küche','man sitzt darauf','steht meist an einer Theke'],
  'Servierwagen': ['hat Rollen','im Esszimmer oder in der Küche','man kann Dinge darauf stellen','zum Transportieren von Geschirr und Speisen'],
  'Schirmständer': ['steht auf dem Boden','im Flur oder Eingangsbereich','dient zur Aufbewahrung von Dingen','dient zur Aufbewahrung von Regenschirmen'],
  'Raumteiler': ['steht frei im Raum','in allen Zimmern','ähnelt einer Trennwand','trennt ein Zimmer in zwei Bereiche'],
  'Hollywoodschaukel': ['zum Sitzen oder Liegen','steht draußen','hat mehr als ein Sitzplatz','bewegt sich vor und zurück'],
  'Handtuchhalter': ['steht frei oder ist an der Wand befestigt','im Badezimmer','dient zur Ablage','darauf trocknen Handtücher'],
  'Zeitungsständer': ['steht frei oder ist an der Wand befestigt','im Wohnzimmer','dient zur Ablage','dient zur Ablage von Zeitschriften'],
  'Wickelkommode': ['hat meist vier Beine','im Kinderzimmer','hat oben eine Fläche zum Liegen','Babys werden darauf an- und ausgezogen'],
  'Sideboard': ['hat meist vier Beine','in allen Zimmern','dient zur Aufbewahrung von Dingen','Bezeichnung stammt aus dem Englischen'],
  'Schuhschrank': ['steht oder hängt an der Wand','im Flur oder Eingangsbereich','dient zur Aufbewahrung von Dingen','dient zur Lagerung von Sandalen, Stiefeln, etc.'],
  'Stockbett': ['hat meist vier Beine','im Kinderzimmer oder Schlafzimmer','mehrere Personen liegen darin','zwei Schlafstätten übereinander'],
  'Sitzsack': ['liegt auf dem Boden','im Wohnzimmer oder Kinderzimmer','man sitzt darauf','bequemes Sitzmöbelstück ohne Beine']
};


final Map nfMusikinstrumenteMAP = {
  'Saxophon': ['Blasinstrument','aus Metall','Rohr weitet sich zum Ende','stark vertreten im Jazz'],
  'Akkordeon': ['Handzuginstrument','überwiegend aus Holz','hat links eine Tastatur','wird auch "Quetschkomode" genannt'],
  'Tuba': ['Blasinstrument','aus Metall','tiefstes Blechblasinstrument','nach oben gerichteter Schalltrichter'],
  'Triangel': ['Schlaginstrument','aus Stahl','wird mit Stahlstab geschlagen','gleichseitiges Dreieck'],
  'Bratsche': ['Streichinstrument','aus Holz','wird mit Bogen gestrichen','etwas größer als die Geige'],
  'Dudelsack': ['Blasinstrument','überwiegend aus Holz','hat einen Beutel aus Leder oder Kunststoff','wird meist in Schottland gespielt'],
  'Xylophon': ['Schlaginstrument','aus Holz','aneinander gereihte Klangstäbe','wird oft im Kindergarten gespielt'],
  'Waldhorn': ['Blasinstrument','aus Metall','hat kreisförmig gewundenes Rohr','wird zur Jagd geblasen'],
  'Blockflöte': ['Blasinstrument','aus Holz','schmal, lang, mit Löchern','spielen viele Grundschüler'],
  'Tamburin': ['Schlaginstrument','aus Holz und Metall','Rahmentrommel mit Schellen','wird in einer Hand gehalten, mit der anderen geschlagen'],
  'Drehleier': ['Streichinstrument','überwiegend aus Holz','Seiten von innerem Rad gestrichen','Spieler dreht an Kurbel'],
  'Querflöte': ['Blasinstrument','aus Metall','schmal, lang, mit Klappen','wird seitlich gehalten'],
  'Balalaika': ['Zupfinstrument','aus Holz','hat dreieckigen Resonanzkörper','oft in russischer Volksmusik verwendet'],
  'Ukulele': ['Zupfinstrument','aus Holz','exotischer Klang','sehr kleine Gitarre mit 4 Saiten'],
  'Kontrabass': ['Streichinstrument','aus Holz','wird mit Bogen gestrichen','wird im Lied von den drei Chinesen gespielt']
};


final Map nfObstMAP = {
  'Grapefruit': ['wächst an einem Baum','außen orange und innen rosa','Zitrusfrucht','hat einen bitteren Geschmack'],
  'Kiwi': ['wächst an einer Rebe','außen braun und innen grün','exotische Frucht','hat eine stachelig-haarige Schale'],
  'Granatapfel': ['wächst an einem Baum','rot','exotische Frucht','enthält viele rubinrote Samen'],
  'Heidelbeere': ['wächst an einem Strauch','blau','Beerenobst','färbt Mund und Zähne blau'],
  'Stachelbeere': ['wächst an einem Strauch','grün oder rot','Beerenobst','der Strauch hat stachelige Äste'],
  'Johannisbeere': ['wächst an einem Strauch','schwarz oder rot','Beerenobst','kleine säuerlich schmeckende kugelförmige Früchte'],
  'Zwetschge': ['wächst an einem Baum','lila','Steinobst','wird auch Pflaume genannt'],
  'Mango': ['wächst an einem Baum','innen gelb','exotische Frucht','hat oft faseriges Fruchtfleisch'],
  'Physalis': ['wächst an einem Strauch','orange mit hellbrauner Hülle','heißt auch Blasenkirsche','wird zum Verzieren von Kuchen oder Cocktails benutzt'],
  'Preiselbeere': ['wächst an einem Strauch','rot','Beerenobst','wird oft zu Wildgerichten gegessen'],
  'Mirabelle': ['wächst an einem Baum','gelb','Steinobst','wird oft zu Likör und Marmelade verarbeitet'],
  'Papaya': ['wächst an einem Baum','außen grün und innen orange','exotische Frucht','schmeckt sehr süß'],
  'Litschi': ['wächst an einem Baum','außen rosa-braun und innen weiß','Kernobst','wird oft in thailändischen Gerichten verwendet'],
  'Kokusnuss': ['wächst an einem Baum','außen braun und innen weiß','Steinobst','die darin enthaltene Milch kann man trinken'],
  'Maracuja': ['wächst an einem Baum','außen lila und innen orange','exotische Frucht','wird auch Passionsfrucht genannt']
};



final Map nfPflanzenMAP = {
  'Eberesche': ['Nutzpflanze','sommergrün','hat gefiederte Blätter','wird auch als Vogelbeere bezeichnet'],
  'Hortensie': ['Zierpflanze','sommergrün','hat große Blüten','Blüten haben farbige oder weiße Kelchblättern'],
  'Zypresse': ['Zierpflanze','immergrün','hat Nadeln','prägt die Kulturlandschaft in der Toskana'],
  'Koriander': ['Nutzpflanze','sommergrün','hat Blätter und kugelförmige Samen','wird als Gewürz oder Heilmittel verwendet'],
  'Hyazinthe': ['Zierpflanze','sommergrün','hat eine Blütentraube aus vielen Einzelblüten','duftet süß'],
  'Geranie': ['Zierpflanze','sommergrün','wächst aufrecht oder hängend','wird meist als Balkonpflanze genutzt'],
  'Schlehe': ['Nutzpflanze','sommergrün','hat bitter schmeckende Früchte','hat weiße Blüten'],
  'Mammutbaum': ['Nutzpflanze','immergrün','hat Nadeln','wird sehr alt und gehört zu den größten Bäumen der Erde'],
  'Oregano': ['Nutzpflanze','sommergrün','hat gegenständig angeordnete Blätter','wird in der mediterranen Küche als Gewürz benutzt'],
  'Ringelblume': ['Nutzpflanze','immergrün','blüht gelb oder orange','wird auch Löwenzahn genannt'],
  'Vergissmeinnicht': ['Zierpflanze','sommergrün','hat blaue bis violettfarbene Blüten','gilt als Symbol der Erinnerung'],
  'Löwenmäulchen': ['Zierpflanze','sommergrün','blüht meist gelb, rot oder violett','Blüten sind weit aufgesperrt'],
  'Brennnessel': ['Nutzpflanze','sommergrün','hat mit Haaren besetzte Blätter und Stängel','Berührung ist schmerzhaft'],
  'Bärlauch': ['Nutzpflanze','sommergrün','ist ein Wildgemüse','riecht nach Knoblauch']
};


final Map nfRestaurantMAP = {
  'Trinkgeld': ['Finanzen',	'aus Papier oder Metall', 'wenn man zufrieden war', 'erhält der Kellner'],
  'Besteck': ['Inventar',	'aus Silber oder Edelstahl',	'liegt neben dem Teller',	'wird zum Essen benötigt'],
  'Menü': ['Inventar',	'hat mehrere Gänge',	'ist meist günstiger',	'mittags besondere Angebote'],
  'Speisekarte': ['Inventar',	'klein oder umfangreich',	'wird gelesen',	'enthält Speisen und Getränke'],
  'Tresen': ['Inventar',	'man steht daran',	'trennt Personal und Kundschaft',	'auch Schanktisch genannt'],
  'Vorspeise': ['Gang',	'kleine Portion',	'oft Suppe oder Salat',	'erster Gang'],
  'Tischdecke': ['Dekoration',	'aus Stoff oder Papier',	'rund oder eckig',	'schützt den Tisch'],
  'Dessert': ['Gang',	'meist süß',	'manchmal Käseteller',	'letzter Gang'],
  'Aperitif': ['Getränk',	'kalt', 	'oft Prosecco', 	'bei Ankunft im Restaurant'],
  'Hauptgang': ['Gang',	'meist deftig',	'oft Fleisch oder Fisch',	'größter Gang'],
  'Weinkarte': ['Inventar',	'wird gelesen',	'enthält spezielle Getränke',	'Getränke sind rot, weiß oder rosé'],
  'Zapfhahn': ['Inventar',	'befindet sich an der Theke',	'meist an Fass angeschlossen',	'Armatur einer Bierleitung'],
  'Tageskarte': ['Inventar',	'wird gelesen',	'enthält saisonale Gerichte',	'jeden Tag neu'],
  'Reservierung': ['Termin',	'wird im Voraus getätigt',	'per E-Mail oder Telefon',	'Tisch wird damit freigehalten'],
  'Digestif': ['Getränk',	'kalt',	'oft Magenbitter', 'hilfreich nach dem Essen']
};


final Map nfSportartenMAP = {
  'Basketball': ['meist in einer Halle',	'in der Gruppe',	'mit zwei Mannschaften',	'Ball wird in Korb geworfen'],
  'Eiskunstlauf': ['meist drinnen',	'alleine oder zu zweit',	'Bewegung zu Musik',	'auf dem Eis'],
  'Marathonlauf': ['meist draußen',	'meist alleine',	'Laufsportart',	'sehr lange Strecke'],
  'Baseball': ['meist draußen',	'in der Gruppe',	'Schlagballspiel',	'Ball wird geschlagen und gefangen'],
  'Volleyball': ['meist in einer Halle',	'in der Gruppe',	'mit zwei Mannschaften',	'Ball wird über ein Netz'],
  'Badminton': ['meist in einer Halle',	'zu zweit',	'mit einem Schläger',	'mit einem Federball'],
  'Joggen': ['meist draußen',	'meist alleine',	'Laufsportart',	'längere Strecke'],
  'Judo': ['meist in einer Halle',	'zu zweit',	'Kampfsportart',	'mit weißem Stoffanzug und Gürtel'],
  'Karate': ['meist in einer Halle',	'zu zweit',	'Kampfsportart',	'mit Schlägen, Tritten und Stößen'],
  'Walken': ['meist draußen',	'meist alleine',	'Laufsportart',	'mit zwei Stöcken'],
  'Squash': ['meist in einer Halle',	'alleine oder zu zweit',	'mit einem Schläger',	'mit einem kleinen Ball gegen in die Wand'],
  'Biathlon': ['meist draußen',	'meist alleine',	'Wintersportart',	'beinhaltet Langlauf und Schießen'],
  'Skisprung': ['meist draußen',	'meist alleine',	'Wintersportart',	'von einer Schanze'],
  'Aerobic': ['meist drinnen',	'in der Gruppe',	'Bewegung zu Musik',	'rhytmische Bewegungen'],
  'Snowboard': ['meist draußen',	'meist alleine',	'Wintersportart',	'mit beiden Füßen auf einem Brett']
};


final Map nfStrassenverkehrMAP = {
  'Tankstelle': ['hat einen festen Platz',	'Teil einer Straße',	'am Straßenrand zu finden',	'wird aufgesucht wenn das Benzin leer ist'],
  'Ampel': ['hat einen festen Platz',	'sorgt für Sicherheit',	'muss vom Autofahrer beachtet werden',	'leuchtet rot', 'gelb oder grün'],
  'Krankenwagen': ['bewegt sich fort',	'Verkehrsteilnehmer',	'darf im Notfall über Rot fahren',	'wird bei Unfall mit Verletzten gerufen'],
  'Stau': ['hat einen festen Platz',	'verändert den Verkehrsfluss',	'erfordert langsames Fahren',	'passiert häufig bei stockendem Straßenverkehr'],
  'Bushaltestelle': ['hat einen festen Platz',	'Teil einer Straße',	'Anlaufstelle für ein öffentliches Verkehrsmittel',	'wird von Bussen genutzt'],
  'Fußgängerzone': ['hat einen festen Platz',	'Verkehrsfläche',	'darf mit dem Auto nicht befahren werden',	'wird ausschließlich von Menschen genutzt'],
  'Gehweg': ['hat einen festen Platz',	'Verkehrsfläche',	'darf mit dem Auto nicht befahren werden',	'anderes Wort für Bürgersteig'],
  'Bordstein': ['hat einen festen Platz',	'Teil einer Verkehrsfläche',	'Teil des Gehwegs',	'Rand des Gehwegs'],
  'Zebrastreifen': ['hat einen festen Platz',	'sorgt für Sicherheit',	'muss vom Autofahrer beachtet werden',	'zeigt einen Straßenübergang an'],
  'Kreisverkehr': ['hat einen festen Platz',	'Teil des Straßenverlaufs',	'bietet einen runden Straßenverlauf',	'ersetzt eine Kreuzung'],
  'Radweg': ['hat einen festen Platz',	'Verkehrsfläche',	'muss vom Autofahrer beachtet werden',	'ausschließllich für Farhrräder'],
  'Verkehrsschild': ['hat einen festen Platz',	'sorgt für Sicherheit',	'muss vom Autofahrer beachtet werden',	'zeigt z.B. die erlaubte Geschwindigkeit an'],
  'Leitplanke': ['hat einen festen Platz',	'sorgt für Sicherheit',	'Schutz aus Stahl',	'hindert ein Fahrzeug daran, von der Straße abzukommen'],
  'Blitzer': ['hat einen festen Platz',	'sorgt für Sicherheit',	'überwacht die Einhaltung der Geschwindigkeit',	'anderes Wort für Radarfalle'],
  'Mittelstreifen': ['hat einen festen Platz',	'Teil einer Straße',	'trennt Fahrbahnen',	'meist begrünte Trennung des Verkehrsstroms']
};


final Map nfSupermarktMAP = {
  'Nudeln': ['Nahrungsmittel', 	'bei Grundnahrungsmitteln',	'gelb',	'aus Getreide'],
  'Kaugummi': ['Nahrungsmittel', 	'oft an der Kasse',	'meist weiß',	'wird lange gekaut'],
  'Leberwurst': ['Nahrungsmittel', 	'Fleischtheke',	'rosa oder braun',	'kalbsfleischhaltiger Brotaufstrich'],
  'Eierlikör': ['Nahrungsmittel', 	'Getränkeabteilung',	'gelb und dickflüssig',	'aus Alkohol, Zucker und Eiern'],
  'Heidelbeeren': ['Nahrungsmittel', 	'Obstabteilung',	'dunkelblau',	'wachsen an Sträuchern'],
  'Pizza': ['Nahrungsmittel', 	'Tiefkühltruhe',	'rund und flach',	'italienische Teigwarenspezialität'],
  'Apfelwein': ['Nahrungsmittel', 	'Getränkeabteilung',	'gelb',	'Alkohol aus Äpfeln'],
  'Mettwurst': ['Nahrungsmittel', 	'Fleischtheke',	'rotbraun',	'aus rohem Schweine- und Rindfleisch'],
  'Klopapier': ['kein Nahrungsmittel', 	'Haushaltswarenabteilung',	'meist weiß',	'aus bis zu fünf Papierlagen'],
  'Spülmittel': ['kein Nahrungsmittel', 	'Haushaltswarenabteilung',	'gelb, grün, blau oder weiß',	'aus Zitronensäure und Alkohol zum Abwaschen'],
  'Shampoo': ['kein Nahrungsmittel', 	'Kosmetikabteilung',	'meist weiß und duftend',	'aus flüssiger Masse für die Haare'],
  'Eiskaffee': ['Nahrungsmittel', 	'Getränkeabteilung',	'meist braun',	'Kaltgetränk, zuvor aus Bohnen aufgebrüht'],
  'Geschenkpapier': ['kein Nahrungsmittel', 	'Schreibwarenabteilung',	'aus Papier',	'zum Einpacken von Überraschungen'],
  'Rasierer': ['kein Nahrungsmittel', 	'Kosmetikabteilung',	'bunt und länglich',	'aus Klingen und Stiel'],
  'Eistee': ['Nahrungsmittel', 	'Getränkeabteilung',	'meist braun',	'Kaltgetränk, zuvor aus Blättern aufgegossen']
};


final Map nfTiereMAP = {
  'Schildkröte': ['kein Säugetier',	'Wildtier',	'hat einen Panzer',	'wird sehr alt'],
  'Krokodil': ['kein Säugetier',	'Wildtier',	'hat einen Panzer',	'hat scharfe Zähne'],
  'Meerschweinchen': ['Säugetier',	'Haustier',	'hat Fell',	'tagaktives Nagetier'],
  'Leopard': ['Säugetier',	'Wildtier',	'hat Fell',	'ist sehr schnell'],
  'Jaguar': ['Säugetier',	'Wildtier',	'hat Fell',	'ist auch Symbol einer Automarke'],
  'Wiesel': ['Säugetier',	'Wildtier',	'hat Fell',	'ist flink'],
  'Luchs': ['Säugetier',	'Wildtier',	'hat Fell',	'gehört zur Familie der Wildkatzen'],
  'Hamster': ['Säugetier',	'Haustier',	'hat Fell',	'rennt nachts im Rad'],
  'Lama': ['Säugetier',	'Nutztier',	'hat Fell',	'spuckt'],
  'Otter': ['Säugetier',	'Wildtier',	'hat Fell',	'isst gerne Fisch'],
  'Elch': ['Säugetier',	'Wildtier',	'hat Fell',	'hat ein Geweih und röhrt'],
  'Robbe': ['Säugetier',	'Wildtier',	'hat Fell',	'Kinder werden Heuler genannt'],
  'Pinguin': ['kein Säugetier',	'Wildtier',	'hat Federn',	'ist schwarz und weiß'],
  'Alpaka': ['Säugetier',	'Nutztier',	'hat Fell',	'gehört zur Familie der Kamele'],
  'Delfin': ['Säugetier',	'Wildtier',	'hat eine glatte Haut',	'ist stromlinienförmig und sehr intelligent']
};


final Map nfWerkzeugeMAP = {
  'Zollstock': ['lang',	'aus Holz, Kuststoff oder Metall',	'hat miteinander verbundene gerade Holzteile',	'benötigt man um etwas zu messen'],
  'Kreissäge': ['groß',	'aus Metall',	'hat eine gezackte, runde Schneideplatte',	'benötigt man um Holz und Metall zu zerkleinern'],
  'Dübel': ['klein',	'aus Plastik oder Holz',	'hat eine spitz zulaufende Form',	'benötigt man als Halterung für Schrauben'],
  'Wasserwaage': ['lang',	'aus Holz, Kunststoff und Metall',	'hat eine längliche, rechteckige Form',	'benötigt man um etwas gerade anzubringen'],
  'Bohrmaschine': ['mittelgroß',	'aus Metall und Kunststoff',	'hat ein Gewinde für Aufsätze',	'benötigt man um tiefe Löcher in einer Wand herzustellen'],
  'Lötkolben': ['mittelgroß',	'aus Metall und Kunststoff',	'hat eine stiftartige Form',	'benötigt man um Metalle aufzuschmelzen'],
  'Kabeltrommel': ['mittelgroß',	'aus Kunststoff und Metall',	'hat eine runde Form',	'benötigt man um eine Kunststoffschnur aufzurollen'],
  'Drahtbürste': ['mittelgroß',	'aus Holz und Metall',	'hat einen Holzgriff mit Borsten',	'benötigt man zum Reinigen von Flaschen'],
  'Winkelmesser': ['mittelgroß',	'aus Metall oder Plastik',	'hat eine Maßstabangabe',	'benötigt man für das Ausmessen von Ecken'],
  'Verlängerungskabel': ['lang',	'aus Kunststoff und Metall',	'hat einen Stecker und eine Kupplung',	'benötigt man um Strom zu verlegen'],
  'Motorsäge': ['groß',	'aus Metall',	'hat eine lange und gezackte Spitze',	'benötigt man um Holz zu schneiden'],
  'Handbohrer': ['mittelgroß',	'aus Metall',	'hat einen Seitengriff',	'benötigt man um ohne Strom Löcher herzustellen'],
  'Schweißgerät': ['groß',	'aus Metall und Kunststoff',	'hat einen viereckigen Kasten',	'benötigt man um Dinge mittels Wärme zu verbinden'],
  'Schleifpapier': ['mittelgroß',	'aus Papier und Kunststoff',	'hat eine Körnung',	'benötigt man um eine raue Fläche zu glätten'],
  'Lüsterklemme': ['klein',	'aus Kunststoff und Metall',	'hat Klemmschrauben',	'benötigt man um eine Lampe am Strom anzuschließen']
};
